// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

import Foundation

public enum TSAccessFlags: Int, Sendable, Codable {
    case owner_read = 0
    case owner_write = 1
    case owner_execute = 2
    case group_read = 3
    case group_write = 4
    case group_execute = 5
    case system_read = 6
    case system_write = 7
    case system_execute = 8
}
