// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primtypes.djinni

import UIKit

public struct TSAssortedPrimitives: Sendable, Equatable, Hashable, Codable {
    public let b: Bool
    public let eight: Int8
    public let sixteen: Int16
    public let thirtytwo: Int32
    public let sixtyfour: Int64
    public let fthirtytwo: CGFloat
    public let fsixtyfour: Double
    public let oB: Bool?
    public let oEight: Int8?
    public let oSixteen: Int16?
    public let oThirtytwo: Int32?
    public let oSixtyfour: Int64?
    public let oFthirtytwo: CGFloat?
    public let oFsixtyfour: Double?

    public init(
        b: Bool,
        eight: Int8,
        sixteen: Int16,
        thirtytwo: Int32,
        sixtyfour: Int64,
        fthirtytwo: CGFloat,
        fsixtyfour: Double,
        oB: Bool? = nil,
        oEight: Int8? = nil,
        oSixteen: Int16? = nil,
        oThirtytwo: Int32? = nil,
        oSixtyfour: Int64? = nil,
        oFthirtytwo: CGFloat? = nil,
        oFsixtyfour: Double? = nil
    ) {
        self.b = b
        self.eight = eight
        self.sixteen = sixteen
        self.thirtytwo = thirtytwo
        self.sixtyfour = sixtyfour
        self.fthirtytwo = fthirtytwo
        self.fsixtyfour = fsixtyfour
        self.oB = oB
        self.oEight = oEight
        self.oSixteen = oSixteen
        self.oThirtytwo = oThirtytwo
        self.oSixtyfour = oSixtyfour
        self.oFthirtytwo = oFthirtytwo
        self.oFsixtyfour = oFsixtyfour
    }
}
