// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

import Foundation

/** Record returned by a client */
public struct TSClientReturnedRecord: Sendable {
    public let recordId: Int64
    public let content: String
    public let misc: String?

    public init(
        recordId: Int64,
        content: String,
        misc: String? = nil
    ) {
        self.recordId = recordId
        self.content = content
        self.misc = misc
    }
}
