// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

import Foundation

/** Record containing constants */
public struct TSConstants: Sendable, Equatable, Hashable, Codable {
}
