// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

import Foundation

public struct TSDateRecord: Sendable {
    public let createdAt: Date

    public init(createdAt: Date) {
        self.createdAt = createdAt
    }
}
