// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum.djinni

import Foundation

public struct TSEnumUsageRecord: Sendable, Equatable, Hashable, Codable {
    public let e: TSColor
    public let o: TSColor?
    public let l: [TSColor]
    public let s: Set<TSColor>
    public let m: [TSColor: TSColor]

    public init(
        e: TSColor,
        o: TSColor? = nil,
        l: [TSColor],
        s: Set<TSColor>,
        m: [TSColor: TSColor]
    ) {
        self.e = e
        self.o = o
        self.l = l
        self.s = s
        self.m = m
    }
}
