// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

import Foundation

/** Extended record */
public struct TSExtendedRecord: Sendable {
    public let foo: Bool

    public init(foo: Bool) {
        self.foo = foo
    }
}
