// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

import Foundation

public struct TSMapRecord: Sendable {
    public let map: [String: Int64]
    public let imap: [Int32: Int32]

    public init(
        map: [String: Int64],
        imap: [Int32: Int32]
    ) {
        self.map = map
        self.imap = imap
    }
}
