// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

import Foundation

public struct TSNestedCollection: Sendable, Equatable, Hashable, Codable {
    public let setList: [Set<String>]

    public init(setList: [Set<String>]) {
        self.setList = setList
    }
}
