// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

import Foundation

public struct TSPrimitiveList: Sendable, Equatable, Hashable, Codable {
    public let list: [Int64]

    public init(list: [Int64]) {
        self.list = list
    }
}
