// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

import Foundation

public struct TSRecordWithDurationAndDerivings: Sendable {
    public let dt: TimeInterval

    public init(dt: TimeInterval) {
        self.dt = dt
    }
}
