// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

import Foundation

public struct TSRecordUsingExtendedRecord: Sendable, Equatable, Hashable, Codable {
    public let er: TSExtendedRecord

    public init(er: TSExtendedRecord) {
        self.er = er
    }
}
