// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

import Foundation

public struct TSRecordWithFlags: Sendable {
    public let access: TSAccessFlags

    public init(access: TSAccessFlags) {
        self.access = access
    }
}
