// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

import Foundation

public struct TSRecordWithNestedDerivings: Sendable, Equatable, Hashable, Codable {
    public let key: Int32
    public let rec: TSRecordWithDerivings

    public init(
        key: Int32,
        rec: TSRecordWithDerivings
    ) {
        self.key = key
        self.rec = rec
    }
}
