// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

import Foundation

public struct TSSetRecord: Sendable, Equatable, Hashable, Codable {
    public let set: Set<String>
    public let iset: Set<Int32>

    public init(
        set: Set<String>,
        iset: Set<Int32>
    ) {
        self.set = set
        self.iset = iset
    }
}
