// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

public struct TSSwiftTestTextStyle: Sendable, Equatable, Hashable, Codable {
    public let color: Int32
    public let letterCase: TSSwiftTestLetterCase

    public init(
        color: Int32,
        letterCase: TSSwiftTestLetterCase
    ) {
        self.color = color
        self.letterCase = letterCase
    }
}
