// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

/**
 * ============================================================
 * Test: Nested records
 * Verifies: correct type references between generated types
 * ============================================================
 */
public struct TSSwiftTestNested: Sendable, Equatable, Hashable, Codable {
    public let label: TSSwiftTestLabel
    public let color: TSSwiftTestColor
    public let style: TSSwiftTestTextStyle

    public init(
        label: TSSwiftTestLabel,
        color: TSSwiftTestColor,
        style: TSSwiftTestTextStyle
    ) {
        self.label = label
        self.color = color
        self.style = style
    }
}
