// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

/** Enum with multi-word cases (underscore-separated in Djinni) */
public enum TSSwiftTestShadowElevation: Int, Sendable {
    case `none` = 0
    case low_Shadow = 1
    case medium_Shadow = 2
    case high_Shadow = 3
}
