// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

/**
 * ============================================================
 * Test: Optional fields
 * Verifies: T? type, = nil default in init
 * ============================================================
 */
public struct TSSwiftTestOptionals: Sendable, Equatable, Hashable, Codable {
    public let requiredField: String
    public let optionalString: String?
    public let optionalInt: Int32?
    public let optionalEnum: TSSwiftTestColor?
    public let optionalRecord: TSSwiftTestAllPrimitives?
    public let optionalList: [String]?

    public init(
        requiredField: String,
        optionalString: String? = nil,
        optionalInt: Int32? = nil,
        optionalEnum: TSSwiftTestColor? = nil,
        optionalRecord: TSSwiftTestAllPrimitives? = nil,
        optionalList: [String]? = nil
    ) {
        self.requiredField = requiredField
        self.optionalString = optionalString
        self.optionalInt = optionalInt
        self.optionalEnum = optionalEnum
        self.optionalRecord = optionalRecord
        self.optionalList = optionalList
    }
}
