// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

/**
 * ============================================================
 * Test: Enum default values in records
 * Verifies: default value conversion (EnumType::Value -> .value)
 * ============================================================
 */
public enum TSSwiftTestLetterCase: Int, Sendable {
    case `default` = 0
    case upper = 1
    case lower = 2
}
