// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import UIKit

public struct TSSwiftTestLabel: Sendable {
    public let textColor: Int32
    public let fontSize: CGFloat
    public let text: String
    public let isBold: Bool

    public init(
        textColor: Int32,
        fontSize: CGFloat,
        text: String,
        isBold: Bool
    ) {
        self.textColor = textColor
        self.fontSize = fontSize
        self.text = text
        self.isBold = isBold
    }
}
