// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

/**
 * ============================================================
 * Test: Collection types
 * Verifies: list -> [T], set -> Set<T>, map -> [K: V]
 * ============================================================
 */
public struct TSSwiftTestCollections: Sendable {
    public let stringList: [String]
    public let intSet: Set<Int32>
    public let stringToIntMap: [String: Int64]
    public let nestedList: [[String]]
    public let enumList: [TSSwiftTestColor]
    public let enumMap: [TSSwiftTestColor: String]

    public init(
        stringList: [String],
        intSet: Set<Int32>,
        stringToIntMap: [String: Int64],
        nestedList: [[String]],
        enumList: [TSSwiftTestColor],
        enumMap: [TSSwiftTestColor: String]
    ) {
        self.stringList = stringList
        self.intSet = intSet
        self.stringToIntMap = stringToIntMap
        self.nestedList = nestedList
        self.enumList = enumList
        self.enumMap = enumMap
    }
}
