// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import Foundation

/**
 * ============================================================
 * Test: Record with doc comments
 * Verifies: doc comments are preserved in Swift output
 * ============================================================
 * A documented record for testing
 * This has multi-line documentation
 */
public struct TSSwiftTestDocumented: Sendable {
    /** The main label text */
    public let text: String
    /** Whether the label is visible */
    public let visible: Bool

    public init(
        text: String,
        visible: Bool
    ) {
        self.text = text
        self.visible = visible
    }
}
