// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

import UIKit

/**
 * ============================================================
 * Test: Record inheritance (extends) — must be flattened
 * Verifies: super fields appear first, all in one struct
 * ============================================================
 */
public struct TSSwiftTestBaseLabel: Sendable, Equatable, Hashable, Codable {
    public let textColor: Int32
    public let fontSize: CGFloat

    public init(
        textColor: Int32,
        fontSize: CGFloat
    ) {
        self.textColor = textColor
        self.fontSize = fontSize
    }
}
