// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

import Foundation

public struct TSWcharTestRec: Sendable {
    public let s: String

    public init(s: String) {
        self.s = s
    }
}
