// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestLabel.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSwiftTestLabel::NativeSwiftTestLabel() = default;

NativeSwiftTestLabel::~NativeSwiftTestLabel() = default;

auto NativeSwiftTestLabel::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestLabel>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.text_color)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.font_size)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.text)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.is_bold)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestLabel::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestLabel>::get();
    ::testsuite::SwiftTestLabel model;
    model.mTextColor = ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mTextColor));
    model.mFontSize = ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mFontSize));
    model.mText = ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mText));
    model.mIsBold = ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mIsBold));
    return model;
}

} // namespace djinni_generated
