// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestBaseLabel.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSwiftTestBaseLabel::NativeSwiftTestBaseLabel() = default;

NativeSwiftTestBaseLabel::~NativeSwiftTestBaseLabel() = default;

auto NativeSwiftTestBaseLabel::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestBaseLabel>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.text_color)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.font_size)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestBaseLabel::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestBaseLabel>::get();
    ::testsuite::SwiftTestBaseLabel model;
    model.mTextColor = ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mTextColor));
    model.mFontSize = ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mFontSize));
    return model;
}

} // namespace djinni_generated
