// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_interface.hpp"

namespace djinni_generated {

class NativeSwiftTestInterface final : ::djinni::JniInterface<::testsuite::SwiftTestInterface, NativeSwiftTestInterface> {
public:
    using CppType = std::shared_ptr<::testsuite::SwiftTestInterface>;
    using CppOptType = std::shared_ptr<::testsuite::SwiftTestInterface>;
    using JniType = jobject;

    using Boxed = NativeSwiftTestInterface;

    ~NativeSwiftTestInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSwiftTestInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSwiftTestInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSwiftTestInterface();
    friend ::djinni::JniClass<NativeSwiftTestInterface>;
    friend ::djinni::JniInterface<::testsuite::SwiftTestInterface, NativeSwiftTestInterface>;

};

} // namespace djinni_generated
