// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_single_field.hpp"

namespace djinni_generated {

class NativeSwiftTestSingleField final {
public:
    using CppType = ::testsuite::SwiftTestSingleField;
    using JniType = jobject;

    using Boxed = NativeSwiftTestSingleField;

    ~NativeSwiftTestSingleField();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSwiftTestSingleField();
    friend ::djinni::JniClass<NativeSwiftTestSingleField>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/SwiftTestSingleField") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_mValue { ::djinni::jniGetFieldID(clazz.get(), "mValue", "Ljava/lang/String;") };
};

} // namespace djinni_generated
