// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_letter_case.hpp"

namespace djinni_generated {

class NativeSwiftTestLetterCase final : ::djinni::JniEnum {
public:
    using CppType = ::testsuite::SwiftTestLetterCase;
    using JniType = jobject;

    using Boxed = NativeSwiftTestLetterCase;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeSwiftTestLetterCase>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeSwiftTestLetterCase>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeSwiftTestLetterCase() : JniEnum("com/dropbox/djinni/test/SwiftTestLetterCase") {}
    friend ::djinni::JniClass<NativeSwiftTestLetterCase>;
};

} // namespace djinni_generated
