// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_base_label.hpp"

namespace djinni_generated {

class NativeSwiftTestBaseLabel final {
public:
    using CppType = ::testsuite::SwiftTestBaseLabel;
    using JniType = jobject;

    using Boxed = NativeSwiftTestBaseLabel;

    ~NativeSwiftTestBaseLabel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSwiftTestBaseLabel();
    friend ::djinni::JniClass<NativeSwiftTestBaseLabel>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/SwiftTestBaseLabel") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IF)V") };
    const jfieldID field_mTextColor { ::djinni::jniGetFieldID(clazz.get(), "mTextColor", "I") };
    const jfieldID field_mFontSize { ::djinni::jniGetFieldID(clazz.get(), "mFontSize", "F") };
};

} // namespace djinni_generated
