// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestSingleField.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSwiftTestSingleField::NativeSwiftTestSingleField() = default;

NativeSwiftTestSingleField::~NativeSwiftTestSingleField() = default;

auto NativeSwiftTestSingleField::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestSingleField>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.value)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestSingleField::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestSingleField>::get();
    ::testsuite::SwiftTestSingleField model;
    model.mValue = ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mValue));
    return model;
}

} // namespace djinni_generated
