// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestCollections.hpp"  // my header
#include "Marshal.hpp"
#include "NativeSwiftTestColor.hpp"

namespace djinni_generated {

NativeSwiftTestCollections::NativeSwiftTestCollections() = default;

NativeSwiftTestCollections::~NativeSwiftTestCollections() = default;

auto NativeSwiftTestCollections::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestCollections>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni::String>::fromCpp(jniEnv, c.string_list)),
                                                           ::djinni::get(::djinni::Set<::djinni::I32>::fromCpp(jniEnv, c.int_set)),
                                                           ::djinni::get(::djinni::Map<::djinni::String, ::djinni::I64>::fromCpp(jniEnv, c.string_to_int_map)),
                                                           ::djinni::get(::djinni::List<::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.nested_list)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NativeSwiftTestColor>::fromCpp(jniEnv, c.enum_list)),
                                                           ::djinni::get(::djinni::Map<::djinni_generated::NativeSwiftTestColor, ::djinni::String>::fromCpp(jniEnv, c.enum_map)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestCollections::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestCollections>::get();
    ::testsuite::SwiftTestCollections model;
    model.mStringList = ::djinni::List<::djinni::String>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mStringList));
    model.mIntSet = ::djinni::Set<::djinni::I32>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mIntSet));
    model.mStringToIntMap = ::djinni::Map<::djinni::String, ::djinni::I64>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mStringToIntMap));
    model.mNestedList = ::djinni::List<::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mNestedList));
    model.mEnumList = ::djinni::List<::djinni_generated::NativeSwiftTestColor>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mEnumList));
    model.mEnumMap = ::djinni::Map<::djinni_generated::NativeSwiftTestColor, ::djinni::String>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mEnumMap));
    return model;
}

} // namespace djinni_generated
