// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_all_primitives.hpp"

namespace djinni_generated {

class NativeSwiftTestAllPrimitives final {
public:
    using CppType = ::testsuite::SwiftTestAllPrimitives;
    using JniType = jobject;

    using Boxed = NativeSwiftTestAllPrimitives;

    ~NativeSwiftTestAllPrimitives();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSwiftTestAllPrimitives();
    friend ::djinni::JniClass<NativeSwiftTestAllPrimitives>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/SwiftTestAllPrimitives") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZBSIJFDLjava/lang/String;[BLjava/util/Date;)V") };
    const jfieldID field_mMyBool { ::djinni::jniGetFieldID(clazz.get(), "mMyBool", "Z") };
    const jfieldID field_mMyI8 { ::djinni::jniGetFieldID(clazz.get(), "mMyI8", "B") };
    const jfieldID field_mMyI16 { ::djinni::jniGetFieldID(clazz.get(), "mMyI16", "S") };
    const jfieldID field_mMyI32 { ::djinni::jniGetFieldID(clazz.get(), "mMyI32", "I") };
    const jfieldID field_mMyI64 { ::djinni::jniGetFieldID(clazz.get(), "mMyI64", "J") };
    const jfieldID field_mMyF32 { ::djinni::jniGetFieldID(clazz.get(), "mMyF32", "F") };
    const jfieldID field_mMyF64 { ::djinni::jniGetFieldID(clazz.get(), "mMyF64", "D") };
    const jfieldID field_mMyString { ::djinni::jniGetFieldID(clazz.get(), "mMyString", "Ljava/lang/String;") };
    const jfieldID field_mMyBinary { ::djinni::jniGetFieldID(clazz.get(), "mMyBinary", "[B") };
    const jfieldID field_mMyDate { ::djinni::jniGetFieldID(clazz.get(), "mMyDate", "Ljava/util/Date;") };
};

} // namespace djinni_generated
