// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_text_style.hpp"

namespace djinni_generated {

class NativeSwiftTestTextStyle final {
public:
    using CppType = ::testsuite::SwiftTestTextStyle;
    using JniType = jobject;

    using Boxed = NativeSwiftTestTextStyle;

    ~NativeSwiftTestTextStyle();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSwiftTestTextStyle();
    friend ::djinni::JniClass<NativeSwiftTestTextStyle>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/SwiftTestTextStyle") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILcom/dropbox/djinni/test/SwiftTestLetterCase;)V") };
    const jfieldID field_mColor { ::djinni::jniGetFieldID(clazz.get(), "mColor", "I") };
    const jfieldID field_mLetterCase { ::djinni::jniGetFieldID(clazz.get(), "mLetterCase", "Lcom/dropbox/djinni/test/SwiftTestLetterCase;") };
};

} // namespace djinni_generated
