// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestExternOptional.hpp"  // my header
#include "Marshal.hpp"
#include "TestColorJni.h"
#include "UserActionJni.h"

namespace djinni_generated {

NativeSwiftTestExternOptional::NativeSwiftTestExternOptional() = default;

NativeSwiftTestExternOptional::~NativeSwiftTestExternOptional() = default;

auto NativeSwiftTestExternOptional::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestExternOptional>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::TestColorJni>::fromCpp(jniEnv, c.opt_color)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::UserActionJni>::fromCpp(jniEnv, c.opt_action)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestExternOptional::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestExternOptional>::get();
    ::testsuite::SwiftTestExternOptional model;
    model.mName = ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName));
    model.mOptColor = ::djinni::Optional<std::optional, ::djinni::TestColorJni>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mOptColor));
    model.mOptAction = ::djinni::Optional<std::optional, ::djinni::UserActionJni>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mOptAction));
    return model;
}

} // namespace djinni_generated
