// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestInterface.hpp"  // my header
#include "Marshal.hpp"
#include "NativeSwiftTestColor.hpp"

namespace djinni_generated {

NativeSwiftTestInterface::NativeSwiftTestInterface() : ::djinni::JniInterface<::testsuite::SwiftTestInterface, NativeSwiftTestInterface>("com/dropbox/djinni/test/SwiftTestInterface$CppProxy") {}

NativeSwiftTestInterface::~NativeSwiftTestInterface() = default;


CJNIEXPORT void JNICALL Java_com_dropbox_djinni_test_SwiftTestInterface_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        delete reinterpret_cast<::djinni::CppProxyHandle<::testsuite::SwiftTestInterface>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_dropbox_djinni_test_SwiftTestInterface_00024CppProxy_native_1doSomething(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_input)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::testsuite::SwiftTestInterface>(nativeRef);
        auto r = ref->do_something(::djinni::String::toCpp(jniEnv, j_input));
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_dropbox_djinni_test_SwiftTestInterface_00024CppProxy_native_1getColor(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        const auto& ref = ::djinni::objectFromHandleAddress<::testsuite::SwiftTestInterface>(nativeRef);
        auto r = ref->get_color();
        return ::djinni::release(::djinni_generated::NativeSwiftTestColor::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
