// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestEmpty.hpp"  // my header

namespace djinni_generated {

NativeSwiftTestEmpty::NativeSwiftTestEmpty() = default;

NativeSwiftTestEmpty::~NativeSwiftTestEmpty() = default;

auto NativeSwiftTestEmpty::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    (void)c; // Suppress warnings in release builds for empty records
    const auto& data = ::djinni::JniClass<NativeSwiftTestEmpty>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor)};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestEmpty::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 1);
    assert(j != nullptr);
    (void)j; // Suppress warnings in release builds for empty records
    ::testsuite::SwiftTestEmpty model;
    return model;
}

} // namespace djinni_generated
