// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_color.hpp"

namespace djinni_generated {

class NativeSwiftTestColor final : ::djinni::JniEnum {
public:
    using CppType = ::testsuite::SwiftTestColor;
    using JniType = jobject;

    using Boxed = NativeSwiftTestColor;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeSwiftTestColor>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeSwiftTestColor>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeSwiftTestColor() : JniEnum("com/dropbox/djinni/test/SwiftTestColor") {}
    friend ::djinni::JniClass<NativeSwiftTestColor>;
};

} // namespace djinni_generated
