// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestOptionals.hpp"  // my header
#include "Marshal.hpp"
#include "NativeSwiftTestAllPrimitives.hpp"
#include "NativeSwiftTestColor.hpp"

namespace djinni_generated {

NativeSwiftTestOptionals::NativeSwiftTestOptionals() = default;

NativeSwiftTestOptionals::~NativeSwiftTestOptionals() = default;

auto NativeSwiftTestOptionals::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestOptionals>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.required_field)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(jniEnv, c.optional_string)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(jniEnv, c.optional_int)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni_generated::NativeSwiftTestColor>::fromCpp(jniEnv, c.optional_enum)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni_generated::NativeSwiftTestAllPrimitives>::fromCpp(jniEnv, c.optional_record)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.optional_list)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestOptionals::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestOptionals>::get();
    ::testsuite::SwiftTestOptionals model;
    model.mRequiredField = ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mRequiredField));
    model.mOptionalString = ::djinni::Optional<std::optional, ::djinni::String>::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mOptionalString));
    model.mOptionalInt = ::djinni::Optional<std::optional, ::djinni::I32>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mOptionalInt));
    model.mOptionalEnum = ::djinni::Optional<std::optional, ::djinni_generated::NativeSwiftTestColor>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mOptionalEnum));
    model.mOptionalRecord = ::djinni::Optional<std::optional, ::djinni_generated::NativeSwiftTestAllPrimitives>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mOptionalRecord));
    model.mOptionalList = ::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mOptionalList));
    return model;
}

} // namespace djinni_generated
