// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_extern_optional.hpp"

namespace djinni_generated {

class NativeSwiftTestExternOptional final {
public:
    using CppType = ::testsuite::SwiftTestExternOptional;
    using JniType = jobject;

    using Boxed = NativeSwiftTestExternOptional;

    ~NativeSwiftTestExternOptional();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSwiftTestExternOptional();
    friend ::djinni::JniClass<NativeSwiftTestExternOptional>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/SwiftTestExternOptional") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Landroid/graphics/Color;Lcom/example/UserAction;)V") };
    const jfieldID field_mName { ::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;") };
    const jfieldID field_mOptColor { ::djinni::jniGetFieldID(clazz.get(), "mOptColor", "Landroid/graphics/Color;") };
    const jfieldID field_mOptAction { ::djinni::jniGetFieldID(clazz.get(), "mOptAction", "Lcom/example/UserAction;") };
};

} // namespace djinni_generated
