// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "NativeSwiftTestNested.hpp"  // my header
#include "NativeSwiftTestColor.hpp"
#include "NativeSwiftTestLabel.hpp"
#include "NativeSwiftTestTextStyle.hpp"

namespace djinni_generated {

NativeSwiftTestNested::NativeSwiftTestNested() = default;

NativeSwiftTestNested::~NativeSwiftTestNested() = default;

auto NativeSwiftTestNested::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSwiftTestNested>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeSwiftTestLabel::fromCpp(jniEnv, c.label)),
                                                           ::djinni::get(::djinni_generated::NativeSwiftTestColor::fromCpp(jniEnv, c.color)),
                                                           ::djinni::get(::djinni_generated::NativeSwiftTestTextStyle::fromCpp(jniEnv, c.style)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSwiftTestNested::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSwiftTestNested>::get();
    ::testsuite::SwiftTestNested model;
    model.mLabel = ::djinni_generated::NativeSwiftTestLabel::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mLabel));
    model.mColor = ::djinni_generated::NativeSwiftTestColor::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mColor));
    model.mStyle = ::djinni_generated::NativeSwiftTestTextStyle::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mStyle));
    return model;
}

} // namespace djinni_generated
