// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_label.hpp"

namespace djinni_generated {

class NativeSwiftTestLabel final {
public:
    using CppType = ::testsuite::SwiftTestLabel;
    using JniType = jobject;

    using Boxed = NativeSwiftTestLabel;

    ~NativeSwiftTestLabel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSwiftTestLabel();
    friend ::djinni::JniClass<NativeSwiftTestLabel>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/SwiftTestLabel") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(IFLjava/lang/String;Z)V") };
    const jfieldID field_mTextColor { ::djinni::jniGetFieldID(clazz.get(), "mTextColor", "I") };
    const jfieldID field_mFontSize { ::djinni::jniGetFieldID(clazz.get(), "mFontSize", "F") };
    const jfieldID field_mText { ::djinni::jniGetFieldID(clazz.get(), "mText", "Ljava/lang/String;") };
    const jfieldID field_mIsBold { ::djinni::jniGetFieldID(clazz.get(), "mIsBold", "Z") };
};

} // namespace djinni_generated
