// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "djinni_support.hpp"
#include "swift_test_shadow_elevation.hpp"

namespace djinni_generated {

class NativeSwiftTestShadowElevation final : ::djinni::JniEnum {
public:
    using CppType = ::testsuite::SwiftTestShadowElevation;
    using JniType = jobject;

    using Boxed = NativeSwiftTestShadowElevation;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeSwiftTestShadowElevation>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeSwiftTestShadowElevation>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeSwiftTestShadowElevation() : JniEnum("com/dropbox/djinni/test/SwiftTestShadowElevation") {}
    friend ::djinni::JniClass<NativeSwiftTestShadowElevation>;
};

} // namespace djinni_generated
