// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test

/** Record returned by a client */
data class ClientReturnedRecord(
    val mRecordId: Long,
    val mContent: String,
    val mMisc: String?
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ClientReturnedRecord

        if (mRecordId != other.mRecordId) return false
        if (mContent != other.mContent) return false
        if (mMisc != other.mMisc) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mRecordId.hashCode()
        hashCode = hashCode * 31 + mContent.hashCode()
        hashCode = hashCode * 31 + (mMisc?.hashCode() ?: 0)
        return hashCode
    }

    override fun toString(): String  {
        return "ClientReturnedRecord {" +
                "mRecordId=" + mRecordId +
                "," + "mContent=" + mContent +
                "," + "mMisc=" + mMisc +
        "}"
    }

}
