// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test

/** Extended record */
data class ExtendedRecord(
    val mFoo: Boolean
) {
    companion object {
        val EXTENDED_RECORD_CONST: ExtendedRecord =  ExtendedRecord(
            true /* mFoo */ )
    }

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ExtendedRecord

        if (mFoo != other.mFoo) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mFoo.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "ExtendedRecord {" +
                "mFoo=" + mFoo +
        "}"
    }

}
