// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test

import java.util.ArrayList
import java.util.HashMap

data class MapListRecord(
    val mMapList: ArrayList<HashMap<String, Long>>
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as MapListRecord

        if (mMapList != other.mMapList) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mMapList.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "MapListRecord {" +
                "mMapList=" + mMapList +
        "}"
    }

}
