// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from no_constructor.djinni

package com.dropbox.djinni.test

data class NoConstructorRecordNative(
    val mFirstValue: Int,
    val mSecondValue: String
) {
    companion object {
        val RECORD_CONST_VALUE: String = "test"
        /** Weirdness in casing should be preserved: this should become XXXWeirdCase in CamelCase */
        val XXXWEIRD_CASE: Int = 1
    }

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as NoConstructorRecordNative

        if (mFirstValue != other.mFirstValue) return false
        if (mSecondValue != other.mSecondValue) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mFirstValue
        hashCode = hashCode * 31 + mSecondValue.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "NoConstructorRecordNative {" +
                "mFirstValue=" + mFirstValue +
                "," + "mSecondValue=" + mSecondValue +
        "}"
    }

}
