// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test

import djinni.test2.Test2.PersistingState

data class RecordWithEmbeddedCppProto(
    val mState: PersistingState
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as RecordWithEmbeddedCppProto


        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + ()
        return hashCode
    }

    override fun toString(): String  {
        return "RecordWithEmbeddedCppProto {" +
                "mState=" + mState +
        "}"
    }

}
