// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

/**
 * ============================================================
 * Test: Interface (should be completely skipped)
 * Verifies: no Swift file generated for interfaces
 * ============================================================
 */
abstract class SwiftTestInterface {
    abstract fun doSomething(input: String): String

    abstract fun getColor(): SwiftTestColor

    class CppProxy(private val nativeRef: Long) : SwiftTestInterface() {
        private val destroyed = AtomicBoolean(false)

        init {
            if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @kotlin.jvm.JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }

        override fun doSomething(input: String): String {
            assert(!destroyed.get()) { "trying to use a destroyed object" }
            return native_doSomething(nativeRef, input)
        }
        private external fun native_doSomething(_nativeRef: Long, input: String): String

        override fun getColor(): SwiftTestColor {
            assert(!destroyed.get()) { "trying to use a destroyed object" }
            return native_getColor(nativeRef)
        }
        private external fun native_getColor(_nativeRef: Long): SwiftTestColor
    }
}
