// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

data class SwiftTestLabel(
    override val mTextColor: Int,
    override val mFontSize: Float,
    val mText: String,
    val mIsBold: Boolean
) : SwiftTestBaseLabel(mTextColor, mFontSize) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestLabel

        if (mTextColor != other.mTextColor) return false
        if (mFontSize != other.mFontSize) return false
        if (mText != other.mText) return false
        if (mIsBold != other.mIsBold) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mTextColor
        hashCode = hashCode * 31 + mFontSize.hashCode()
        hashCode = hashCode * 31 + mText.hashCode()
        hashCode = hashCode * 31 + mIsBold.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestLabel {" +
                "mTextColor=" + mTextColor +
                "," + "mFontSize=" + mFontSize +
                "," + "mText=" + mText +
                "," + "mIsBold=" + mIsBold +
        "}"
    }

}
