// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

/**
 * ============================================================
 * Test: Record inheritance (extends) — must be flattened
 * Verifies: super fields appear first, all in one struct
 * ============================================================
 */
open class SwiftTestBaseLabel(
    open val mTextColor: Int,
    open val mFontSize: Float
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestBaseLabel

        if (mTextColor != other.mTextColor) return false
        if (mFontSize != other.mFontSize) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mTextColor
        hashCode = hashCode * 31 + mFontSize.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestBaseLabel {" +
                "mTextColor=" + mTextColor +
                "," + "mFontSize=" + mFontSize +
        "}"
    }

}
