// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

data class SwiftTestTextStyle(
    val mColor: Int,
    val mLetterCase: SwiftTestLetterCase
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestTextStyle

        if (mColor != other.mColor) return false
        if (mLetterCase != other.mLetterCase) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mColor
        hashCode = hashCode * 31 + mLetterCase.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestTextStyle {" +
                "mColor=" + mColor +
                "," + "mLetterCase=" + mLetterCase +
        "}"
    }

}
