// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

/** Extern type in optional field (skip should still apply) */
data class SwiftTestExternOptional(
    val mName: String,
    val mOptColor: android.graphics.Color?,
    val mOptAction: com.example.UserAction?
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestExternOptional

        if (mName != other.mName) return false
        if (mOptColor != other.mOptColor) return false
        if (mOptAction != other.mOptAction) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mName.hashCode()
        hashCode = hashCode * 31 + (mOptColor?.hashCode() ?: 0)
        hashCode = hashCode * 31 + (mOptAction?.hashCode() ?: 0)
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestExternOptional {" +
                "mName=" + mName +
                "," + "mOptColor=" + mOptColor +
                "," + "mOptAction=" + mOptAction +
        "}"
    }

}
