// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

/**
 * ============================================================
 * Test: Nested records
 * Verifies: correct type references between generated types
 * ============================================================
 */
data class SwiftTestNested(
    val mLabel: SwiftTestLabel,
    val mColor: SwiftTestColor,
    val mStyle: SwiftTestTextStyle
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestNested

        if (mLabel != other.mLabel) return false
        if (mColor != other.mColor) return false
        if (mStyle != other.mStyle) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mLabel.hashCode()
        hashCode = hashCode * 31 + mColor.hashCode()
        hashCode = hashCode * 31 + mStyle.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestNested {" +
                "mLabel=" + mLabel +
                "," + "mColor=" + mColor +
                "," + "mStyle=" + mStyle +
        "}"
    }

}
