// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

import java.util.Date

/**
 * ============================================================
 * Test: All primitive types in a single record
 * Verifies: type mapping for every primitive
 * ============================================================
 */
data class SwiftTestAllPrimitives(
    val mMyBool: Boolean,
    val mMyI8: Byte,
    val mMyI16: Short,
    val mMyI32: Int,
    val mMyI64: Long,
    val mMyF32: Float,
    val mMyF64: Double,
    val mMyString: String,
    val mMyBinary: ByteArray,
    val mMyDate: Date
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestAllPrimitives

        if (mMyBool != other.mMyBool) return false
        if (mMyI8 != other.mMyI8) return false
        if (mMyI16 != other.mMyI16) return false
        if (mMyI32 != other.mMyI32) return false
        if (mMyI64 != other.mMyI64) return false
        if (mMyF32 != other.mMyF32) return false
        if (mMyF64 != other.mMyF64) return false
        if (mMyString != other.mMyString) return false
        if (!mMyBinary.contentEquals(other.mMyBinary)) return falseif (mMyDate != other.mMyDate) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mMyBool.hashCode()
        hashCode = hashCode * 31 + mMyI8
        hashCode = hashCode * 31 + mMyI16
        hashCode = hashCode * 31 + mMyI32
        hashCode = hashCode * 31 + mMyI64.hashCode()
        hashCode = hashCode * 31 + mMyF32.hashCode()
        hashCode = hashCode * 31 + mMyF64.hashCode()
        hashCode = hashCode * 31 + mMyString.hashCode()
        hashCode = hashCode * 31 + mMyBinary.contentHashCode()
        hashCode = hashCode * 31 + mMyDate.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestAllPrimitives {" +
                "mMyBool=" + mMyBool +
                "," + "mMyI8=" + mMyI8 +
                "," + "mMyI16=" + mMyI16 +
                "," + "mMyI32=" + mMyI32 +
                "," + "mMyI64=" + mMyI64 +
                "," + "mMyF32=" + mMyF32 +
                "," + "mMyF64=" + mMyF64 +
                "," + "mMyString=" + mMyString +
                "," + "mMyBinary=" + mMyBinary +
                "," + "mMyDate=" + mMyDate +
        "}"
    }

}
