// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

import java.util.ArrayList

/**
 * ============================================================
 * Test: Optional fields
 * Verifies: T? type, = nil default in init
 * ============================================================
 */
data class SwiftTestOptionals(
    val mRequiredField: String,
    val mOptionalString: String?,
    val mOptionalInt: Int?,
    val mOptionalEnum: SwiftTestColor?,
    val mOptionalRecord: SwiftTestAllPrimitives?,
    val mOptionalList: ArrayList<String>?
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestOptionals

        if (mRequiredField != other.mRequiredField) return false
        if (mOptionalString != other.mOptionalString) return false
        if (mOptionalInt != other.mOptionalInt) return false
        if (mOptionalEnum != other.mOptionalEnum) return false
        if (mOptionalRecord != other.mOptionalRecord) return false
        if (mOptionalList != other.mOptionalList) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mRequiredField.hashCode()
        hashCode = hashCode * 31 + (mOptionalString?.hashCode() ?: 0)
        hashCode = hashCode * 31 + (mOptionalInt?.hashCode() ?: 0)
        hashCode = hashCode * 31 + (mOptionalEnum?.hashCode() ?: 0)
        hashCode = hashCode * 31 + (mOptionalRecord?.hashCode() ?: 0)
        hashCode = hashCode * 31 + (mOptionalList?.hashCode() ?: 0)
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestOptionals {" +
                "mRequiredField=" + mRequiredField +
                "," + "mOptionalString=" + mOptionalString +
                "," + "mOptionalInt=" + mOptionalInt +
                "," + "mOptionalEnum=" + mOptionalEnum +
                "," + "mOptionalRecord=" + mOptionalRecord +
                "," + "mOptionalList=" + mOptionalList +
        "}"
    }

}
