// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

/**
 * ============================================================
 * Test: Record with doc comments
 * Verifies: doc comments are preserved in Swift output
 * ============================================================
 * A documented record for testing
 * This has multi-line documentation
 */
data class SwiftTestDocumented(
    val mText: String,
    val mVisible: Boolean
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestDocumented

        if (mText != other.mText) return false
        if (mVisible != other.mVisible) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mText.hashCode()
        hashCode = hashCode * 31 + mVisible.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestDocumented {" +
                "mText=" + mText +
                "," + "mVisible=" + mVisible +
        "}"
    }

}
