// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test

/**
 * ============================================================
 * Test: Record with single field
 * Verifies: inline init (not multi-line)
 * ============================================================
 */
data class SwiftTestSingleField(
    val mValue: String
) {

    override fun equals(other: Any?): Boolean  {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SwiftTestSingleField

        if (mValue != other.mValue) return false

        return true
    }

    override fun hashCode(): Int  {
        // Pick an arbitrary non-zero starting value
        var hashCode = 17;
        hashCode = hashCode * 31 + mValue.hashCode()
        return hashCode
    }

    override fun toString(): String  {
        return "SwiftTestSingleField {" +
                "mValue=" + mValue +
        "}"
    }

}
