// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class TestDuration {

    companion object {
        @kotlin.jvm.JvmStatic
        external fun hoursString(dt: java.time.Duration): String

        @kotlin.jvm.JvmStatic
        external fun minutesString(dt: java.time.Duration): String

        @kotlin.jvm.JvmStatic
        external fun secondsString(dt: java.time.Duration): String

        @kotlin.jvm.JvmStatic
        external fun millisString(dt: java.time.Duration): String

        @kotlin.jvm.JvmStatic
        external fun microsString(dt: java.time.Duration): String

        @kotlin.jvm.JvmStatic
        external fun nanosString(dt: java.time.Duration): String

        @kotlin.jvm.JvmStatic
        external fun hours(count: Int): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun minutes(count: Int): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun seconds(count: Int): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun millis(count: Int): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun micros(count: Int): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun nanos(count: Int): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun hoursf(count: Double): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun minutesf(count: Double): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun secondsf(count: Double): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun millisf(count: Double): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun microsf(count: Double): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun nanosf(count: Double): java.time.Duration

        @kotlin.jvm.JvmStatic
        external fun box(count: Long): java.time.Duration?

        @kotlin.jvm.JvmStatic
        external fun unbox(dt: java.time.Duration?): Long
    }

    class CppProxy(private val nativeRef: Long) : TestDuration() {
        private val destroyed = AtomicBoolean(false)

        init {
            if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @kotlin.jvm.JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }
    }
}
