// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class TestOutcome {

    companion object {
        @kotlin.jvm.JvmStatic
        external fun getSuccessOutcome(): com.snapchat.djinni.Outcome<String, Int>

        @kotlin.jvm.JvmStatic
        external fun getErrorOutcome(): com.snapchat.djinni.Outcome<String, Int>

        @kotlin.jvm.JvmStatic
        external fun putSuccessOutcome(x: com.snapchat.djinni.Outcome<String, Int>): String

        @kotlin.jvm.JvmStatic
        external fun putErrorOutcome(x: com.snapchat.djinni.Outcome<String, Int>): Int

        @kotlin.jvm.JvmStatic
        external fun getNestedSuccessOutcome(): NestedOutcome

        @kotlin.jvm.JvmStatic
        external fun getNestedErrorOutcome(): NestedOutcome

        @kotlin.jvm.JvmStatic
        external fun putNestedSuccessOutcome(x: NestedOutcome): Int

        @kotlin.jvm.JvmStatic
        external fun putNestedErrorOutcome(x: NestedOutcome): String
    }

    class CppProxy(private val nativeRef: Long) : TestOutcome() {
        private val destroyed = AtomicBoolean(false)

        init {
            if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @kotlin.jvm.JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }
    }
}
