// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class WcharTestHelpers {

    companion object {
        @kotlin.jvm.JvmStatic
        external fun getRecord(): WcharTestRec

        @kotlin.jvm.JvmStatic
        external fun getString(): String

        @kotlin.jvm.JvmStatic
        external fun checkString(str: String): Boolean

        @kotlin.jvm.JvmStatic
        external fun checkRecord(rec: WcharTestRec): Boolean
    }

    class CppProxy(private val nativeRef: Long) : WcharTestHelpers() {
        private val destroyed = AtomicBoolean(false)

        init {
            if (nativeRef == 0L) throw RuntimeException("nativeRef is zero")
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @kotlin.jvm.JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }
    }
}
