// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from djinni_perf_benchmark.djinni

#import "TXSRecordSixInt.h"
#import "DjinniUtils.h"


@implementation TXSRecordSixInt

- (nonnull instancetype)initWithI1:(int64_t)i1
                                i2:(int64_t)i2
                                i3:(int64_t)i3
                                i4:(int64_t)i4
                                i5:(int64_t)i5
                                i6:(int64_t)i6
{
    if (self = [super init]) {
        _i1 = i1;
        _i2 = i2;
        _i3 = i3;
        _i4 = i4;
        _i5 = i5;
        _i6 = i6;
    }
    return self;
}

+ (nonnull instancetype)RecordSixIntWithI1:(int64_t)i1
                                        i2:(int64_t)i2
                                        i3:(int64_t)i3
                                        i4:(int64_t)i4
                                        i5:(int64_t)i5
                                        i6:(int64_t)i6
{
    return [[self alloc] initWithI1:i1
                                 i2:i2
                                 i3:i3
                                 i4:i4
                                 i5:i5
                                 i6:i6];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[TXSRecordSixInt class]]) {
        return NO;
    }
    TXSRecordSixInt *typedOther = (TXSRecordSixInt *)other;
    return self.i1 == typedOther.i1 &&
            self.i2 == typedOther.i2 &&
            self.i3 == typedOther.i3 &&
            self.i4 == typedOther.i4 &&
            self.i5 == typedOther.i5 &&
            self.i6 == typedOther.i6;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.i1;
    hashCode = hashCode * 31 + (NSUInteger)self.i2;
    hashCode = hashCode * 31 + (NSUInteger)self.i3;
    hashCode = hashCode * 31 + (NSUInteger)self.i4;
    hashCode = hashCode * 31 + (NSUInteger)self.i5;
    hashCode = hashCode * 31 + (NSUInteger)self.i6;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p i1:%@ i2:%@ i3:%@ i4:%@ i5:%@ i6:%@>", self.class, (void *)self, @(self.i1), @(self.i2), @(self.i3), @(self.i4), @(self.i5), @(self.i6)];
}

#endif
@end
