// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Record containing enum constant */
public class ConstantWithEnum {

    @Nonnull
    public static final ConstantEnum CONST_ENUM = ConstantEnum.SomeValue;


    public ConstantWithEnum(
            ) {
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof ConstantWithEnum)) {
            return false;
        }
        ConstantWithEnum other = (ConstantWithEnum) obj;
        return ;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        return hashCode;
    }

    @Override
    public String toString() {
        return "ConstantWithEnum{" +
        "}";
    }

}
