// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/** Extended record */
public class ExtendedRecord {

    @Nonnull
    public static final ExtendedRecord EXTENDED_RECORD_CONST = new ExtendedRecord(
        true /* mFoo */ );


    /*package*/ final boolean mFoo;

    public ExtendedRecord(
            boolean foo) {
        this.mFoo = foo;
    }

    public boolean getFoo() {
        return mFoo;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof ExtendedRecord)) {
            return false;
        }
        ExtendedRecord other = (ExtendedRecord) obj;
        return this.mFoo == other.mFoo;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + (mFoo ? 1 : 0);
        return hashCode;
    }

    @Override
    public String toString() {
        return "ExtendedRecord{" +
                "mFoo=" + mFoo +
        "}";
    }

}
