// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashMap;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class MapListRecord {


    /*package*/ final ArrayList<HashMap<String, Long>> mMapList;

    public MapListRecord(
            @Nonnull ArrayList<HashMap<String, Long>> mapList) {
        this.mMapList = mapList;
    }

    @Nonnull
    public ArrayList<HashMap<String, Long>> getMapList() {
        return mMapList;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof MapListRecord)) {
            return false;
        }
        MapListRecord other = (MapListRecord) obj;
        return this.mMapList.equals(other.mMapList);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mMapList.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "MapListRecord{" +
                "mMapList=" + mMapList +
        "}";
    }

}
