// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

package com.dropbox.djinni.test;

import java.util.HashMap;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class MapRecord {


    /*package*/ final HashMap<String, Long> mMap;

    /*package*/ final HashMap<Integer, Integer> mImap;

    public MapRecord(
            @Nonnull HashMap<String, Long> map,
            @Nonnull HashMap<Integer, Integer> imap) {
        this.mMap = map;
        this.mImap = imap;
    }

    @Nonnull
    public HashMap<String, Long> getMap() {
        return mMap;
    }

    @Nonnull
    public HashMap<Integer, Integer> getImap() {
        return mImap;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof MapRecord)) {
            return false;
        }
        MapRecord other = (MapRecord) obj;
        return this.mMap.equals(other.mMap) &&
                this.mImap.equals(other.mImap);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mMap.hashCode();
        hashCode = hashCode * 31 + mImap.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "MapRecord{" +
                "mMap=" + mMap +
                "," + "mImap=" + mImap +
        "}";
    }

}
