// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class RecordUsingExtendedRecord {

    @Nonnull
    public static final RecordUsingExtendedRecord CR = new RecordUsingExtendedRecord(
        new ExtendedRecord(
            false /* mFoo */ ) /* mEr */ );


    /*package*/ final ExtendedRecord mEr;

    public RecordUsingExtendedRecord(
            @Nonnull ExtendedRecord er) {
        this.mEr = er;
    }

    @Nonnull
    public ExtendedRecord getEr() {
        return mEr;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof RecordUsingExtendedRecord)) {
            return false;
        }
        RecordUsingExtendedRecord other = (RecordUsingExtendedRecord) obj;
        return this.mEr.equals(other.mEr);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mEr.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "RecordUsingExtendedRecord{" +
                "mEr=" + mEr +
        "}";
    }

}
