// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

package com.dropbox.djinni.test;

import djinni.test.Test.Person;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class RecordWithEmbeddedProto {


    /*package*/ final Person mPerson;

    public RecordWithEmbeddedProto(
            @Nonnull Person person) {
        this.mPerson = person;
    }

    @Nonnull
    public Person getPerson() {
        return mPerson;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof RecordWithEmbeddedProto)) {
            return false;
        }
        RecordWithEmbeddedProto other = (RecordWithEmbeddedProto) obj;
        return ;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + ();
        return hashCode;
    }

    @Override
    public String toString() {
        return "RecordWithEmbeddedProto{" +
                "mPerson=" + mPerson +
        "}";
    }

}
