// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

package com.dropbox.djinni.test;

import java.util.EnumSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class RecordWithFlags {


    /*package*/ final EnumSet<AccessFlags> mAccess;

    public RecordWithFlags(
            @Nonnull EnumSet<AccessFlags> access) {
        this.mAccess = access;
    }

    @Nonnull
    public EnumSet<AccessFlags> getAccess() {
        return mAccess;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof RecordWithFlags)) {
            return false;
        }
        RecordWithFlags other = (RecordWithFlags) obj;
        return this.mAccess == other.mAccess;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mAccess.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "RecordWithFlags{" +
                "mAccess=" + mAccess +
        "}";
    }

}
