// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class SupportCopying {


    /*package*/ final int mX;

    public SupportCopying(
            int x) {
        this.mX = x;
    }

    public int getX() {
        return mX;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof SupportCopying)) {
            return false;
        }
        SupportCopying other = (SupportCopying) obj;
        return this.mX == other.mX;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mX;
        return hashCode;
    }

    @Override
    public String toString() {
        return "SupportCopying{" +
                "mX=" + mX +
        "}";
    }

}
