// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

public final class SwiftTestLabel extends SwiftTestBaseLabel {


    /*package*/ final String mText;

    /*package*/ final boolean mIsBold;

    public SwiftTestLabel(
            int textColor,
            float fontSize,
            String text,
            boolean isBold) {
        super(textColor,fontSize);
        this.mText = text;
        super(textColor,fontSize);
        this.mIsBold = isBold;
    }

    public int getTextColor() {
        return mTextColor;
    }

    public float getFontSize() {
        return mFontSize;
    }

    public String getText() {
        return mText;
    }

    public boolean getIsBold() {
        return mIsBold;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestLabel)) {
            return false;
        }
        SwiftTestLabel other = (SwiftTestLabel) obj;
        return this.mText.equals(other.mText) &&
                this.mIsBold == other.mIsBold;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mTextColor;
        hashCode = hashCode * 31 + Float.floatToIntBits(mFontSize);
        hashCode = hashCode * 31 + mText.hashCode();
        hashCode = hashCode * 31 + (mIsBold ? 1 : 0);
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestLabel{" +
                "mTextColor=" + mTextColor +
                "," + "mFontSize=" + mFontSize +
                "," + "mText=" + mText +
                "," + "mIsBold=" + mIsBold +
        "}";
    }

}
