// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

/**
 * ============================================================
 * Test: Nested records
 * Verifies: correct type references between generated types
 * ============================================================
 */
public final class SwiftTestNested {


    /*package*/ final SwiftTestLabel mLabel;

    /*package*/ final SwiftTestColor mColor;

    /*package*/ final SwiftTestTextStyle mStyle;

    public SwiftTestNested(
            SwiftTestLabel label,
            SwiftTestColor color,
            SwiftTestTextStyle style) {
        this.mLabel = label;
        this.mColor = color;
        this.mStyle = style;
    }

    public SwiftTestLabel getLabel() {
        return mLabel;
    }

    public SwiftTestColor getColor() {
        return mColor;
    }

    public SwiftTestTextStyle getStyle() {
        return mStyle;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestNested)) {
            return false;
        }
        SwiftTestNested other = (SwiftTestNested) obj;
        return this.mLabel.equals(other.mLabel) &&
                this.mColor == other.mColor &&
                this.mStyle.equals(other.mStyle);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mLabel.hashCode();
        hashCode = hashCode * 31 + mColor.hashCode();
        hashCode = hashCode * 31 + mStyle.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestNested{" +
                "mLabel=" + mLabel +
                "," + "mColor=" + mColor +
                "," + "mStyle=" + mStyle +
        "}";
    }

}
