// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

/**
 * ============================================================
 * Test: Empty record (only constants, no fields)
 * Verifies: struct with no fields, no init
 * ============================================================
 */
public final class SwiftTestEmpty {

    public static final int SOME_CONST = 42;


    public SwiftTestEmpty(
            ) {
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestEmpty)) {
            return false;
        }
        SwiftTestEmpty other = (SwiftTestEmpty) obj;
        return ;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestEmpty{" +
        "}";
    }

}
