// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

/**
 * ============================================================
 * Test: Record with single field
 * Verifies: inline init (not multi-line)
 * ============================================================
 */
public final class SwiftTestSingleField {


    /*package*/ final String mValue;

    public SwiftTestSingleField(
            String value) {
        this.mValue = value;
    }

    public String getValue() {
        return mValue;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestSingleField)) {
            return false;
        }
        SwiftTestSingleField other = (SwiftTestSingleField) obj;
        return this.mValue.equals(other.mValue);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mValue.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestSingleField{" +
                "mValue=" + mValue +
        "}";
    }

}
