// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

/** Extern type in optional field (skip should still apply) */
public final class SwiftTestExternOptional {


    /*package*/ final String mName;

    /*package*/ final android.graphics.Color mOptColor;

    /*package*/ final com.example.UserAction mOptAction;

    public SwiftTestExternOptional(
            String name,
            android.graphics.Color optColor,
            com.example.UserAction optAction) {
        this.mName = name;
        this.mOptColor = optColor;
        this.mOptAction = optAction;
    }

    public String getName() {
        return mName;
    }

    public android.graphics.Color getOptColor() {
        return mOptColor;
    }

    public com.example.UserAction getOptAction() {
        return mOptAction;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestExternOptional)) {
            return false;
        }
        SwiftTestExternOptional other = (SwiftTestExternOptional) obj;
        return this.mName.equals(other.mName) &&
                ((this.mOptColor == null && other.mOptColor == null) || (this.mOptColor != null && this.mOptColor.equals(other.mOptColor))) &&
                ((this.mOptAction == null && other.mOptAction == null) || (this.mOptAction != null && this.mOptAction.equals(other.mOptAction)));
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mName.hashCode();
        hashCode = hashCode * 31 + (mOptColor == null ? 0 : mOptColor.hashCode());
        hashCode = hashCode * 31 + (mOptAction == null ? 0 : mOptAction.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestExternOptional{" +
                "mName=" + mName +
                "," + "mOptColor=" + mOptColor +
                "," + "mOptAction=" + mOptAction +
        "}";
    }

}
