// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;

/**
 * ============================================================
 * Test: Optional fields
 * Verifies: T? type, = nil default in init
 * ============================================================
 */
public final class SwiftTestOptionals {


    /*package*/ final String mRequiredField;

    /*package*/ final String mOptionalString;

    /*package*/ final Integer mOptionalInt;

    /*package*/ final SwiftTestColor mOptionalEnum;

    /*package*/ final SwiftTestAllPrimitives mOptionalRecord;

    /*package*/ final ArrayList<String> mOptionalList;

    public SwiftTestOptionals(
            String requiredField,
            String optionalString,
            Integer optionalInt,
            SwiftTestColor optionalEnum,
            SwiftTestAllPrimitives optionalRecord,
            ArrayList<String> optionalList) {
        this.mRequiredField = requiredField;
        this.mOptionalString = optionalString;
        this.mOptionalInt = optionalInt;
        this.mOptionalEnum = optionalEnum;
        this.mOptionalRecord = optionalRecord;
        this.mOptionalList = optionalList;
    }

    public String getRequiredField() {
        return mRequiredField;
    }

    public String getOptionalString() {
        return mOptionalString;
    }

    public Integer getOptionalInt() {
        return mOptionalInt;
    }

    public SwiftTestColor getOptionalEnum() {
        return mOptionalEnum;
    }

    public SwiftTestAllPrimitives getOptionalRecord() {
        return mOptionalRecord;
    }

    public ArrayList<String> getOptionalList() {
        return mOptionalList;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestOptionals)) {
            return false;
        }
        SwiftTestOptionals other = (SwiftTestOptionals) obj;
        return this.mRequiredField.equals(other.mRequiredField) &&
                ((this.mOptionalString == null && other.mOptionalString == null) || (this.mOptionalString != null && this.mOptionalString.equals(other.mOptionalString))) &&
                ((this.mOptionalInt == null && other.mOptionalInt == null) || (this.mOptionalInt != null && this.mOptionalInt.equals(other.mOptionalInt))) &&
                ((this.mOptionalEnum == null && other.mOptionalEnum == null) || (this.mOptionalEnum != null && this.mOptionalEnum.equals(other.mOptionalEnum))) &&
                ((this.mOptionalRecord == null && other.mOptionalRecord == null) || (this.mOptionalRecord != null && this.mOptionalRecord.equals(other.mOptionalRecord))) &&
                ((this.mOptionalList == null && other.mOptionalList == null) || (this.mOptionalList != null && this.mOptionalList.equals(other.mOptionalList)));
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mRequiredField.hashCode();
        hashCode = hashCode * 31 + (mOptionalString == null ? 0 : mOptionalString.hashCode());
        hashCode = hashCode * 31 + (mOptionalInt == null ? 0 : mOptionalInt.hashCode());
        hashCode = hashCode * 31 + (mOptionalEnum == null ? 0 : mOptionalEnum.hashCode());
        hashCode = hashCode * 31 + (mOptionalRecord == null ? 0 : mOptionalRecord.hashCode());
        hashCode = hashCode * 31 + (mOptionalList == null ? 0 : mOptionalList.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestOptionals{" +
                "mRequiredField=" + mRequiredField +
                "," + "mOptionalString=" + mOptionalString +
                "," + "mOptionalInt=" + mOptionalInt +
                "," + "mOptionalEnum=" + mOptionalEnum +
                "," + "mOptionalRecord=" + mOptionalRecord +
                "," + "mOptionalList=" + mOptionalList +
        "}";
    }

}
