// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

/**
 * ============================================================
 * Test: Record with doc comments
 * Verifies: doc comments are preserved in Swift output
 * ============================================================
 * A documented record for testing
 * This has multi-line documentation
 */
public final class SwiftTestDocumented {


    /*package*/ final String mText;

    /*package*/ final boolean mVisible;

    public SwiftTestDocumented(
            String text,
            boolean visible) {
        this.mText = text;
        this.mVisible = visible;
    }

    /** The main label text */
    public String getText() {
        return mText;
    }

    /** Whether the label is visible */
    public boolean getVisible() {
        return mVisible;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestDocumented)) {
            return false;
        }
        SwiftTestDocumented other = (SwiftTestDocumented) obj;
        return this.mText.equals(other.mText) &&
                this.mVisible == other.mVisible;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mText.hashCode();
        hashCode = hashCode * 31 + (mVisible ? 1 : 0);
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestDocumented{" +
                "mText=" + mText +
                "," + "mVisible=" + mVisible +
        "}";
    }

}
