// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

/**
 * ============================================================
 * Test: Collection types
 * Verifies: list -> [T], set -> Set<T>, map -> [K: V]
 * ============================================================
 */
public final class SwiftTestCollections {


    /*package*/ final ArrayList<String> mStringList;

    /*package*/ final HashSet<Integer> mIntSet;

    /*package*/ final HashMap<String, Long> mStringToIntMap;

    /*package*/ final ArrayList<ArrayList<String>> mNestedList;

    /*package*/ final ArrayList<SwiftTestColor> mEnumList;

    /*package*/ final HashMap<SwiftTestColor, String> mEnumMap;

    public SwiftTestCollections(
            ArrayList<String> stringList,
            HashSet<Integer> intSet,
            HashMap<String, Long> stringToIntMap,
            ArrayList<ArrayList<String>> nestedList,
            ArrayList<SwiftTestColor> enumList,
            HashMap<SwiftTestColor, String> enumMap) {
        this.mStringList = stringList;
        this.mIntSet = intSet;
        this.mStringToIntMap = stringToIntMap;
        this.mNestedList = nestedList;
        this.mEnumList = enumList;
        this.mEnumMap = enumMap;
    }

    public ArrayList<String> getStringList() {
        return mStringList;
    }

    public HashSet<Integer> getIntSet() {
        return mIntSet;
    }

    public HashMap<String, Long> getStringToIntMap() {
        return mStringToIntMap;
    }

    public ArrayList<ArrayList<String>> getNestedList() {
        return mNestedList;
    }

    public ArrayList<SwiftTestColor> getEnumList() {
        return mEnumList;
    }

    public HashMap<SwiftTestColor, String> getEnumMap() {
        return mEnumMap;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestCollections)) {
            return false;
        }
        SwiftTestCollections other = (SwiftTestCollections) obj;
        return this.mStringList.equals(other.mStringList) &&
                this.mIntSet.equals(other.mIntSet) &&
                this.mStringToIntMap.equals(other.mStringToIntMap) &&
                this.mNestedList.equals(other.mNestedList) &&
                this.mEnumList.equals(other.mEnumList) &&
                this.mEnumMap.equals(other.mEnumMap);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mStringList.hashCode();
        hashCode = hashCode * 31 + mIntSet.hashCode();
        hashCode = hashCode * 31 + mStringToIntMap.hashCode();
        hashCode = hashCode * 31 + mNestedList.hashCode();
        hashCode = hashCode * 31 + mEnumList.hashCode();
        hashCode = hashCode * 31 + mEnumMap.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestCollections{" +
                "mStringList=" + mStringList +
                "," + "mIntSet=" + mIntSet +
                "," + "mStringToIntMap=" + mStringToIntMap +
                "," + "mNestedList=" + mNestedList +
                "," + "mEnumList=" + mEnumList +
                "," + "mEnumMap=" + mEnumMap +
        "}";
    }

}
