// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

package com.dropbox.djinni.test;

/**
 * ============================================================
 * Test: Record inheritance (extends) — must be flattened
 * Verifies: super fields appear first, all in one struct
 * ============================================================
 */
public final class SwiftTestBaseLabel {


    /*package*/ final int mTextColor;

    /*package*/ final float mFontSize;

    public SwiftTestBaseLabel(
            int textColor,
            float fontSize) {
        this.mTextColor = textColor;
        this.mFontSize = fontSize;
    }

    public int getTextColor() {
        return mTextColor;
    }

    public float getFontSize() {
        return mFontSize;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof SwiftTestBaseLabel)) {
            return false;
        }
        SwiftTestBaseLabel other = (SwiftTestBaseLabel) obj;
        return this.mTextColor == other.mTextColor &&
                this.mFontSize == other.mFontSize;
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mTextColor;
        hashCode = hashCode * 31 + Float.floatToIntBits(mFontSize);
        return hashCode;
    }

    @Override
    public String toString() {
        return "SwiftTestBaseLabel{" +
                "mTextColor=" + mTextColor +
                "," + "mFontSize=" + mFontSize +
        "}";
    }

}
