// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public enum TestIdentEnumNative {
    SnakeEnum,
    /** Should become CapsEnum in objective-c, but stay the same in Java/C++ */
    CAPSENUM,
    ;
}
