// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

package com.dropbox.djinni.test;

public final class TestOptionalExternInterfaceRecord {


    /*package*/ final com.dropbox.djinni.test.SampleInterface mSampleInterface;

    public TestOptionalExternInterfaceRecord(
            com.dropbox.djinni.test.SampleInterface sampleInterface) {
        this.mSampleInterface = sampleInterface;
    }

    public com.dropbox.djinni.test.SampleInterface getSampleInterface() {
        return mSampleInterface;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof TestOptionalExternInterfaceRecord)) {
            return false;
        }
        TestOptionalExternInterfaceRecord other = (TestOptionalExternInterfaceRecord) obj;
        return ((this.mSampleInterface == null && other.mSampleInterface == null) || (this.mSampleInterface != null && this.mSampleInterface.equals(other.mSampleInterface)));
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + (mSampleInterface == null ? 0 : mSampleInterface.hashCode());
        return hashCode;
    }

    @Override
    public String toString() {
        return "TestOptionalExternInterfaceRecord{" +
                "mSampleInterface=" + mSampleInterface +
        "}";
    }

}
