// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

package com.dropbox.djinni.test;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public class WcharTestRec {


    /*package*/ final String mS;

    public WcharTestRec(
            @Nonnull String s) {
        this.mS = s;
    }

    @Nonnull
    public String getS() {
        return mS;
    }

    @Override
    public boolean equals(@CheckForNull Object obj) {
        if (!(obj instanceof WcharTestRec)) {
            return false;
        }
        WcharTestRec other = (WcharTestRec) obj;
        return this.mS.equals(other.mS);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + mS.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "WcharTestRec{" +
                "mS=" + mS +
        "}";
    }

}
