// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from djinni_perf_benchmark.djinni

#include "RecordSixInt.hpp"  // my header
#include "BuildConstants.h"

namespace snapchat::djinni::benchmark {


bool operator==(const RecordSixInt& lhs, const RecordSixInt& rhs) {
    return lhs.i1 == rhs.i1 &&
           lhs.i2 == rhs.i2 &&
           lhs.i3 == rhs.i3 &&
           lhs.i4 == rhs.i4 &&
           lhs.i5 == rhs.i5 &&
           lhs.i6 == rhs.i6;
}

bool operator!=(const RecordSixInt& lhs, const RecordSixInt& rhs) {
    return !(lhs == rhs);
}

std::string RecordSixInt::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "RecordSixInt {";

        ss << "\n" << childIndentation;
        ss << "i1=" << i1;

        ss << "\n" << childIndentation;
        ss << "i2=" << i2;

        ss << "\n" << childIndentation;
        ss << "i3=" << i3;

        ss << "\n" << childIndentation;
        ss << "i4=" << i4;

        ss << "\n" << childIndentation;
        ss << "i5=" << i5;

        ss << "\n" << childIndentation;
        ss << "i6=" << i6;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace snapchat::djinni::benchmark
