// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#include "_varname_record_.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const VarnameRecord& lhs, const VarnameRecord& rhs) {
    return lhs._field_ == rhs._field_;
}

bool operator!=(const VarnameRecord& lhs, const VarnameRecord& rhs) {
    return !(lhs == rhs);
}

std::string VarnameRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "VarnameRecord {";

        ss << "\n" << childIndentation;
        ss << "_field_=" << _field_;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
