// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#include "_varname_record_.hpp"  // my header

namespace testsuite {


bool operator==(const VarnameRecord& lhs, const VarnameRecord& rhs) {
    return lhs._field_ == rhs._field_;
}

bool operator!=(const VarnameRecord& lhs, const VarnameRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
