// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

#include "client_returned_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const ClientReturnedRecord& lhs, const ClientReturnedRecord& rhs) {
    return lhs.record_id == rhs.record_id &&
           lhs.content == rhs.content &&
           lhs.misc == rhs.misc;
}

bool operator!=(const ClientReturnedRecord& lhs, const ClientReturnedRecord& rhs) {
    return !(lhs == rhs);
}

std::string ClientReturnedRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "ClientReturnedRecord {";

        ss << "\n" << childIndentation;
        ss << "record_id=" << record_id;

        ss << "\n" << childIndentation;
        ss << "content=" << content;

        ss << "\n" << childIndentation;
        if (misc) {
            ss << "misc=" << *misc;
        }
        else {
            ss << "misc=<none>";
        }

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
