// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#pragma once

#include "constant_enum.hpp"
#include <utility>

namespace testsuite {

/** Record containing enum constant */
struct ConstantWithEnum final {

    static constant_enum const CONST_ENUM;

    friend bool operator==(const ConstantWithEnum& lhs, const ConstantWithEnum& rhs);
    friend bool operator!=(const ConstantWithEnum& lhs, const ConstantWithEnum& rhs);
};

} // namespace testsuite
