// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#include "constant_with_enum.hpp"  // my header

namespace testsuite {

constant_enum const ConstantWithEnum::CONST_ENUM = constant_enum::SOME_VALUE;

bool operator==(const ConstantWithEnum& lhs, const ConstantWithEnum& rhs) {
    return true;
}

bool operator!=(const ConstantWithEnum& lhs, const ConstantWithEnum& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
