// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

#pragma once

#include <cstdint>
#include <sstream>
#include <string>
#include <utility>

namespace testsuite {

/** Record for use in constants */
struct ConstantRecord final {
    int32_t some_integer;
    std::string some_string;

    friend bool operator==(const ConstantRecord& lhs, const ConstantRecord& rhs);
    friend bool operator!=(const ConstantRecord& lhs, const ConstantRecord& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    ConstantRecord(int32_t some_integer_,
                   std::string some_string_)
    : some_integer(std::move(some_integer_))
    , some_string(std::move(some_string_))
    {}
};

} // namespace testsuite
