// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constants.djinni

#include "constant_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const ConstantRecord& lhs, const ConstantRecord& rhs) {
    return lhs.some_integer == rhs.some_integer &&
           lhs.some_string == rhs.some_string;
}

bool operator!=(const ConstantRecord& lhs, const ConstantRecord& rhs) {
    return !(lhs == rhs);
}

std::string ConstantRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "ConstantRecord {";

        ss << "\n" << childIndentation;
        ss << "some_integer=" << some_integer;

        ss << "\n" << childIndentation;
        ss << "some_string=" << some_string;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
