// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#include "date_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const DateRecord& lhs, const DateRecord& rhs) {
    return lhs.created_at == rhs.created_at;
}

bool operator!=(const DateRecord& lhs, const DateRecord& rhs) {
    return !(lhs == rhs);
}

std::string DateRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "DateRecord {";

        ss << "\n" << childIndentation;
        ss << "created_at=" << created_at.getTestRepresentation(childIndentation);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

bool operator<(const DateRecord& lhs, const DateRecord& rhs) {
    if (lhs.created_at < rhs.created_at) {
        return true;
    }
    if (rhs.created_at < lhs.created_at) {
        return false;
    }
    return false;
}

bool operator>(const DateRecord& lhs, const DateRecord& rhs) {
    return rhs < lhs;
}

bool operator<=(const DateRecord& lhs, const DateRecord& rhs) {
    return !(rhs < lhs);
}

bool operator>=(const DateRecord& lhs, const DateRecord& rhs) {
    return !(lhs < rhs);
}

} // namespace testsuite
