// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from test.djinni

#include "empty_record.hpp"  // my header

namespace testsuite {


bool operator==(const EmptyRecord& lhs, const EmptyRecord& rhs) {
    return true;
}

bool operator!=(const EmptyRecord& lhs, const EmptyRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
