// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

#pragma once

#include <sstream>
#include <utility>

namespace testsuite {

struct ExtendedRecord; // Requiring extended class

/** Extended record */
struct ExtendedRecordBase {

    static ExtendedRecord const EXTENDED_RECORD_CONST;
    bool foo;

    friend bool operator==(const ExtendedRecordBase& lhs, const ExtendedRecordBase& rhs);
    friend bool operator!=(const ExtendedRecordBase& lhs, const ExtendedRecordBase& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    ExtendedRecordBase(bool foo_)
    : foo(std::move(foo_))
    {}

    virtual ~ExtendedRecordBase() = default;

protected:
    ExtendedRecordBase(const ExtendedRecordBase&) = default;
    ExtendedRecordBase(ExtendedRecordBase&&) = default;
    ExtendedRecordBase& operator=(const ExtendedRecordBase&) = default;
    ExtendedRecordBase& operator=(ExtendedRecordBase&&) = default;
};

} // namespace testsuite
