// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#include "extern_record_with_derivings.hpp"  // my header
#include "BuildConstants.h"


bool operator==(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs) {
    return lhs.member == rhs.member &&
           lhs.e == rhs.e;
}

bool operator!=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs) {
    return !(lhs == rhs);
}

std::string ExternRecordWithDerivings::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "ExternRecordWithDerivings {";

        ss << "\n" << childIndentation;
        ss << "member=" << member.getTestRepresentation(childIndentation);

        ss << "\n" << childIndentation;
        ss << "e=" << to_string(e);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

bool operator<(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs) {
    if (lhs.member < rhs.member) {
        return true;
    }
    if (rhs.member < lhs.member) {
        return false;
    }
    if (lhs.e < rhs.e) {
        return true;
    }
    if (rhs.e < lhs.e) {
        return false;
    }
    return false;
}

bool operator>(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs) {
    return rhs < lhs;
}

bool operator<=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs) {
    return !(rhs < lhs);
}

bool operator>=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs) {
    return !(lhs < rhs);
}
