// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace testsuite {

struct MapListRecord final {
    std::vector<std::unordered_map<std::string, int64_t>> map_list;

    friend bool operator==(const MapListRecord& lhs, const MapListRecord& rhs);
    friend bool operator!=(const MapListRecord& lhs, const MapListRecord& rhs);

    //NOLINTNEXTLINE(google-explicit-constructor)
    MapListRecord(std::vector<std::unordered_map<std::string, int64_t>> map_list_)
    : map_list(std::move(map_list_))
    {}
};

} // namespace testsuite
