// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#include "map_list_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const MapListRecord& lhs, const MapListRecord& rhs) {
    return lhs.map_list == rhs.map_list;
}

bool operator!=(const MapListRecord& lhs, const MapListRecord& rhs) {
    return !(lhs == rhs);
}

std::string MapListRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "MapListRecord {";

        ss << "\n" << childIndentation;
        ss << "map_list=[";
        for (size_t i = 0; i < map_list.size(); ++i) {
            if (i > 0) { ss << ","; }
            ss << "\n" << childIndentation << "   ";
            ss << map_list[i];
        }
        if (!map_list.empty()) {
            ss << "\n" << childIndentation;
        }
        ss << "]";

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
