// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#include "map_date_record.hpp"  // my header

namespace testsuite {


bool operator==(const MapDateRecord& lhs, const MapDateRecord& rhs) {
    return lhs.dates_by_id == rhs.dates_by_id;
}

bool operator!=(const MapDateRecord& lhs, const MapDateRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
