// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#include "map_list_record.hpp"  // my header

namespace testsuite {


bool operator==(const MapListRecord& lhs, const MapListRecord& rhs) {
    return lhs.map_list == rhs.map_list;
}

bool operator!=(const MapListRecord& lhs, const MapListRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
