// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#include "map_record.hpp"  // my header

namespace testsuite {


bool operator==(const MapRecord& lhs, const MapRecord& rhs) {
    return lhs.map == rhs.map &&
           lhs.imap == rhs.imap;
}

bool operator!=(const MapRecord& lhs, const MapRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
