// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#include "map_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const MapRecord& lhs, const MapRecord& rhs) {
    return lhs.map == rhs.map &&
           lhs.imap == rhs.imap;
}

bool operator!=(const MapRecord& lhs, const MapRecord& rhs) {
    return !(lhs == rhs);
}

std::string MapRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "MapRecord {";

        ss << "\n" << childIndentation;
        ss << "map=" << map;

        ss << "\n" << childIndentation;
        ss << "imap=" << imap;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
