// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

#pragma once

#include "expected.hpp"
#include <cstdint>
#include <sstream>
#include <string>
#include <utility>

namespace testsuite {

struct NestedOutcome final {
    djinni::expected<int32_t, std::string> o;

    friend bool operator==(const NestedOutcome& lhs, const NestedOutcome& rhs);
    friend bool operator!=(const NestedOutcome& lhs, const NestedOutcome& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    NestedOutcome(djinni::expected<int32_t, std::string> o_)
    : o(std::move(o_))
    {}
};

} // namespace testsuite
