// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

#pragma once

#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

namespace testsuite {

struct NestedCollection final {
    std::vector<std::unordered_set<std::string>> set_list;

    friend bool operator==(const NestedCollection& lhs, const NestedCollection& rhs);
    friend bool operator!=(const NestedCollection& lhs, const NestedCollection& rhs);

    //NOLINTNEXTLINE(google-explicit-constructor)
    NestedCollection(std::vector<std::unordered_set<std::string>> set_list_)
    : set_list(std::move(set_list_))
    {}
};

} // namespace testsuite
