// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

#include "nested_collection.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const NestedCollection& lhs, const NestedCollection& rhs) {
    return lhs.set_list == rhs.set_list;
}

bool operator!=(const NestedCollection& lhs, const NestedCollection& rhs) {
    return !(lhs == rhs);
}

std::string NestedCollection::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "NestedCollection {";

        ss << "\n" << childIndentation;
        ss << "set_list=[";
        for (size_t i = 0; i < set_list.size(); ++i) {
            if (i > 0) { ss << ","; }
            ss << "\n" << childIndentation << "   ";
            ss << set_list[i];
        }
        if (!set_list.empty()) {
            ss << "\n" << childIndentation;
        }
        ss << "]";

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
