// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

#include "nested_collection.hpp"  // my header

namespace testsuite {


bool operator==(const NestedCollection& lhs, const NestedCollection& rhs) {
    return lhs.set_list == rhs.set_list;
}

bool operator!=(const NestedCollection& lhs, const NestedCollection& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
