// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from no_constructor.djinni

#include "no_constructor_record_native.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {

std::string const NoConstructorRecord::RECORD_CONST_VALUE = {"test"};

bool operator==(const NoConstructorRecord& lhs, const NoConstructorRecord& rhs) {
    return lhs.FirstValue == rhs.FirstValue &&
           lhs.second_value == rhs.second_value;
}

bool operator!=(const NoConstructorRecord& lhs, const NoConstructorRecord& rhs) {
    return !(lhs == rhs);
}

std::string NoConstructorRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "NoConstructorRecord {";

        ss << "\n" << childIndentation;
        ss << "FirstValue=" << FirstValue;

        ss << "\n" << childIndentation;
        ss << "second_value=" << second_value;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
