// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

#include "primitive_list.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const PrimitiveList& lhs, const PrimitiveList& rhs) {
    return lhs.list == rhs.list;
}

bool operator!=(const PrimitiveList& lhs, const PrimitiveList& rhs) {
    return !(lhs == rhs);
}

std::string PrimitiveList::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "PrimitiveList {";

        ss << "\n" << childIndentation;
        ss << "list=[";
        for (size_t i = 0; i < list.size(); ++i) {
            if (i > 0) { ss << ","; }
            ss << "\n" << childIndentation << "   ";
            ss << list[i];
        }
        if (!list.empty()) {
            ss << "\n" << childIndentation;
        }
        ss << "]";

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
