// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from primitive_list.djinni

#include "primitive_list.hpp"  // my header

namespace testsuite {


bool operator==(const PrimitiveList& lhs, const PrimitiveList& rhs) {
    return lhs.list == rhs.list;
}

bool operator!=(const PrimitiveList& lhs, const PrimitiveList& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
