// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#pragma once

#include "proto/cpp/test2.pb.h"
#include <sstream>
#include <utility>

namespace testsuite {

struct RecordWithEmbeddedCppProto final {
    ::djinni::test2::PersistingState state;

    friend bool operator==(const RecordWithEmbeddedCppProto& lhs, const RecordWithEmbeddedCppProto& rhs);
    friend bool operator!=(const RecordWithEmbeddedCppProto& lhs, const RecordWithEmbeddedCppProto& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RecordWithEmbeddedCppProto(::djinni::test2::PersistingState state_)
    : state(std::move(state_))
    {}
};

} // namespace testsuite
