// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from duration.djinni

#include "record_with_duration_and_derivings.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const RecordWithDurationAndDerivings& lhs, const RecordWithDurationAndDerivings& rhs) {
    return lhs.dt == rhs.dt;
}

bool operator!=(const RecordWithDurationAndDerivings& lhs, const RecordWithDurationAndDerivings& rhs) {
    return !(lhs == rhs);
}

std::string RecordWithDurationAndDerivings::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "RecordWithDurationAndDerivings {";

        ss << "\n" << childIndentation;
        ss << "dt=" << dt.getTestRepresentation(childIndentation);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

bool operator<(const RecordWithDurationAndDerivings& lhs, const RecordWithDurationAndDerivings& rhs) {
    if (lhs.dt < rhs.dt) {
        return true;
    }
    if (rhs.dt < lhs.dt) {
        return false;
    }
    return false;
}

bool operator>(const RecordWithDurationAndDerivings& lhs, const RecordWithDurationAndDerivings& rhs) {
    return rhs < lhs;
}

bool operator<=(const RecordWithDurationAndDerivings& lhs, const RecordWithDurationAndDerivings& rhs) {
    return !(rhs < lhs);
}

bool operator>=(const RecordWithDurationAndDerivings& lhs, const RecordWithDurationAndDerivings& rhs) {
    return !(lhs < rhs);
}

} // namespace testsuite
