// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

#include "record_using_extended_record.hpp"  // my header

namespace testsuite {

RecordUsingExtendedRecord const RecordUsingExtendedRecord::CR = RecordUsingExtendedRecord(
    ExtendedRecord(
        false /* foo */ ) /* er */ );

bool operator==(const RecordUsingExtendedRecord& lhs, const RecordUsingExtendedRecord& rhs) {
    return lhs.er == rhs.er;
}

bool operator!=(const RecordUsingExtendedRecord& lhs, const RecordUsingExtendedRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
