// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#include "RecordWithEmbeddedProto.hpp"  // my header

namespace testsuite {


bool operator==(const RecordWithEmbeddedProto& lhs, const RecordWithEmbeddedProto& rhs) {
    return lhs.person == rhs.person;
}

bool operator!=(const RecordWithEmbeddedProto& lhs, const RecordWithEmbeddedProto& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
