// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#pragma once

#include "proto/cpp/test.pb.h"
#include <sstream>
#include <utility>

namespace testsuite {

struct RecordWithEmbeddedProto final {
    ::djinni::test::Person person;

    friend bool operator==(const RecordWithEmbeddedProto& lhs, const RecordWithEmbeddedProto& rhs);
    friend bool operator!=(const RecordWithEmbeddedProto& lhs, const RecordWithEmbeddedProto& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RecordWithEmbeddedProto(::djinni::test::Person person_)
    : person(std::move(person_))
    {}
};

} // namespace testsuite
