// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#include "record_with_flags.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const RecordWithFlags& lhs, const RecordWithFlags& rhs) {
    return lhs.access == rhs.access;
}

bool operator!=(const RecordWithFlags& lhs, const RecordWithFlags& rhs) {
    return !(lhs == rhs);
}

std::string RecordWithFlags::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "RecordWithFlags {";

        ss << "\n" << childIndentation;
        ss << "access=" << to_string(access);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
