// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

#pragma once

#include "../../handwritten-src/cpp/extended_record.hpp"
#include <sstream>
#include <utility>

namespace testsuite {

struct RecordUsingExtendedRecord final {

    static RecordUsingExtendedRecord const CR;
    ExtendedRecord er;

    friend bool operator==(const RecordUsingExtendedRecord& lhs, const RecordUsingExtendedRecord& rhs);
    friend bool operator!=(const RecordUsingExtendedRecord& lhs, const RecordUsingExtendedRecord& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RecordUsingExtendedRecord(ExtendedRecord er_)
    : er(std::move(er_))
    {}
};

} // namespace testsuite
