// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#include "RecordWithEmbeddedCppProto.hpp"  // my header

namespace testsuite {


bool operator==(const RecordWithEmbeddedCppProto& lhs, const RecordWithEmbeddedCppProto& rhs) {
    return lhs.state == rhs.state;
}

bool operator!=(const RecordWithEmbeddedCppProto& lhs, const RecordWithEmbeddedCppProto& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
