// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#include "RecordWithEmbeddedCppProto.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const RecordWithEmbeddedCppProto& lhs, const RecordWithEmbeddedCppProto& rhs) {
    return lhs.state == rhs.state;
}

bool operator!=(const RecordWithEmbeddedCppProto& lhs, const RecordWithEmbeddedCppProto& rhs) {
    return !(lhs == rhs);
}

std::string RecordWithEmbeddedCppProto::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "RecordWithEmbeddedCppProto {";

        ss << "\n" << childIndentation;
        ss << "state=" << state;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
