// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

#include "record_using_extended_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {

RecordUsingExtendedRecord const RecordUsingExtendedRecord::CR = RecordUsingExtendedRecord(
    ExtendedRecord(
        false /* foo */ ) /* er */ );

bool operator==(const RecordUsingExtendedRecord& lhs, const RecordUsingExtendedRecord& rhs) {
    return lhs.er == rhs.er;
}

bool operator!=(const RecordUsingExtendedRecord& lhs, const RecordUsingExtendedRecord& rhs) {
    return !(lhs == rhs);
}

std::string RecordUsingExtendedRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "RecordUsingExtendedRecord {";

        ss << "\n" << childIndentation;
        ss << "er=" << er.getTestRepresentation(childIndentation);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
