// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#include "record_with_flags.hpp"  // my header

namespace testsuite {


bool operator==(const RecordWithFlags& lhs, const RecordWithFlags& rhs) {
    return lhs.access == rhs.access;
}

bool operator!=(const RecordWithFlags& lhs, const RecordWithFlags& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
