// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#pragma once

#include "access_flags.hpp"
#include <sstream>
#include <utility>

namespace testsuite {

struct RecordWithFlags final {
    access_flags access;

    friend bool operator==(const RecordWithFlags& lhs, const RecordWithFlags& rhs);
    friend bool operator!=(const RecordWithFlags& lhs, const RecordWithFlags& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    RecordWithFlags(access_flags access_)
    : access(std::move(access_))
    {}
};

} // namespace testsuite
