// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#include "set_record.hpp"  // my header

namespace testsuite {


bool operator==(const SetRecord& lhs, const SetRecord& rhs) {
    return lhs.set == rhs.set &&
           lhs.iset == rhs.iset;
}

bool operator!=(const SetRecord& lhs, const SetRecord& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
