// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#include "set_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SetRecord& lhs, const SetRecord& rhs) {
    return lhs.set == rhs.set &&
           lhs.iset == rhs.iset;
}

bool operator!=(const SetRecord& lhs, const SetRecord& rhs) {
    return !(lhs == rhs);
}

std::string SetRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SetRecord {";

        ss << "\n" << childIndentation;
        ss << "set=" << set;

        ss << "\n" << childIndentation;
        ss << "iset=" << iset;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
