// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

#include "support_copying.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SupportCopying& lhs, const SupportCopying& rhs) {
    return lhs.x == rhs.x;
}

bool operator!=(const SupportCopying& lhs, const SupportCopying& rhs) {
    return !(lhs == rhs);
}

std::string SupportCopying::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SupportCopying {";

        ss << "\n" << childIndentation;
        ss << "x=" << x;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
