// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

#pragma once

#include <cstdint>
#include <sstream>
#include <utility>

namespace testsuite {

struct SupportCopying final {
    int32_t x;

    friend bool operator==(const SupportCopying& lhs, const SupportCopying& rhs);
    friend bool operator!=(const SupportCopying& lhs, const SupportCopying& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    SupportCopying(int32_t x_)
    : x(std::move(x_))
    {}
};

} // namespace testsuite
