// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nscopying.djinni

#include "support_copying.hpp"  // my header

namespace testsuite {


bool operator==(const SupportCopying& lhs, const SupportCopying& rhs) {
    return lhs.x == rhs.x;
}

bool operator!=(const SupportCopying& lhs, const SupportCopying& rhs) {
    return !(lhs == rhs);
}

} // namespace testsuite
