// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include <sstream>
#include <string>
#include <utility>

namespace testsuite {

/**
 * ============================================================
 * Test: Record with single field
 * Verifies: inline init (not multi-line)
 * ============================================================
 */
struct SwiftTestSingleField final {
    std::string value;

    friend bool operator==(const SwiftTestSingleField& lhs, const SwiftTestSingleField& rhs);
    friend bool operator!=(const SwiftTestSingleField& lhs, const SwiftTestSingleField& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    //NOLINTNEXTLINE(google-explicit-constructor)
    SwiftTestSingleField(std::string value_)
    : value(std::move(value_))
    {}
};

} // namespace testsuite
