// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_text_style.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestTextStyle& lhs, const SwiftTestTextStyle& rhs) {
    return lhs.color == rhs.color &&
           lhs.letter_case == rhs.letter_case;
}

bool operator!=(const SwiftTestTextStyle& lhs, const SwiftTestTextStyle& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestTextStyle::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestTextStyle {";

        ss << "\n" << childIndentation;
        ss << "color=" << color;

        ss << "\n" << childIndentation;
        ss << "letter_case=" << to_string(letter_case);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
