// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include <cstdint>
#include <sstream>
#include <utility>

namespace testsuite {

/**
 * ============================================================
 * Test: Empty record (only constants, no fields)
 * Verifies: struct with no fields, no init
 * ============================================================
 */
struct SwiftTestEmpty final {

    static constexpr int32_t SOME_CONST = 42;

    friend bool operator==(const SwiftTestEmpty& lhs, const SwiftTestEmpty& rhs);
    friend bool operator!=(const SwiftTestEmpty& lhs, const SwiftTestEmpty& rhs);
};

} // namespace testsuite
