// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "swift_test_letter_case.hpp"
#include <cstdint>
#include <sstream>
#include <utility>

namespace testsuite {

struct SwiftTestTextStyle final {
    int32_t color;
    SwiftTestLetterCase letter_case;

    friend bool operator==(const SwiftTestTextStyle& lhs, const SwiftTestTextStyle& rhs);
    friend bool operator!=(const SwiftTestTextStyle& lhs, const SwiftTestTextStyle& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    SwiftTestTextStyle(int32_t color_,
                       SwiftTestLetterCase letter_case_)
    : color(std::move(color_))
    , letter_case(std::move(letter_case_))
    {}
};

} // namespace testsuite
