// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include <sstream>
#include <string>
#include <utility>

namespace testsuite {

/**
 * ============================================================
 * Test: Record with doc comments
 * Verifies: doc comments are preserved in Swift output
 * ============================================================
 * A documented record for testing
 * This has multi-line documentation
 */
struct SwiftTestDocumented final {
    /** The main label text */
    std::string text;
    /** Whether the label is visible */
    bool visible;

    friend bool operator==(const SwiftTestDocumented& lhs, const SwiftTestDocumented& rhs);
    friend bool operator!=(const SwiftTestDocumented& lhs, const SwiftTestDocumented& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    SwiftTestDocumented(std::string text_,
                        bool visible_)
    : text(std::move(text_))
    , visible(std::move(visible_))
    {}
};

} // namespace testsuite
