// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "swift_test_all_primitives.hpp"
#include "swift_test_color.hpp"
#include <cstdint>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace testsuite {

/**
 * ============================================================
 * Test: Optional fields
 * Verifies: T? type, = nil default in init
 * ============================================================
 */
struct SwiftTestOptionals final {
    std::string required_field;
    std::optional<std::string> optional_string;
    std::optional<int32_t> optional_int;
    std::optional<SwiftTestColor> optional_enum;
    std::optional<SwiftTestAllPrimitives> optional_record;
    std::optional<std::vector<std::string>> optional_list;

    friend bool operator==(const SwiftTestOptionals& lhs, const SwiftTestOptionals& rhs);
    friend bool operator!=(const SwiftTestOptionals& lhs, const SwiftTestOptionals& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    SwiftTestOptionals(std::string required_field_,
                       std::optional<std::string> optional_string_,
                       std::optional<int32_t> optional_int_,
                       std::optional<SwiftTestColor> optional_enum_,
                       std::optional<SwiftTestAllPrimitives> optional_record_,
                       std::optional<std::vector<std::string>> optional_list_)
    : required_field(std::move(required_field_))
    , optional_string(std::move(optional_string_))
    , optional_int(std::move(optional_int_))
    , optional_enum(std::move(optional_enum_))
    , optional_record(std::move(optional_record_))
    , optional_list(std::move(optional_list_))
    {}
};

} // namespace testsuite
