// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include <chrono>
#include <cstdint>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

namespace testsuite {

/**
 * ============================================================
 * Test: All primitive types in a single record
 * Verifies: type mapping for every primitive
 * ============================================================
 */
struct SwiftTestAllPrimitives final {
    bool my_bool;
    int8_t my_i8;
    int16_t my_i16;
    int32_t my_i32;
    int64_t my_i64;
    float my_f32;
    double my_f64;
    std::string my_string;
    std::vector<uint8_t> my_binary;
    std::chrono::system_clock::time_point my_date;

    friend bool operator==(const SwiftTestAllPrimitives& lhs, const SwiftTestAllPrimitives& rhs);
    friend bool operator!=(const SwiftTestAllPrimitives& lhs, const SwiftTestAllPrimitives& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    SwiftTestAllPrimitives(bool my_bool_,
                           int8_t my_i8_,
                           int16_t my_i16_,
                           int32_t my_i32_,
                           int64_t my_i64_,
                           float my_f32_,
                           double my_f64_,
                           std::string my_string_,
                           std::vector<uint8_t> my_binary_,
                           std::chrono::system_clock::time_point my_date_)
    : my_bool(std::move(my_bool_))
    , my_i8(std::move(my_i8_))
    , my_i16(std::move(my_i16_))
    , my_i32(std::move(my_i32_))
    , my_i64(std::move(my_i64_))
    , my_f32(std::move(my_f32_))
    , my_f64(std::move(my_f64_))
    , my_string(std::move(my_string_))
    , my_binary(std::move(my_binary_))
    , my_date(std::move(my_date_))
    {}
};

} // namespace testsuite
