// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_extern_record.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestExternRecord& lhs, const SwiftTestExternRecord& rhs) {
    return lhs.background_color == rhs.background_color &&
           lhs.label_text == rhs.label_text &&
           lhs.icon == rhs.icon &&
           lhs.action == rhs.action;
}

bool operator!=(const SwiftTestExternRecord& lhs, const SwiftTestExternRecord& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestExternRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestExternRecord {";

        ss << "\n" << childIndentation;
        ss << "background_color=" << background_color.getTestRepresentation(childIndentation);

        ss << "\n" << childIndentation;
        ss << "label_text=" << label_text.getTestRepresentation(childIndentation);

        ss << "\n" << childIndentation;
        ss << "icon=" << icon.getTestRepresentation(childIndentation);

        ss << "\n" << childIndentation;
        ss << "action=" << action.getTestRepresentation(childIndentation);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
