// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_optionals.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestOptionals& lhs, const SwiftTestOptionals& rhs) {
    return lhs.required_field == rhs.required_field &&
           lhs.optional_string == rhs.optional_string &&
           lhs.optional_int == rhs.optional_int &&
           lhs.optional_enum == rhs.optional_enum &&
           lhs.optional_record == rhs.optional_record &&
           lhs.optional_list == rhs.optional_list;
}

bool operator!=(const SwiftTestOptionals& lhs, const SwiftTestOptionals& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestOptionals::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestOptionals {";

        ss << "\n" << childIndentation;
        ss << "required_field=" << required_field;

        ss << "\n" << childIndentation;
        if (optional_string) {
            ss << "optional_string=" << *optional_string;
        }
        else {
            ss << "optional_string=<none>";
        }

        ss << "\n" << childIndentation;
        if (optional_int) {
            ss << "optional_int=" << *optional_int;
        }
        else {
            ss << "optional_int=<none>";
        }

        ss << "\n" << childIndentation;
        if (optional_enum) {
            ss << "optional_enum=" << to_string(*optional_enum);
        }
        else {
            ss << "optional_enum=<none>";
        }

        ss << "\n" << childIndentation;
        if (optional_record) {
            ss << "optional_record=" << optional_record->getTestRepresentation(childIndentation);
        }
        else {
            ss << "optional_record=<none>";
        }

        ss << "\n" << childIndentation;
        if (optional_list) {
            ss << "optional_list=" << *optional_list;
        }
        else {
            ss << "optional_list=<none>";
        }

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
