// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "TestColor.h"
#include "UserAction.h"
#include <optional>
#include <sstream>
#include <string>
#include <utility>

namespace testsuite {

/** Extern type in optional field (skip should still apply) */
struct SwiftTestExternOptional final {
    std::string name;
    std::optional<TestColor> opt_color;
    std::optional<UserAction> opt_action;

    friend bool operator==(const SwiftTestExternOptional& lhs, const SwiftTestExternOptional& rhs);
    friend bool operator!=(const SwiftTestExternOptional& lhs, const SwiftTestExternOptional& rhs);

    std::string getTestRepresentation(const std::string& indentation) const;

    SwiftTestExternOptional(std::string name_,
                            std::optional<TestColor> opt_color_,
                            std::optional<UserAction> opt_action_)
    : name(std::move(name_))
    , opt_color(std::move(opt_color_))
    , opt_action(std::move(opt_action_))
    {}
};

} // namespace testsuite
