// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_documented.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestDocumented& lhs, const SwiftTestDocumented& rhs) {
    return lhs.text == rhs.text &&
           lhs.visible == rhs.visible;
}

bool operator!=(const SwiftTestDocumented& lhs, const SwiftTestDocumented& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestDocumented::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestDocumented {";

        ss << "\n" << childIndentation;
        ss << "text=" << text;

        ss << "\n" << childIndentation;
        ss << "visible=" << visible;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
