// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include "swift_test_base_label.hpp"
#include <sstream>
#include <string>
#include <utility>

namespace testsuite {

struct SwiftTestLabel : public SwiftTestBaseLabel {
    std::string text;
    bool is_bold;

    friend bool operator==(const SwiftTestLabel& lhs, const SwiftTestLabel& rhs);
    friend bool operator!=(const SwiftTestLabel& lhs, const SwiftTestLabel& rhs);

    std::string getTestRepresentation(const std::string& indentation) const override;

    SwiftTestLabel(int32_t text_color_,
                   float font_size_,
                   std::string text_,
                   bool is_bold_)
    : 
    SwiftTestBaseLabel( text_color_,
                        font_size_), text(std::move(text_)), is_bold(std::move(is_bold_))
    {}
};

} // namespace testsuite
