// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_label.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestLabel& lhs, const SwiftTestLabel& rhs) {
    return lhs.text_color == rhs.text_color &&
           lhs.font_size == rhs.font_size &&
           lhs.text == rhs.text &&
           lhs.is_bold == rhs.is_bold;
}

bool operator!=(const SwiftTestLabel& lhs, const SwiftTestLabel& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestLabel::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestLabel {";

        ss << "\n" << childIndentation;
        ss << SwiftTestBaseLabel::getTestRepresentation(childIndentation);

        ss << "\n" << childIndentation;
        ss << "text=" << text;

        ss << "\n" << childIndentation;
        ss << "is_bold=" << is_bold;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
