// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_single_field.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestSingleField& lhs, const SwiftTestSingleField& rhs) {
    return lhs.value == rhs.value;
}

bool operator!=(const SwiftTestSingleField& lhs, const SwiftTestSingleField& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestSingleField::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestSingleField {";

        ss << "\n" << childIndentation;
        ss << "value=" << value;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
