// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_nested.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestNested& lhs, const SwiftTestNested& rhs) {
    return lhs.label == rhs.label &&
           lhs.color == rhs.color &&
           lhs.style == rhs.style;
}

bool operator!=(const SwiftTestNested& lhs, const SwiftTestNested& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestNested::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestNested {";

        ss << "\n" << childIndentation;
        ss << "label=" << label.getTestRepresentation(childIndentation);

        ss << "\n" << childIndentation;
        ss << "color=" << to_string(color);

        ss << "\n" << childIndentation;
        ss << "style=" << style.getTestRepresentation(childIndentation);

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
