// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#include "swift_test_collections.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const SwiftTestCollections& lhs, const SwiftTestCollections& rhs) {
    return lhs.string_list == rhs.string_list &&
           lhs.int_set == rhs.int_set &&
           lhs.string_to_int_map == rhs.string_to_int_map &&
           lhs.nested_list == rhs.nested_list &&
           lhs.enum_list == rhs.enum_list &&
           lhs.enum_map == rhs.enum_map;
}

bool operator!=(const SwiftTestCollections& lhs, const SwiftTestCollections& rhs) {
    return !(lhs == rhs);
}

std::string SwiftTestCollections::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "SwiftTestCollections {";

        ss << "\n" << childIndentation;
        ss << "int_set=" << int_set;

        ss << "\n" << childIndentation;
        ss << "string_to_int_map=" << string_to_int_map;

        ss << "\n" << childIndentation;
        ss << "enum_map=" << enum_map;

        ss << "\n";

        ss << "\n" << childIndentation;
        ss << "string_list=[";
        for (size_t i = 0; i < string_list.size(); ++i) {
            if (i > 0) { ss << ","; }
            ss << "\n" << childIndentation << "   ";
            ss << string_list[i];
        }
        if (!string_list.empty()) {
            ss << "\n" << childIndentation;
        }
        ss << "]";

        ss << "\n" << childIndentation;
        ss << "nested_list=[";
        for (size_t i = 0; i < nested_list.size(); ++i) {
            if (i > 0) { ss << ","; }
            ss << "\n" << childIndentation << "   ";
            ss << nested_list[i];
        }
        if (!nested_list.empty()) {
            ss << "\n" << childIndentation;
        }
        ss << "]";

        ss << "\n" << childIndentation;
        ss << "enum_list=[";
        for (size_t i = 0; i < enum_list.size(); ++i) {
            if (i > 0) { ss << ","; }
            ss << "\n" << childIndentation << "   ";
            ss << to_string(enum_list[i]);
        }
        if (!enum_list.empty()) {
            ss << "\n" << childIndentation;
        }
        ss << "]";

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
