// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include <functional>

namespace testsuite {

enum class SwiftTestLetterCase : int {
    DEFAULT = 0,
    UPPER = 1,
    LOWER = 2,
};

constexpr const char* to_string(SwiftTestLetterCase e) noexcept {
    constexpr const char* names[] = {
        "Default",
        "Upper",
        "Lower",
    };
    return names[static_cast<int>(e)];
}

} // namespace testsuite

namespace std {

template <>
struct hash<::testsuite::SwiftTestLetterCase> {
    size_t operator()(::testsuite::SwiftTestLetterCase type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
