// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#pragma once

#include <functional>

namespace testsuite {

enum class SwiftTestColor : int {
    RED = 0,
    GREEN = 1,
    BLUE = 2,
};

constexpr const char* to_string(SwiftTestColor e) noexcept {
    constexpr const char* names[] = {
        "Red",
        "Green",
        "Blue",
    };
    return names[static_cast<int>(e)];
}

} // namespace testsuite

namespace std {

template <>
struct hash<::testsuite::SwiftTestColor> {
    size_t operator()(::testsuite::SwiftTestColor type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
