// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from yaml-test.djinni

#include "test_optional_extern_interface_record.hpp"  // my header
#include "BuildConstants.h"


bool operator==(const TestOptionalExternInterfaceRecord& lhs, const TestOptionalExternInterfaceRecord& rhs) {
    return lhs.sample_interface == rhs.sample_interface;
}

bool operator!=(const TestOptionalExternInterfaceRecord& lhs, const TestOptionalExternInterfaceRecord& rhs) {
    return !(lhs == rhs);
}

std::string TestOptionalExternInterfaceRecord::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "TestOptionalExternInterfaceRecord {";

        ss << "\n" << childIndentation;
        if (sample_interface) {
            ss << "sample_interface=" << *sample_interface;
        }
        else {
            ss << "sample_interface=<none>";
        }

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}
