// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from array.djinni

#include "vec2.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const Vec2& lhs, const Vec2& rhs) {
    return lhs.x == rhs.x &&
           lhs.y == rhs.y;
}

bool operator!=(const Vec2& lhs, const Vec2& rhs) {
    return !(lhs == rhs);
}

std::string Vec2::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "Vec2 {";

        ss << "\n" << childIndentation;
        ss << "x=" << x;

        ss << "\n" << childIndentation;
        ss << "y=" << y;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
