// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wchar_test.djinni

#include "wchar_test_rec.hpp"  // my header
#include "BuildConstants.h"

namespace testsuite {


bool operator==(const WcharTestRec& lhs, const WcharTestRec& rhs) {
    return lhs.s == rhs.s;
}

bool operator!=(const WcharTestRec& lhs, const WcharTestRec& rhs) {
    return !(lhs == rhs);
}

std::string WcharTestRec::getTestRepresentation(const std::string& textIndentation) const {
    if constexpr (BuildConstants::UnitTests) {
        std::ostringstream ss;
        auto childIndentation = textIndentation + "   ";
        ss << "WcharTestRec {";

        ss << "\n" << childIndentation;
        ss << "s=" << s;

        ss << "\n" << textIndentation << "}";
        return ss.str();
    }
    return "";
}

} // namespace testsuite
