// vinsg
// Generator trait and shared generation utilities, translated from generator.scala

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use djinni_ast::ast::*;
use djinni_ast::ident_style;
use djinni_ast::spec::Spec;

use crate::writer::IndentWriter;

pub struct GeneratorContext {
    pub spec: Spec,
    pub written_files: HashMap<String, String>,
    pub out_files: Vec<PathBuf>,
}

pub fn create_file_from_parts<F>(
    out_files: &mut Vec<PathBuf>,
    written_files: &mut HashMap<String, String>,
    folder: &Path,
    file_name: &str,
    f: F,
) where
    F: FnOnce(&mut IndentWriter),
{
    let file_path = folder.join(file_name);
    out_files.push(file_path.clone());

    let cp = file_path.to_string_lossy().to_lowercase();
    if let Some(existing) = written_files.get(&cp) {
        panic!(
            "Refusing to write \"{}\"; we already wrote a file to path \"{}\"",
            file_path.display(),
            existing
        );
    }
    written_files.insert(cp, file_path.to_string_lossy().to_string());

    let mut w = IndentWriter::new();
    f(&mut w);
    fs::write(&file_path, w.into_string()).expect("Failed to write file");
}

impl GeneratorContext {
    pub fn create_file<F>(&mut self, folder: &Path, file_name: &str, f: F)
    where
        F: FnOnce(&mut IndentWriter),
    {
        create_file_from_parts(&mut self.out_files, &mut self.written_files, folder, file_name, f);
    }

    /// Split borrow: returns (&Spec, &mut out_files, &mut written_files) so that
    /// callers can hold an immutable reference to spec (e.g. via CppMarshal) while
    /// still creating files.
    pub fn split_borrow(&mut self) -> (&Spec, &mut Vec<PathBuf>, &mut HashMap<String, String>) {
        (&self.spec, &mut self.out_files, &mut self.written_files)
    }

    pub fn write_hpp_file(
        &mut self,
        folder: &Path,
        namespace: &str,
        file_ident_style: fn(&str) -> String,
        name: &str,
        origin: &str,
        includes: &[String],
        fwds: &[String],
        f: impl FnOnce(&mut IndentWriter),
        f2: impl FnOnce(&mut IndentWriter),
    ) {
        let file_name = format!("{}.{}", file_ident_style(name), self.spec.cpp_header_ext);
        self.create_file(folder, &file_name, |w| {
            w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
            w.wl(&format!("// This file was generated by Djinni from {}", origin));
            w.wl_empty();
            w.wl("#pragma once");
            if !includes.is_empty() {
                w.wl_empty();
                for inc in includes {
                    w.wl(inc);
                }
            }
            w.wl_empty();
            wrap_namespace(w, namespace, |w| {
                if !fwds.is_empty() {
                    for fwd in fwds {
                        w.wl(fwd);
                    }
                    w.wl_empty();
                }
                f(w);
            });
            f2(w);
        });
    }

    pub fn write_cpp_file(
        &mut self,
        folder: &Path,
        namespace: &str,
        file_ident_style: fn(&str) -> String,
        include_prefix: &str,
        name: &str,
        origin: &str,
        includes: &[String],
        f: impl FnOnce(&mut IndentWriter),
    ) {
        let file_name = format!("{}.{}", file_ident_style(name), self.spec.cpp_ext);
        let my_header = format!(
            "\"{}{}\"",
            include_prefix,
            format!("{}.{}", file_ident_style(name), self.spec.cpp_header_ext)
        );
        let my_header_include = format!("#include {}", my_header);

        self.create_file(folder, &file_name, |w| {
            w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
            w.wl(&format!("// This file was generated by Djinni from {}", origin));
            w.wl_empty();
            w.wl(&format!("#include {}  // my header", my_header));
            for inc in includes {
                if *inc != my_header_include {
                    w.wl(inc);
                }
            }
            w.wl_empty();
            wrap_namespace(w, namespace, f);
        });
    }
}

pub fn wrap_namespace<F: FnOnce(&mut IndentWriter)>(w: &mut IndentWriter, ns: &str, f: F) {
    if ns.is_empty() {
        f(w);
    } else {
        w.wl(&format!("namespace {} {{", ns));
        w.wl_empty();
        f(w);
        w.wl_empty();
        w.wl(&format!("}} // namespace {}", ns));
    }
}

pub fn wrap_anonymous_namespace<F: FnOnce(&mut IndentWriter)>(w: &mut IndentWriter, f: F) {
    w.wl("namespace { // anonymous namespace");
    w.wl_empty();
    f(w);
    w.wl_empty();
    w.wl("} // end anonymous namespace");
}

pub fn write_doc(w: &mut IndentWriter, doc: &Doc) {
    match doc.lines.len() {
        0 => {}
        1 => {
            w.wl(&format!("/**{} */", doc.lines[0]));
        }
        _ => {
            w.wl("/**");
            for line in &doc.lines {
                w.wl(&format!(" *{}", line));
            }
            w.wl(" */");
        }
    }
}

pub fn write_method_doc(
    w: &mut IndentWriter,
    doc: &Doc,
    params: &[Field],
    ident_fn: fn(&str) -> String,
) {
    if doc.lines.is_empty() {
        return;
    }
    let new_lines: Vec<String> = doc
        .lines
        .iter()
        .map(|line| {
            let mut result = line.clone();
            for p in params {
                let pattern = format!("\\b{}\\b", regex_escape(&p.ident.name));
                let replacement = ident_fn(&p.ident.name);
                if let Ok(re) = regex::Regex::new(&pattern) {
                    result = re.replace_all(&result, replacement.as_str()).to_string();
                }
            }
            result
        })
        .collect();
    write_doc(w, &Doc { lines: new_lines });
}

fn regex_escape(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        if "\\^$.|?*+()[]{}".contains(c) {
            result.push('\\');
        }
        result.push(c);
    }
    result
}

pub fn normal_enum_options(e: &Enum) -> Vec<&EnumOption> {
    e.options
        .iter()
        .filter(|o| o.special_flag.is_none())
        .collect()
}

pub fn write_enum_option_none(
    w: &mut IndentWriter,
    e: &Enum,
    ident_fn: fn(&str) -> String,
    delim: &str,
) {
    if let Some(o) = e.options.iter().find(|o| o.special_flag == Some(SpecialFlag::NoFlags)) {
        write_doc(w, &o.doc);
        w.wl(&format!("{} {} 0,", ident_fn(&o.ident.name), delim));
    }
}

pub fn write_enum_options(
    w: &mut IndentWriter,
    e: &Enum,
    ident_fn: fn(&str) -> String,
    delim: &str,
) {
    for (shift, o) in normal_enum_options(e).iter().enumerate() {
        write_doc(w, &o.doc);
        if e.flags {
            w.wl(&format!(
                "{} {} 1 << {},",
                ident_fn(&o.ident.name),
                delim,
                shift
            ));
        } else {
            w.wl(&format!(
                "{} {} {},",
                ident_fn(&o.ident.name),
                delim,
                shift
            ));
        }
    }
}

pub fn write_enum_option_all(
    w: &mut IndentWriter,
    e: &Enum,
    ident_fn: fn(&str) -> String,
    delim: &str,
) {
    if let Some(o) = e
        .options
        .iter()
        .find(|o| o.special_flag == Some(SpecialFlag::AllFlags))
    {
        write_doc(w, &o.doc);
        w.w(&format!("{} {} ", ident_fn(&o.ident.name), delim));
        let normal = normal_enum_options(e);
        let parts: Vec<String> = normal
            .iter()
            .enumerate()
            .map(|(i, _)| format!("(1 << {})", i))
            .collect();
        let combined = if parts.is_empty() {
            "0".to_string()
        } else {
            parts.iter().fold("0".to_string(), |acc, o| format!("{} | {}", acc, o))
        };
        w.wl(&format!("{},", combined));
    }
}

pub fn write_aligned_call(
    w: &mut IndentWriter,
    call: &str,
    params: &[Field],
    delim: &str,
    end: &str,
    f: impl Fn(&Field) -> String,
) {
    w.w(call);
    let mut first = true;
    for p in params {
        if first {
            first = false;
        } else {
            w.wl(delim);
            w.w(&" ".repeat(call.len()));
        }
        w.w(&f(p));
    }
    w.w(end);
}

/// Collect all fields from a record and its base records (inheritance chain)
pub fn collect_super_fields(idl: &[TypeDecl], r: &Record) -> Vec<Field> {
    let mut fields = r.fields.clone();
    let mut current = r.clone();
    while let Some(ref base_name) = current.base_record {
        if let Some(td) = idl.iter().find(|td| td.ident().name == *base_name) {
            if let TypeDef::Record(super_rec) = td.body() {
                fields = [super_rec.fields.clone(), fields].concat();
                current = super_rec.clone();
            } else {
                break;
            }
        } else {
            break;
        }
    }
    fields
}

pub fn get_super_record(idl: &[TypeDecl], r: &Record) -> Option<SuperRecord> {
    r.base_record.as_ref().and_then(|base_name| {
        idl.iter().find(|td| td.ident().name == *base_name).map(|td| {
            if let TypeDef::Record(super_rec) = td.body() {
                let super_fields = collect_super_fields(idl, super_rec);
                SuperRecord {
                    ident: td.ident().clone(),
                    record: super_rec.clone(),
                    fields: super_fields,
                }
            } else {
                panic!("Base record is not a record type")
            }
        })
    })
}

pub fn is_inherited(idl: &[TypeDecl], name: &str) -> bool {
    idl.iter().any(|td| {
        if td.ident().name == name {
            return false;
        }
        if let TypeDef::Record(r) = td.body() {
            r.base_record.as_deref() == Some(name)
        } else {
            false
        }
    })
}

pub fn with_ns(namespace: Option<&str>, t: &str) -> String {
    match namespace {
        None => t.to_string(),
        Some("") => format!("::{}", t),
        Some(s) => format!("::{}::{}", s, t),
    }
}
