// vinsg
// JavaGenerator: generates Java source files, translated from JavaGenerator.scala

use std::collections::BTreeSet;
use std::path::Path;

use djinni_ast::ast::*;
use djinni_ast::meta::*;
use djinni_ast::spec::q;

use crate::gen::*;
use crate::java_marshal::JavaMarshal;
use crate::writer::IndentWriter;

/// Format a float like Scala's Double.toString
fn fmt_float(d: f64) -> String {
    let s = d.to_string();
    if s.contains('.') || s.contains('E') || s.contains('e') {
        s
    } else {
        format!("{}.0", s)
    }
}

pub fn generate_java(ctx: &mut GeneratorContext, idl: &[TypeDecl]) {
    let java_out = match &ctx.spec.java_out_folder {
        Some(f) => f.clone(),
        None => return,
    };

    let intern_decls: Vec<_> = idl
        .iter()
        .filter_map(|td| {
            if let TypeDecl::Intern { ident, params, body, doc, origin } = td {
                Some((ident.clone(), params.clone(), body.clone(), doc.clone(), origin.clone()))
            } else {
                None
            }
        })
        .collect();

    for (ident, params, body, doc, origin) in &intern_decls {
        match body {
            TypeDef::Enum(e) => {
                assert!(params.is_empty());
                generate_enum(ctx, &java_out, origin, ident, doc, e, idl);
            }
            TypeDef::Record(r) => {
                generate_record(ctx, &java_out, origin, ident, doc, params, r, idl);
            }
            TypeDef::Interface(i) => {
                generate_interface(ctx, &java_out, origin, ident, doc, params, i, idl);
            }
            TypeDef::ProtobufMessage(_) => {}
        }
    }
}

// --- JavaRefs ---

struct JavaRefs {
    java: BTreeSet<String>,
}

impl JavaRefs {
    fn new(spec: &djinni_ast::spec::Spec) -> Self {
        let mut java = BTreeSet::new();
        if let Some(ref pkg) = spec.java_annotation {
            java.insert(pkg.clone());
        }
        if let Some(ref pkg) = spec.java_nullable_annotation {
            java.insert(pkg.clone());
        }
        if let Some(ref pkg) = spec.java_nonnull_annotation {
            java.insert(pkg.clone());
        }
        JavaRefs { java }
    }

    fn find_type_ref(&mut self, ty: &TypeRef, marshal: &JavaMarshal) {
        if let Some(resolved) = &ty.resolved {
            self.find_mexpr(resolved, marshal);
        }
    }

    fn find_mexpr(&mut self, tm: &MExpr, marshal: &JavaMarshal) {
        for arg in &tm.args {
            self.find_mexpr(arg, marshal);
        }
        self.find_meta(&tm.base, marshal);
    }

    fn find_meta(&mut self, m: &Meta, marshal: &JavaMarshal) {
        for r in marshal.references(m) {
            if let crate::cpp_marshal::SymbolReference::ImportRef(arg) = r {
                self.java.insert(arg);
            }
        }
    }
}

// --- write Java file ---

fn write_java_file<F>(
    ctx: &mut GeneratorContext,
    folder: &Path,
    ident: &str,
    origin: &str,
    refs: &BTreeSet<String>,
    f: F,
) where
    F: FnOnce(&mut IndentWriter),
{
    let id_java_ty = (ctx.spec.java_ident_style.ty)(ident);
    let file_name = format!("{}.java", id_java_ty);
    let java_package = ctx.spec.java_package.clone();

    ctx.create_file(folder, &file_name, |w| {
        w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!("// This file was generated by Djinni from {}", origin));
        w.wl_empty();
        if let Some(ref pkg) = java_package {
            w.wl(&format!("package {};", pkg));
            w.wl_empty();
        }
        if !refs.is_empty() {
            for s in refs {
                w.wl(&format!("import {};", s));
            }
            w.wl_empty();
        }
        f(w);
    });
}

// --- Enum Generation ---

fn generate_enum(
    ctx: &mut GeneratorContext,
    folder: &Path,
    origin: &str,
    ident: &Ident,
    doc: &Doc,
    e: &Enum,
    _idl: &[TypeDecl],
) {
    let marshal = JavaMarshal::new(&ctx.spec, false);
    let refs = JavaRefs::new(&ctx.spec);
    let java_annotation_header = ctx.spec.java_annotation.as_ref().map(|pkg| {
        format!("@{}", pkg.split('.').last().unwrap_or(pkg))
    });
    let access_mod = ctx.spec.java_class_access_modifier.code_generation_string().to_string();
    let self_name = marshal.typename_from_name(&ident.name, &TypeDef::Enum(e.clone()));
    let id_java_enum: fn(&str) -> String = ctx.spec.java_ident_style.enum_;

    write_java_file(ctx, folder, &ident.name, origin, &refs.java, |w| {
        write_doc(w, doc);
        if let Some(ref ann) = java_annotation_header {
            w.wl(ann);
        }
        w.w(&format!("{}enum {}", access_mod, self_name));
        w.braced(|w| {
            for o in normal_enum_options(e) {
                write_doc(w, &o.doc);
                w.wl(&format!("{},", id_java_enum(&o.ident.name)));
            }
            w.wl(";");
        });
    });
}

// --- Interface Generation ---

fn generate_interface(
    ctx: &mut GeneratorContext,
    folder: &Path,
    origin: &str,
    ident: &Ident,
    doc: &Doc,
    type_params: &[TypeParam],
    i: &Interface,
    _idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let marshal = JavaMarshal::new(spec, false);
    let mut refs = JavaRefs::new(spec);

    for m in &i.methods {
        for p in &m.params {
            refs.find_type_ref(&p.ty, &marshal);
        }
        if let Some(ref ret) = m.ret {
            refs.find_type_ref(ret, &marshal);
        }
    }
    for c in &i.consts {
        refs.find_type_ref(&c.ty, &marshal);
    }
    if i.ext.cpp {
        refs.java.insert("java.util.concurrent.atomic.AtomicBoolean".into());
        refs.java.insert("com.snapchat.djinni.NativeObjectManager".into());
    }

    let java_class = marshal.typename_from_name(&ident.name, &TypeDef::Interface(i.clone()));
    let type_param_list = java_type_params(type_params, spec);
    let java_annotation_header = spec.java_annotation.as_ref().map(|pkg| {
        format!("@{}", pkg.split('.').last().unwrap_or(pkg))
    });
    let access_mod = spec.java_class_access_modifier.code_generation_string().to_string();
    let java_cpp_exception = spec.java_cpp_exception.clone();
    let jni_use_on_load = spec.jni_use_on_load;
    let java_gen_interface = spec.java_gen_interface;
    let java_package = spec.java_package.clone();
    let module_class = format!("{}Module", (spec.java_ident_style.ty)(&spec.module_name));
    let id_java = &spec.java_ident_style;
    let id_java_method: fn(&str) -> String = id_java.method;
    let id_java_local: fn(&str) -> String = id_java.local;
    let id_java_enum: fn(&str) -> String = id_java.enum_;
    let id_java_const: fn(&str) -> String = id_java.const_;

    let statics: Vec<&Method> = i.methods.iter().filter(|m| m.is_static && m.lang.java).collect();
    let gen_java_interface = java_gen_interface && statics.is_empty() && !i.ext.cpp;
    let class_or_interface = if gen_java_interface { "interface" } else { "abstract class" };
    let method_prefix = if gen_java_interface { "" } else { "public abstract " };
    let throw_exception = java_cpp_exception.as_ref().map(|e| format!(" throws {}", e)).unwrap_or_default();

    let file_name = format!("{}.java", (id_java.ty)(&ident.name));
    let refs_java = refs.java.clone();
    let consts = i.consts.clone();
    let methods = i.methods.clone();
    let ext_cpp = i.ext.cpp;

    create_file_from_parts(out_files, written_files, folder, &file_name, |w| {
        w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!("// This file was generated by Djinni from {}", origin));
        w.wl_empty();
        if let Some(ref pkg) = java_package {
            w.wl(&format!("package {};", pkg));
            w.wl_empty();
        }
        if !refs_java.is_empty() {
            for s in &refs_java {
                w.wl(&format!("import {};", s));
            }
            w.wl_empty();
        }

        write_doc(w, doc);
        if let Some(ref ann) = java_annotation_header {
            w.wl(ann);
        }
        w.w(&format!("{}{} {}{}", access_mod, class_or_interface, java_class, type_param_list));
        w.braced(|w| {
            // Constants
            write_java_constants(w, &consts, &marshal, id_java_enum, id_java_const, &id_java.field, _idl);

            let mut first_member = consts.is_empty();

            // Non-static methods
            for m in methods.iter().filter(|m| !m.is_static) {
                if !first_member {
                    w.wl_empty();
                }
                first_member = false;
                write_method_doc(w, &m.doc, &m.params, id_java_local);
                let ret = marshal.return_type(&m.ret);
                let params: Vec<String> = m.params.iter().map(|p| {
                    let nullity = marshal.nullity_annotation(&p.ty).map(|a| format!("{} ", a)).unwrap_or_default();
                    format!(
                        "{}{} {}",
                        nullity,
                        marshal.param_type_from_mexpr(p.ty.resolved.as_ref().unwrap()),
                        id_java_local(&p.ident.name)
                    )
                }).collect();
                if let Some(ann) = marshal.nullity_annotation_opt(&m.ret) {
                    w.wl(&ann);
                }
                w.wl(&format!(
                    "{}{} {}({}){};",
                    method_prefix, ret, id_java_method(&m.ident.name), params.join(", "), throw_exception
                ));
            }

            // Static methods
            let statics: Vec<&Method> = methods.iter().filter(|m| m.is_static && m.lang.java).collect();
            if !statics.is_empty() {
                // Module initializer
                if jni_use_on_load {
                    w.wl("static");
                    w.braced(|w| {
                        w.wl("try");
                        w.braced(|w| {
                            w.wl(&format!(
                                "Class.forName({});",
                                q(&format!("{}.{}", java_package.as_deref().unwrap_or(""), module_class))
                            ));
                        });
                        w.wl("catch (ClassNotFoundException e)");
                        w.braced(|w| {
                            w.wl(&format!(
                                "throw new IllegalStateException({}, e);",
                                q("Failed to initialize djinni module")
                            ));
                        });
                    });
                }
            }
            for m in &statics {
                w.wl_empty();
                write_method_doc(w, &m.doc, &m.params, id_java_local);
                let ret = marshal.return_type(&m.ret);
                let params: Vec<String> = m.params.iter().map(|p| {
                    let nullity = marshal.nullity_annotation(&p.ty).map(|a| format!("{} ", a)).unwrap_or_default();
                    format!(
                        "{}{} {}",
                        nullity,
                        marshal.param_type_from_mexpr(p.ty.resolved.as_ref().unwrap()),
                        id_java_local(&p.ident.name)
                    )
                }).collect();
                if let Some(ann) = marshal.nullity_annotation_opt(&m.ret) {
                    w.wl(&ann);
                }
                w.wl(&format!(
                    "public static native {} {}({});",
                    ret, id_java_method(&m.ident.name), params.join(", ")
                ));
            }

            // CppProxy
            if ext_cpp {
                w.wl_empty();
                if let Some(ref ann) = java_annotation_header {
                    w.wl(ann);
                }
                w.wl(&format!(
                    "public static final class CppProxy{} extends {}{}",
                    type_param_list, java_class, type_param_list
                ));
                w.braced(|w| {
                    // Module initializer
                    if jni_use_on_load {
                        w.wl("static");
                        w.braced(|w| {
                            w.wl("try");
                            w.braced(|w| {
                                w.wl(&format!(
                                    "Class.forName({});",
                                    q(&format!("{}.{}", java_package.as_deref().unwrap_or(""), module_class))
                                ));
                            });
                            w.wl("catch (ClassNotFoundException e)");
                            w.braced(|w| {
                                w.wl(&format!(
                                    "throw new IllegalStateException({}, e);",
                                    q("Failed to initialize djinni module")
                                ));
                            });
                        });
                    }
                    w.wl("private final long nativeRef;");
                    w.wl("private final AtomicBoolean destroyed = new AtomicBoolean(false);");
                    w.wl_empty();
                    w.wl("private CppProxy(long nativeRef)");
                    w.braced(|w| {
                        w.wl("if (nativeRef == 0) throw new RuntimeException(\"nativeRef is zero\");");
                        w.wl("this.nativeRef = nativeRef;");
                        w.wl("NativeObjectManager.register(this, nativeRef);");
                    });
                    w.wl("public static native void nativeDestroy(long nativeRef);");
                    for m in methods.iter().filter(|m| !m.is_static) {
                        let ret = marshal.return_type(&m.ret);
                        let return_stmt = if m.ret.is_some() { "return " } else { "" };
                        let params: Vec<String> = m.params.iter().map(|p| {
                            format!(
                                "{} {}",
                                marshal.param_type_from_mexpr(p.ty.resolved.as_ref().unwrap()),
                                id_java_local(&p.ident.name)
                            )
                        }).collect();
                        let args: Vec<String> = m.params.iter().map(|p| {
                            id_java_local(&p.ident.name).to_string()
                        }).collect();
                        let meth = id_java_method(&m.ident.name);
                        let args_str = if args.is_empty() { String::new() } else { format!(", {}", args.join(", ")) };
                        w.wl_empty();
                        w.wl("@Override");
                        w.wl(&format!("public {} {}({}){}", ret, meth, params.join(", "), throw_exception));
                        w.braced(|w| {
                            w.wl("assert !this.destroyed.get() : \"trying to use a destroyed object\";");
                            w.wl(&format!("{}native_{}(this.nativeRef{});", return_stmt, meth, args_str));
                        });
                        w.wl(&format!(
                            "private native {} native_{}(long _nativeRef{});",
                            ret, meth,
                            if params.is_empty() { String::new() } else { format!(", {}", params.join(", ")) }
                        ));
                    }
                });
            }
        });
    });
}

// --- Record Generation ---

fn generate_record(
    ctx: &mut GeneratorContext,
    folder: &Path,
    origin: &str,
    ident: &Ident,
    doc: &Doc,
    params: &[TypeParam],
    r: &Record,
    idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let marshal = JavaMarshal::new(spec, false);
    let mut refs = JavaRefs::new(spec);

    for f in &r.fields {
        refs.find_type_ref(&f.ty, &marshal);
    }

    let java_name = if r.ext.java {
        format!("{}_base", ident.name)
    } else {
        ident.name.clone()
    };
    let java_final = if !r.ext.java && spec.java_use_final_for_record {
        "final "
    } else {
        ""
    };

    let super_record = get_super_record(idl, r);
    let super_fields: Vec<Field> = super_record
        .as_ref()
        .map(|sr| sr.fields.clone())
        .unwrap_or_default();
    let all_fields: Vec<Field> = [super_fields.clone(), r.fields.clone()].concat();

    let java_annotation_header = spec.java_annotation.as_ref().map(|pkg| {
        format!("@{}", pkg.split('.').last().unwrap_or(pkg))
    });
    let java_nullable_annotation = spec.java_nullable_annotation.as_ref().map(|pkg| {
        format!("@{}", pkg.split('.').last().unwrap_or(pkg))
    });
    let java_nonnull_annotation = spec.java_nonnull_annotation.as_ref().map(|pkg| {
        format!("@{}", pkg.split('.').last().unwrap_or(pkg))
    });
    let access_mod = spec.java_class_access_modifier.code_generation_string().to_string();
    let self_name = marshal.typename_from_name(&java_name, &TypeDef::Record(r.clone()));
    let type_param_str = java_type_params(params, spec);
    let id_java = &spec.java_ident_style;
    let id_java_method: fn(&str) -> String = id_java.method;
    let id_java_local: fn(&str) -> String = id_java.local;
    let id_java_enum: fn(&str) -> String = id_java.enum_;
    let id_java_const: fn(&str) -> String = id_java.const_;

    let mut interfaces = Vec::new();
    if r.deriving_types.contains(&DerivingType::Ord) {
        interfaces.push(format!("Comparable<{}>", self_name));
    }
    if r.deriving_types.contains(&DerivingType::AndroidParcelable) {
        interfaces.push("android.os.Parcelable".into());
    }
    let implements_section = if interfaces.is_empty() {
        String::new()
    } else {
        format!(" implements {}", interfaces.join(", "))
    };

    let extends_class = marshal.extends_record(idl, r);
    let consts = r.consts.clone();
    let fields = r.fields.clone();
    let deriving_types = r.deriving_types.clone();
    let refs_java = refs.java.clone();
    let java_package = spec.java_package.clone();
    let file_name = format!("{}.java", (id_java.ty)(&java_name));

    create_file_from_parts(out_files, written_files, folder, &file_name, |w| {
        w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!("// This file was generated by Djinni from {}", origin));
        w.wl_empty();
        if let Some(ref pkg) = java_package {
            w.wl(&format!("package {};", pkg));
            w.wl_empty();
        }
        if !refs_java.is_empty() {
            for s in &refs_java {
                w.wl(&format!("import {};", s));
            }
            w.wl_empty();
        }

        write_doc(w, doc);
        if let Some(ref ann) = java_annotation_header {
            w.wl(ann);
        }
        w.w(&format!(
            "{}{}class {}{}{}{}",
            access_mod, java_final, self_name, type_param_str, extends_class, implements_section
        ));
        w.braced(|w| {
            w.wl_empty();
            write_java_constants(w, &consts, &marshal, id_java_enum, id_java_const, &id_java.field, idl);

            // Field definitions
            for f in &fields {
                w.wl_empty();
                w.wl(&format!(
                    "/*package*/ final {} {};",
                    marshal.field_type_from_typeref(&f.ty),
                    (id_java.field)(&f.ident.name)
                ));
            }

            // Constructor
            w.wl_empty();
            w.wl(&format!("public {}(", self_name));
            w.nested_n(2, |w| {
                let mut skip_first = true;
                for f in all_fields.iter() {
                    if !skip_first {
                        w.wl(",");
                    }
                    skip_first = false;
                    if let Some(ref ann) = marshal.nullity_annotation(&f.ty) {
                        w.w(&format!("{} ", ann));
                    }
                    w.w(&format!(
                        "{} {}",
                        marshal.param_type_from_mexpr(f.ty.resolved.as_ref().unwrap()),
                        id_java_local(&f.ident.name)
                    ));
                }
                w.wl(") {");
            });
            w.nested(|w| {
                if !super_fields.is_empty() {
                    w.w("super(");
                    let mut sf_first = true;
                    for f in &super_fields {
                        if !sf_first {
                            w.w(",");
                        }
                        sf_first = false;
                        w.w(&id_java_local(&f.ident.name));
                    }
                    w.wl(");");
                }
                for f in &fields {
                    w.wl(&format!(
                        "this.{} = {};",
                        (id_java.field)(&f.ident.name),
                        id_java_local(&f.ident.name)
                    ));
                }
            });
            w.wl("}");

            // Accessors
            for f in all_fields.iter() {
                w.wl_empty();
                write_doc(w, &f.doc);
                if let Some(ref ann) = marshal.nullity_annotation(&f.ty) {
                    w.wl(ann);
                }
                w.w(&format!(
                    "public {} {}()",
                    marshal.return_type(&Some(f.ty.clone())),
                    id_java_method(&format!("get_{}", f.ident.name))
                ));
                w.braced(|w| {
                    w.wl(&format!("return {};", (id_java.field)(&f.ident.name)));
                });
            }

            // equals
            w.wl_empty();
            w.wl("@Override");
            let nullable_ann = java_nullable_annotation.as_ref().map(|a| format!("{} ", a)).unwrap_or_default();
            w.w(&format!("public boolean equals({}Object obj)", nullable_ann));
            w.braced(|w| {
                w.w(&format!("if (!(obj instanceof {}))", self_name));
                w.braced(|w| {
                    w.wl("return false;");
                });
                w.wl(&format!("{} other = ({}) obj;", self_name, self_name));
                w.w("return ");
                w.nested_n(2, |w| {
                    let mut skip_first = true;
                    for f in &fields {
                        // Skip protobuf fields in equals
                        if let Some(ref resolved) = f.ty.resolved {
                            if matches!(&resolved.base, Meta::MProtobuf(_)) {
                                continue;
                            }
                        }
                        if !skip_first {
                            w.wl(" &&");
                        }
                        skip_first = false;
                        let fname = (id_java.field)(&f.ident.name);
                        if let Some(ref resolved) = f.ty.resolved {
                            match &resolved.base {
                                Meta::MBinary | Meta::MArray => {
                                    w.w(&format!("java.util.Arrays.equals({}, other.{})", fname, fname));
                                }
                                Meta::MList | Meta::MSet | Meta::MMap | Meta::MString | Meta::MDate => {
                                    w.w(&format!("this.{}.equals(other.{})", fname, fname));
                                }
                                Meta::MOptional => {
                                    w.w(&format!(
                                        "((this.{0} == null && other.{0} == null) || (this.{0} != null && this.{0}.equals(other.{0})))",
                                        fname
                                    ));
                                }
                                Meta::MPrimitive(_) => {
                                    w.w(&format!("this.{} == other.{}", fname, fname));
                                }
                                Meta::MDef(d) => match d.def_type {
                                    DefType::Record => {
                                        w.w(&format!("this.{}.equals(other.{})", fname, fname));
                                    }
                                    DefType::Enum => {
                                        w.w(&format!("this.{} == other.{}", fname, fname));
                                    }
                                    _ => {}
                                },
                                Meta::MExtern(e) => match e.def_type {
                                    DefType::Record => {
                                        if e.java.reference {
                                            w.w(&format!("this.{}.equals(other.{})", fname, fname));
                                        } else {
                                            w.w(&format!("this.{} == other.{}", fname, fname));
                                        }
                                    }
                                    DefType::Enum => {
                                        w.w(&format!("this.{} == other.{}", fname, fname));
                                    }
                                    _ => {}
                                },
                                _ => {}
                            }
                        }
                    }
                });
                w.wl(";");
            });

            // hashCode
            w.wl_empty();
            w.wl("@Override");
            w.w("public int hashCode()");
            w.braced(|w| {
                w.wl("// Pick an arbitrary non-zero starting value");
                w.wl("int hashCode = 17;");
                for f in &all_fields {
                    let fname = (id_java.field)(&f.ident.name);
                    if let Some(ref resolved) = f.ty.resolved {
                        let hash_expr = match &resolved.base {
                            Meta::MBinary | Meta::MArray => format!("java.util.Arrays.hashCode({})", fname),
                            Meta::MList | Meta::MSet | Meta::MMap | Meta::MString | Meta::MDate => {
                                format!("{}.hashCode()", fname)
                            }
                            Meta::MDef(_) => format!("{}.hashCode()", fname),
                            Meta::MOptional => format!("({} == null ? 0 : {}.hashCode())", fname, fname),
                            Meta::MPrimitive(p) => match p.j_name.as_str() {
                                "byte" | "short" | "int" => fname.clone(),
                                "long" => format!("((int) ({0} ^ ({0} >>> 32)))", fname),
                                "float" => format!("Float.floatToIntBits({})", fname),
                                "double" => format!("((int) (Double.doubleToLongBits({0}) ^ (Double.doubleToLongBits({0}) >>> 32)))", fname),
                                "boolean" => format!("({} ? 1 : 0)", fname),
                                _ => fname.clone(),
                            },
                            Meta::MExtern(e) => match e.def_type {
                                DefType::Record => format!("({})", e.java.hash.replace("%s", &fname)),
                                DefType::Enum => format!("{}.hashCode()", fname),
                                _ => fname.clone(),
                            },
                            Meta::MProtobuf(_) => "()".to_string(),
                            _ => fname.clone(),
                        };
                        w.wl(&format!("hashCode = hashCode * 31 + {};", hash_expr));
                    }
                }
                w.wl("return hashCode;");
            });

            // toString
            w.wl_empty();
            w.wl("@Override");
            w.w("public String toString()");
            w.braced(|w| {
                w.w("return ");
                w.nested_n(2, |w| {
                    w.wl(&format!("\"{}{{\" +", self_name));
                    for (i, f) in all_fields.iter().enumerate() {
                        let name = (id_java.field)(&f.ident.name);
                        let comma = if i > 0 { "\",\" + " } else { "" };
                        w.wl(&format!("{}\"{}=\" + {} +", comma, name, name));
                    }
                });
                w.wl("\"}\";" );
            });
            w.wl_empty();

            // Parcelable
            if deriving_types.contains(&DerivingType::AndroidParcelable) {
                // TODO: implement Parcelable writeToParcel/createFromParcel if needed
            }

            // compareTo
            if deriving_types.contains(&DerivingType::Ord) {
                w.wl_empty();
                w.wl("@Override");
                let nonnull_ann = java_nonnull_annotation.as_ref().map(|a| format!("{} ", a)).unwrap_or_default();
                w.w(&format!("public int compareTo({}{} other) ", nonnull_ann, self_name));
                w.braced(|w| {
                    w.wl("int tempResult;");
                    for f in &all_fields {
                        let fname = (id_java.field)(&f.ident.name);
                        if let Some(ref resolved) = f.ty.resolved {
                            match &resolved.base {
                                Meta::MString | Meta::MDate => {
                                    w.wl(&format!("tempResult = this.{}.compareTo(other.{});", fname, fname));
                                }
                                Meta::MPrimitive(_) => {
                                    write_primitive_compare(w, &fname);
                                }
                                Meta::MDef(d) => match d.def_type {
                                    DefType::Record => {
                                        w.wl(&format!("tempResult = this.{}.compareTo(other.{});", fname, fname));
                                    }
                                    DefType::Enum => {
                                        w.w(&format!("tempResult = this.{}.compareTo(other.{});", fname, fname));
                                    }
                                    _ => {}
                                },
                                Meta::MExtern(e) => match e.def_type {
                                    DefType::Record => {
                                        if e.java.reference {
                                            w.wl(&format!("tempResult = this.{}.compareTo(other.{});", fname, fname));
                                        } else {
                                            write_primitive_compare(w, &fname);
                                        }
                                    }
                                    DefType::Enum => {
                                        w.w(&format!("tempResult = this.{}.compareTo(other.{});", fname, fname));
                                    }
                                    _ => {}
                                },
                                _ => {}
                            }
                        }
                        w.w("if (tempResult != 0)");
                        w.braced(|w| {
                            w.wl("return tempResult;");
                        });
                    }
                    w.wl("return 0;");
                });
            }
        });
    });
}

fn write_primitive_compare(w: &mut IndentWriter, fname: &str) {
    w.wl(&format!("if (this.{} < other.{}) {{", fname, fname));
    w.nested(|w| {
        w.wl("tempResult = -1;");
    });
    w.wl(&format!("}} else if (this.{} > other.{}) {{", fname, fname));
    w.nested(|w| {
        w.wl("tempResult = 1;");
    });
    w.wl("} else {");
    w.nested(|w| {
        w.wl("tempResult = 0;");
    });
    w.wl("}");
}

// --- Constants ---

fn write_java_constants(
    w: &mut IndentWriter,
    consts: &[Const],
    marshal: &JavaMarshal,
    id_java_enum: fn(&str) -> String,
    id_java_const: fn(&str) -> String,
    id_java_field: &dyn Fn(&str) -> String,
    idl: &[TypeDecl],
) {
    for c in consts {
        write_doc(w, &c.doc);
        if let Some(ref ann) = marshal.nullity_annotation(&c.ty) {
            w.wl(ann);
        }
        w.w(&format!(
            "public static final {} {} = ",
            marshal.field_type_from_typeref(&c.ty),
            id_java_const(&c.ident.name)
        ));
        write_java_const_value(w, &c.ty, &c.value, marshal, id_java_enum, id_java_const, id_java_field, idl);
        w.wl(";");
        w.wl_empty();
    }
}

fn write_java_const_value(
    w: &mut IndentWriter,
    ty: &TypeRef,
    value: &ConstValue,
    marshal: &JavaMarshal,
    id_java_enum: fn(&str) -> String,
    id_java_const: fn(&str) -> String,
    id_java_field: &dyn Fn(&str) -> String,
    idl: &[TypeDecl],
) {
    match value {
        ConstValue::Int(l) => {
            let field_type = marshal.field_type_from_typeref(ty).to_lowercase();
            if field_type == "long" {
                w.w(&format!("{}l", l));
            } else {
                w.w(&l.to_string());
            }
        }
        ConstValue::Float(d) => {
            let field_type = marshal.field_type_from_typeref(ty).to_lowercase();
            if field_type == "float" {
                w.w(&format!("{}f", fmt_float(*d)));
            } else {
                w.w(&fmt_float(*d));
            }
        }
        ConstValue::Bool(b) => {
            w.w(if *b { "true" } else { "false" });
        }
        ConstValue::String(s) => {
            w.w(&format!("\"{}\"", s));
        }
        ConstValue::ConstRef(name) => {
            w.w(&id_java_const(name));
        }
        ConstValue::EnumValue { ty: _enum_ty, value: val } => {
            w.w(&format!("{}.{}", marshal.typename_from_typeref(ty), id_java_enum(val)));
        }
        ConstValue::Composite(fields) => {
            if let Some(ref resolved) = ty.resolved {
                if let Meta::MDef(d) = &resolved.base {
                    if let Some(rec) = find_resolved_record(idl, &d.name) {
                        let type_name = marshal.typename_from_typeref(ty);
                        w.wl(&format!("new {}(", type_name));
                        w.increase();
                        let mut first = true;
                        for f in &rec.fields {
                            if !first {
                                w.wl(",");
                            }
                            first = false;
                            if let Some((_, val)) = fields.iter().find(|(k, _)| *k == f.ident.name) {
                                write_java_const_value(w, &f.ty, val, marshal, id_java_enum, id_java_const, id_java_field, idl);
                                w.w(&format!(" /* {} */ ", id_java_field(&f.ident.name)));
                            }
                        }
                        w.w(")");
                        w.decrease();
                    }
                }
            }
        }
    }
}

fn find_resolved_record<'a>(idl: &'a [TypeDecl], name: &str) -> Option<&'a Record> {
    idl.iter().find_map(|td| {
        if td.ident().name == name {
            if let TypeDef::Record(r) = td.body() {
                Some(r)
            } else {
                None
            }
        } else {
            None
        }
    })
}

fn java_type_params(params: &[TypeParam], spec: &djinni_ast::spec::Spec) -> String {
    if params.is_empty() {
        String::new()
    } else {
        let inner: Vec<String> = params
            .iter()
            .map(|p| (spec.java_ident_style.type_param)(&p.ident.name))
            .collect();
        format!("<{}>", inner.join(", "))
    }
}
