// vinsg
// JNIGenerator: generates JNI C++ bridge files (.hpp/.cpp), translated from JNIGenerator.scala

use std::collections::BTreeSet;
use std::path::Path;

use djinni_ast::ast::*;
use djinni_ast::meta::*;
use djinni_ast::spec::{pre_comma, q, Spec};

use crate::cpp_marshal::{CppMarshal, SymbolReference};
use crate::gen::*;
use crate::java_marshal::JavaMarshal;
use crate::jni_marshal::{to_jni_call, JniMarshal};
use crate::writer::IndentWriter;

pub fn generate_jni(ctx: &mut GeneratorContext, idl: &[TypeDecl]) {
    let jni_out = match &ctx.spec.jni_out_folder {
        Some(f) => f.clone(),
        None => return,
    };

    let intern_decls: Vec<_> = idl
        .iter()
        .filter_map(|td| {
            if let TypeDecl::Intern { ident, params, body, doc, origin } = td {
                Some((ident.clone(), params.clone(), body.clone(), doc.clone(), origin.clone()))
            } else {
                None
            }
        })
        .collect();

    for (ident, params, body, _doc, origin) in &intern_decls {
        match body {
            TypeDef::Enum(e) => {
                assert!(params.is_empty());
                generate_enum(ctx, &jni_out, origin, ident, e, idl);
            }
            TypeDef::Record(r) => {
                generate_record(ctx, &jni_out, origin, ident, params, r, idl);
            }
            TypeDef::Interface(i) => {
                generate_interface(ctx, &jni_out, origin, ident, params, i, idl);
            }
            TypeDef::ProtobufMessage(_) => {}
        }
    }
}

// --- JNIRefs ---

struct JniRefs {
    jni_hpp: BTreeSet<String>,
    jni_cpp: BTreeSet<String>,
}

impl JniRefs {
    fn new(spec: &Spec, name: &str, cpp_prefix_override: Option<&str>) -> Self {
        let mut jni_hpp = BTreeSet::new();
        let mut jni_cpp = BTreeSet::new();

        let cpp_prefix = cpp_prefix_override.unwrap_or(&spec.jni_include_cpp_prefix);
        jni_hpp.insert(format!(
            "#include {}",
            q(&format!(
                "{}{}.{}",
                cpp_prefix,
                (spec.cpp_file_ident_style)(name),
                spec.cpp_header_ext
            ))
        ));
        jni_hpp.insert(format!(
            "#include {}",
            q(&format!("{}djinni_support.hpp", spec.jni_base_lib_include_prefix))
        ));
        if let Some(ref nn_hdr) = spec.cpp_nn_header {
            jni_hpp.insert(format!("#include {}", nn_hdr));
        }

        let _ = &mut jni_cpp; // suppress unused warning

        JniRefs { jni_hpp, jni_cpp }
    }

    fn find_type_ref(&mut self, ty: &TypeRef, jni_marshal: &JniMarshal) {
        if let Some(resolved) = &ty.resolved {
            self.find_mexpr(resolved, jni_marshal);
        }
    }

    fn find_mexpr(&mut self, tm: &MExpr, jni_marshal: &JniMarshal) {
        for arg in &tm.args {
            self.find_mexpr(arg, jni_marshal);
        }
        self.find_meta(&tm.base, jni_marshal);
    }

    fn find_meta(&mut self, m: &Meta, jni_marshal: &JniMarshal) {
        for r in jni_marshal.references(m, "") {
            if let SymbolReference::ImportRef(arg) = r {
                self.jni_cpp.insert(format!("#include {}", arg));
            }
        }
    }
}

// --- Enum Generation ---

fn generate_enum(
    ctx: &mut GeneratorContext,
    folder: &Path,
    origin: &str,
    ident: &Ident,
    e: &Enum,
    _idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let jni_marshal = JniMarshal::new(spec);
    let cpp_marshal = CppMarshal::new(spec);
    let refs = JniRefs::new(spec, &ident.name, None);

    let jni_helper = jni_marshal.helper_class(&ident.name);
    let cpp_self = cpp_marshal.fq_typename_from_name(&ident.name, &TypeDef::Enum(e.clone()));
    let class_lookup = q(&jni_marshal.undecorated_typename(&ident.name, &TypeDef::Enum(e.clone())));

    let base = if e.flags { "JniFlags" } else { "JniEnum" };
    let count = normal_enum_options(e).len();
    let jni_namespace = spec.jni_namespace.clone();

    // All in header for enums
    let all_includes: BTreeSet<String> = refs.jni_hpp.iter().chain(refs.jni_cpp.iter()).cloned().collect();
    let hpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext);

    create_file_from_parts(out_files, written_files, folder, &hpp_name, |w| {
        w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!("// This file was generated by Djinni from {}", origin));
        w.wl_empty();
        w.wl("#pragma once");
        w.wl_empty();
        for inc in &all_includes {
            w.wl(inc);
        }
        w.wl_empty();
        wrap_namespace(w, &jni_namespace, |w| {
            w.w(&format!("class {} final : ::djinni::{}", jni_helper, base));
            w.braced_semi(|w| {
                w.wl_outdent("public:");
                w.wl(&format!("using CppType = {};", cpp_self));
                w.wl("using JniType = jobject;");
                w.wl_empty();
                w.wl(&format!("using Boxed = {};", jni_helper));
                w.wl_empty();
                if e.flags {
                    w.wl(&format!(
                        "static CppType toCpp(JNIEnv* jniEnv, JniType j) {{ return static_cast<CppType>(::djinni::JniClass<{}>::get().flags(jniEnv, j)); }}",
                        jni_helper
                    ));
                    w.wl(&format!(
                        "static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) {{ return ::djinni::JniClass<{}>::get().create(jniEnv, static_cast<unsigned>(c), {}); }}",
                        jni_helper, count
                    ));
                } else {
                    w.wl(&format!(
                        "static CppType toCpp(JNIEnv* jniEnv, JniType j) {{ return static_cast<CppType>(::djinni::JniClass<{}>::get().ordinal(jniEnv, j)); }}",
                        jni_helper
                    ));
                    w.wl(&format!(
                        "static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) {{ return ::djinni::JniClass<{}>::get().create(jniEnv, static_cast<jint>(c)); }}",
                        jni_helper
                    ));
                }
                w.wl_empty();
                w.wl_outdent("private:");
                w.wl(&format!("{0}() : {1}({2}) {{}}", jni_helper, base, class_lookup));
                w.wl(&format!("friend ::djinni::JniClass<{}>;", jni_helper));
            });
        });
    });
}

// --- Record Generation ---

fn generate_record(
    ctx: &mut GeneratorContext,
    folder: &Path,
    origin: &str,
    ident: &Ident,
    params: &[TypeParam],
    r: &Record,
    idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let jni_marshal = JniMarshal::new(spec);
    let cpp_marshal = CppMarshal::new(spec);

    let prefix_override: Option<&str> = if r.ext.cpp {
        Some(&spec.cpp_extended_record_include_prefix)
    } else {
        None
    };

    let super_record = get_super_record(idl, r);
    let super_fields: Vec<Field> = super_record
        .as_ref()
        .map(|sr| sr.fields.clone())
        .unwrap_or_default();
    let all_fields: Vec<Field> = [super_fields.clone(), r.fields.clone()].concat();

    let mut refs = JniRefs::new(spec, &ident.name, prefix_override);
    for f in &all_fields {
        refs.find_type_ref(&f.ty, &jni_marshal);
    }

    let jni_helper = jni_marshal.helper_class(&ident.name);
    let cpp_self = format!(
        "{}{}",
        cpp_marshal.fq_typename_from_name(&ident.name, &TypeDef::Record(r.clone())),
        cpp_type_args(params, spec)
    );

    let jni_namespace = spec.jni_namespace.clone();
    let id_java = &spec.java_ident_style;
    let id_cpp = &spec.cpp_ident_style;

    // --- HPP ---
    let class_lookup = q(&jni_marshal.undecorated_typename(&ident.name, &TypeDef::Record(r.clone())));
    let constructor_sig = q(&jni_marshal.java_method_signature(&all_fields, &None));

    let all_in_header = !params.is_empty();

    if all_in_header {
        // Template class: both prototype and body in hpp
        let all_includes: BTreeSet<String> = refs.jni_hpp.iter().chain(refs.jni_cpp.iter()).cloned().collect();
        let hpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext);

        create_file_from_parts(out_files, written_files, folder, &hpp_name, |w| {
            write_jni_file_header(w, origin, &all_includes);
            wrap_namespace(w, &jni_namespace, |w| {
                write_record_prototype(w, &jni_helper, &cpp_self, params, spec, &all_fields, &class_lookup, &constructor_sig, id_java);
                w.wl_empty();
                write_record_body(w, &jni_helper, &cpp_self, params, spec, &all_fields, id_java, id_cpp, &jni_marshal, &cpp_marshal);
            });
        });
    } else {
        // Separate hpp/cpp
        let hpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext);
        let hpp_includes: Vec<String> = refs.jni_hpp.iter().cloned().collect();

        create_file_from_parts(out_files, written_files, folder, &hpp_name, |w| {
            write_jni_file_header(w, origin, &hpp_includes.iter().cloned().collect());
            wrap_namespace(w, &jni_namespace, |w| {
                write_record_prototype(w, &jni_helper, &cpp_self, params, spec, &all_fields, &class_lookup, &constructor_sig, id_java);
            });
        });

        let cpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_ext);
        let cpp_includes: Vec<String> = refs.jni_cpp.iter().cloned().collect();
        let my_header = format!(
            "\"{}{}\"",
            spec.jni_include_prefix,
            format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext)
        );
        let my_header_include = format!("#include {}", my_header);

        create_file_from_parts(out_files, written_files, folder, &cpp_name, |w| {
            w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
            w.wl(&format!("// This file was generated by Djinni from {}", origin));
            w.wl_empty();
            w.wl(&format!("#include {}  // my header", my_header));
            for inc in &cpp_includes {
                if *inc != my_header_include {
                    w.wl(inc);
                }
            }
            w.wl_empty();
            wrap_namespace(w, &jni_namespace, |w| {
                write_record_body(w, &jni_helper, &cpp_self, params, spec, &all_fields, id_java, id_cpp, &jni_marshal, &cpp_marshal);
            });
        });
    }
}

fn write_jni_file_header(w: &mut IndentWriter, origin: &str, includes: &BTreeSet<String>) {
    w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
    w.wl(&format!("// This file was generated by Djinni from {}", origin));
    w.wl_empty();
    w.wl("#pragma once");
    w.wl_empty();
    for inc in includes {
        w.wl(inc);
    }
    w.wl_empty();
}

fn write_record_prototype(
    w: &mut IndentWriter,
    jni_helper: &str,
    cpp_self: &str,
    params: &[TypeParam],
    spec: &Spec,
    all_fields: &[Field],
    class_lookup: &str,
    constructor_sig: &str,
    id_java: &djinni_ast::ident_style::JavaIdentStyle,
) {
    write_jni_type_params(w, params, spec);
    w.w(&format!("class {} final", jni_helper));
    w.braced_semi(|w| {
        w.wl_outdent("public:");
        w.wl(&format!("using CppType = {};", cpp_self));
        w.wl("using JniType = jobject;");
        w.wl_empty();
        w.wl(&format!("using Boxed = {};", jni_helper));
        w.wl_empty();
        w.wl(&format!("~{};", jni_helper));
        w.wl_empty();
        w.wl("static CppType toCpp(JNIEnv* jniEnv, JniType j);");
        w.wl("static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);");
        w.wl_empty();
        w.wl_outdent("private:");
        w.wl(&format!("{0}();", jni_helper));
        w.wl(&format!("friend ::djinni::JniClass<{}>;", jni_helper));
        w.wl_empty();
        w.wl(&format!(
            "const ::djinni::GlobalRef<jclass> clazz {{ ::djinni::jniFindClass({}) }};",
            class_lookup
        ));
        w.wl(&format!(
            "const jmethodID jconstructor {{ ::djinni::jniGetMethodID(clazz.get(), {}, {}) }};",
            q("<init>"),
            constructor_sig
        ));
        for f in all_fields {
            let java_field_name = (id_java.field)(&f.ident.name);
            let jni_marshal = JniMarshal::new(spec);
            let java_sig = q(&jni_marshal.fq_typename_from_typeref(&f.ty));
            w.wl(&format!(
                "const jfieldID field_{} {{ ::djinni::jniGetFieldID(clazz.get(), {}, {}) }};",
                java_field_name,
                q(&java_field_name),
                java_sig
            ));
        }
    });
}

fn write_record_body(
    w: &mut IndentWriter,
    jni_helper: &str,
    cpp_self: &str,
    params: &[TypeParam],
    spec: &Spec,
    all_fields: &[Field],
    id_java: &djinni_ast::ident_style::JavaIdentStyle,
    id_cpp: &djinni_ast::ident_style::CppIdentStyle,
    jni_marshal: &JniMarshal,
    cpp_marshal: &CppMarshal,
) {
    let jni_helper_with_params = format!("{}{}", jni_helper, type_params_signature(params, spec));

    // Ctor/dtor
    write_jni_type_params(w, params, spec);
    w.wl(&format!("{}::{}() = default;", jni_helper_with_params, jni_helper));
    w.wl_empty();
    write_jni_type_params(w, params, spec);
    w.wl(&format!("{}::~{}() = default;", jni_helper_with_params, jni_helper));
    w.wl_empty();

    // fromCpp
    write_jni_type_params(w, params, spec);
    w.w(&format!(
        "auto {}::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType>",
        jni_helper_with_params
    ));
    w.braced(|w| {
        if all_fields.is_empty() {
            w.wl("(void)c; // Suppress warnings in release builds for empty records");
        }
        w.wl(&format!(
            "const auto& data = ::djinni::JniClass<{}>::get();",
            jni_helper
        ));
        let call = "auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(";
        w.w(&format!("{}data.clazz.get(), data.jconstructor", call));
        if !all_fields.is_empty() {
            w.wl(",");
            let padding = " ".repeat(call.len());
            let mut first = true;
            for f in all_fields {
                if !first {
                    w.wl(",");
                }
                first = false;
                let cpp_field_name = (id_cpp.field)(&f.ident.name);
                let param = if let Some(ref resolved) = f.ty.resolved {
                    jni_marshal.from_cpp(
                        resolved,
                        &cpp_marshal.maybe_move(&format!("c.{}", cpp_field_name), &f.ty),
                    )
                } else {
                    format!("c.{}", cpp_field_name)
                };
                w.w(&format!("{}::djinni::get({})", padding, param));
            }
            w.w(")}");
        } else {
            w.w(")}");
        }
        w.wl(";");
        w.wl("::djinni::jniExceptionCheck(jniEnv);");
        w.wl("return r;");
    });
    w.wl_empty();

    // toCpp
    write_jni_type_params(w, params, spec);
    w.w(&format!(
        "auto {}::toCpp(JNIEnv* jniEnv, JniType j) -> CppType",
        jni_helper_with_params
    ));
    w.braced(|w| {
        w.wl(&format!(
            "::djinni::JniLocalScope jscope(jniEnv, {});",
            all_fields.len() + 1
        ));
        w.wl("assert(j != nullptr);");
        if all_fields.is_empty() {
            w.wl("(void)j; // Suppress warnings in release builds for empty records");
        } else {
            w.wl(&format!(
                "const auto& data = ::djinni::JniClass<{}>::get();",
                jni_helper
            ));
        }
        w.wl(&format!("{} model;", cpp_self));
        for f in all_fields {
            let java_field_name = (id_java.field)(&f.ident.name);
            let field_id = format!("data.field_{}", java_field_name);
            let jni_field_access = to_jni_call(&f.ty, |jt| {
                format!("jniEnv->Get{}Field(j, {})", jt, field_id)
            });
            let to_cpp = if let Some(ref resolved) = f.ty.resolved {
                jni_marshal.to_cpp(resolved, &jni_field_access)
            } else {
                jni_field_access
            };
            w.wl(&format!("model.{} = {};", java_field_name, to_cpp));
        }
        w.wl("return model;");
    });
}

// --- Interface Generation ---

fn generate_interface(
    ctx: &mut GeneratorContext,
    folder: &Path,
    origin: &str,
    ident: &Ident,
    type_params: &[TypeParam],
    i: &Interface,
    _idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let jni_marshal = JniMarshal::new(spec);
    let cpp_marshal = CppMarshal::new(spec);
    let java_marshal = JavaMarshal::new(spec, false);

    let mut refs = JniRefs::new(spec, &ident.name, None);

    if let Some(ref x) = spec.jni_function_prologue_file {
        refs.jni_cpp.insert(format!("#include {}", q(x)));
    }

    for m in &i.methods {
        for p in &m.params {
            refs.find_type_ref(&p.ty, &jni_marshal);
        }
        if let Some(ref ret) = m.ret {
            refs.find_type_ref(ret, &jni_marshal);
        }
    }
    for c in &i.consts {
        refs.find_type_ref(&c.ty, &jni_marshal);
    }

    let jni_self = jni_marshal.helper_class(&ident.name);
    let cpp_self = format!(
        "{}{}",
        cpp_marshal.fq_typename_from_name(&ident.name, &TypeDef::Interface(i.clone())),
        cpp_type_args(type_params, spec)
    );
    let class_lookup = jni_marshal.undecorated_typename(&ident.name, &TypeDef::Interface(i.clone()));
    let base_type = format!("::djinni::JniInterface<{}, {}>", cpp_self, jni_self);
    let jni_namespace = spec.jni_namespace.clone();
    let id_java = &spec.java_ident_style;
    let id_cpp = &spec.cpp_ident_style;

    let all_in_header = !type_params.is_empty();

    let write_proto = |w: &mut IndentWriter| {
        write_jni_type_params(w, type_params, spec);
        w.w(&format!("class {} final : {}", jni_self, base_type));
        w.braced_semi(|w| {
            w.wl_outdent("public:");
            match &spec.cpp_nn_type {
                Some(nn_ptr) => {
                    w.wl(&format!("using CppType = {}<{}>;", nn_ptr, cpp_self));
                    w.wl(&format!("using CppOptType = std::shared_ptr<{}>;", cpp_self));
                }
                None => {
                    w.wl(&format!("using CppType = std::shared_ptr<{}>;", cpp_self));
                    w.wl(&format!("using CppOptType = std::shared_ptr<{}>;", cpp_self));
                }
            }
            w.wl("using JniType = jobject;");
            w.wl_empty();
            w.wl(&format!("using Boxed = {};", jni_self));
            w.wl_empty();
            w.wl(&format!("~{};", jni_self));
            w.wl_empty();

            if spec.cpp_nn_type.is_some() {
                let nn_check_expr = |expr: &str| -> String {
                    match &spec.cpp_nn_check_expression {
                        Some(check) => format!("{}({})", check, expr),
                        None => expr.to_string(),
                    }
                };
                w.w("static CppType toCpp(JNIEnv* jniEnv, JniType j)");
                w.braced_semi(|w| {
                    w.wl(&format!(
                        "DJINNI_ASSERT_MSG(j, jniEnv, \"{}::fromCpp requires a non-null Java object\");",
                        jni_self
                    ));
                    w.wl(&format!(
                        "return {};",
                        nn_check_expr(&format!("::djinni::JniClass<{}>::get()._fromJava(jniEnv, j)", jni_self))
                    ));
                });
            } else {
                w.wl(&format!(
                    "static CppType toCpp(JNIEnv* jniEnv, JniType j) {{ return ::djinni::JniClass<{}>::get()._fromJava(jniEnv, j); }}",
                    jni_self
                ));
            }
            w.wl(&format!(
                "static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) {{ return {{jniEnv, ::djinni::JniClass<{}>::get()._toJava(jniEnv, c)}}; }}",
                jni_self
            ));
            w.wl("static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }");
            w.wl_empty();
            w.wl_outdent("private:");
            w.wl(&format!("{0}();", jni_self));
            w.wl(&format!("friend ::djinni::JniClass<{}>;", jni_self));
            w.wl(&format!("friend {};", base_type));
            w.wl_empty();

            if i.ext.java {
                w.w(&format!(
                    "class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public {}",
                    cpp_self
                ));
                w.braced_semi(|w| {
                    w.wl_outdent("public:");
                    w.wl("JavaProxy(JniType j);");
                    w.wl("~JavaProxy();");
                    w.wl_empty();
                    for m in &i.methods {
                        let ret = cpp_marshal.fq_return_type(m.ret.as_ref());
                        let params: Vec<String> = m.params.iter().map(|p| {
                            format!(
                                "{} {}",
                                cpp_marshal.fq_param_type_from_typeref(&p.ty),
                                (id_cpp.local)(&p.ident.name)
                            )
                        }).collect();
                        w.wl(&format!("{} {}({}) override;", ret, (id_cpp.method)(&m.ident.name), params.join(", ")));
                    }
                    w.wl_empty();
                    w.wl_outdent("private:");
                    w.wl(&format!(
                        "friend ::djinni::JniInterface<{}, {}>;",
                        cpp_self,
                        with_ns(Some(&jni_namespace), &jni_self)
                    ));
                });
                w.wl_empty();
                w.wl(&format!(
                    "const ::djinni::GlobalRef<jclass> clazz {{ ::djinni::jniFindClass({}) }};",
                    q(&class_lookup)
                ));
                for m in &i.methods {
                    let java_method_name = (id_java.method)(&m.ident.name);
                    let java_method_sig = q(&jni_marshal.java_method_signature(&m.params, &m.ret));
                    w.wl(&format!(
                        "const jmethodID method_{} {{ ::djinni::jniGetMethodID(clazz.get(), {}, {}) }};",
                        java_method_name,
                        q(&java_method_name),
                        java_method_sig
                    ));
                }
            }
        });

        if spec.jni_use_on_load && i.ext.cpp {
            let (static_methods, proxy_methods): (Vec<_>, Vec<_>) = i.methods.iter().partition(|m| m.is_static);
            w.wl(&format!(
                "extern const JNINativeMethod {}ProxyRecords[{}];",
                jni_self,
                proxy_methods.len() + 1
            ));
            if !static_methods.is_empty() {
                w.wl(&format!(
                    "extern const JNINativeMethod {}StaticRecords[{}];",
                    jni_self,
                    static_methods.len()
                ));
            }
        }
    };

    let write_body = |w: &mut IndentWriter| {
        let base_class_param = if i.ext.cpp {
            q(&format!("{}$CppProxy", class_lookup))
        } else {
            String::new()
        };
        let jni_self_with_params = format!("{}{}", jni_self, type_params_signature(type_params, spec));

        write_jni_type_params(w, type_params, spec);
        w.wl(&format!("{}::{}() : {}({}) {{}}", jni_self_with_params, jni_self, base_type, base_class_param));
        w.wl_empty();
        write_jni_type_params(w, type_params, spec);
        w.wl(&format!("{}::~{}() = default;", jni_self_with_params, jni_self));
        w.wl_empty();

        if i.ext.java {
            write_jni_type_params(w, type_params, spec);
            w.wl(&format!(
                "{}::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) {{ }}",
                jni_self_with_params
            ));
            w.wl_empty();
            write_jni_type_params(w, type_params, spec);
            w.wl(&format!("{}::JavaProxy::~JavaProxy() = default;", jni_self_with_params));
            w.wl_empty();

            for m in &i.methods {
                let ret = cpp_marshal.fq_return_type(m.ret.as_ref());
                let params: Vec<String> = m.params.iter().map(|p| {
                    format!(
                        "{} c_{}",
                        cpp_marshal.fq_param_type_from_typeref(&p.ty),
                        (id_cpp.local)(&p.ident.name)
                    )
                }).collect();
                write_jni_type_params(w, type_params, spec);
                w.w(&format!(
                    "{} {}::JavaProxy::{}({})",
                    ret, jni_self_with_params, (id_cpp.method)(&m.ident.name), params.join(", ")
                ));
                w.braced(|w| {
                    let java_method_name = (id_java.method)(&m.ident.name);
                    if let Some(ref x) = spec.jni_function_prologue_file {
                        let _ = x;
                        w.wl(&format!(
                            "DJINNI_FUNCTION_PROLOGUE(\"{}.{}\");",
                            ident.name, java_method_name
                        ));
                    }
                    w.wl("auto jniEnv = ::djinni::jniGetThreadEnv();");
                    w.wl("::djinni::JniLocalScope jscope(jniEnv, 10);");
                    w.wl(&format!(
                        "const auto& data = ::djinni::JniClass<{}>::get();",
                        with_ns(Some(&jni_namespace), &jni_self)
                    ));

                    let call_method = match &m.ret {
                        None => format!("jniEnv->CallVoidMethod("),
                        Some(r) => {
                            let jni_call = to_jni_call(r, |jt| format!("jniEnv->Call{}Method(", jt));
                            format!("auto jret = {}", jni_call)
                        }
                    };
                    w.w(&call_method);
                    w.w(&format!("Handle::get().get(), data.method_{}", java_method_name));
                    if !m.params.is_empty() {
                        w.wl(",");
                        let padding = " ".repeat(call_method.len());
                        let mut first = true;
                        for p in &m.params {
                            if !first {
                                w.wl(",");
                            }
                            first = false;
                            let param = if let Some(ref resolved) = p.ty.resolved {
                                jni_marshal.from_cpp(
                                    resolved,
                                    &cpp_marshal.maybe_move(
                                        &format!("c_{}", (id_cpp.local)(&p.ident.name)),
                                        &p.ty,
                                    ),
                                )
                            } else {
                                format!("c_{}", (id_cpp.local)(&p.ident.name))
                            };
                            w.w(&format!("{}::djinni::get({})", padding, param));
                        }
                        w.w(")");
                    } else {
                        w.w(")");
                    }
                    w.wl(";");
                    w.wl("::djinni::jniExceptionCheck(jniEnv);");
                    if let Some(ref ret_ty) = m.ret {
                        if let Some(ref resolved) = ret_ty.resolved {
                            w.wl(&format!("return {};", jni_marshal.to_cpp(resolved, "jret")));
                        }
                    }
                });
            }
        }

        if i.ext.cpp {
            // Generate CEXPORT functions
            let class_ident_munged = java_marshal
                .fq_typename_from_name(&ident.name, &TypeDef::Interface(i.clone()))
                .replace('_', "_1")
                .replace('.', "_");
            let prefix = format!("Java_{}", class_ident_munged);

            let method_name_fn = |name: &str, is_static: bool| -> String {
                let munged = name.replace('_', "_1");
                if is_static {
                    format!("{}_{}", prefix, munged)
                } else {
                    format!("{}_00024CppProxy_{}", prefix, munged)
                }
            };

            // nativeDestroy
            let export_kw = if spec.jni_use_on_load { "static" } else { "CJNIEXPORT" };
            w.wl_empty();
            w.wl(&format!(
                "{} void JNICALL {}(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)",
                export_kw,
                method_name_fn("nativeDestroy", false)
            ));
            w.braced(|w| {
                w.w("try");
                w.braced_end(" JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )", |w| {
                    if spec.jni_function_prologue_file.is_some() {
                        w.wl(&format!(
                            "DJINNI_FUNCTION_PROLOGUE(\"{}.nativeDestroy\");",
                            ident.name
                        ));
                    }
                    w.wl(&format!("delete reinterpret_cast<::djinni::CppProxyHandle<{}>*>(nativeRef);", cpp_self));
                });
            });

            for m in i.methods.iter().filter(|m| !m.is_static || m.lang.java) {
                let native_addon = if m.is_static { "" } else { "native_" };
                let jni_ret_type = jni_marshal.return_type(&m.ret);
                let param_list: Vec<String> = m.params.iter().map(|p| {
                    format!(
                        "{} j_{}",
                        jni_marshal.param_type_from_typeref(&p.ty),
                        (id_java.local)(&p.ident.name)
                    )
                }).collect();
                let param_list_str = param_list.join(", ");
                let zero = if m.ret.is_some() { "0 /* value doesn't matter */" } else { "" };
                let func_name = method_name_fn(
                    &format!("{}{}", native_addon, (id_java.method)(&m.ident.name)),
                    m.is_static,
                );

                w.wl_empty();
                if m.is_static {
                    w.wl(&format!(
                        "{} {} JNICALL {}(JNIEnv* jniEnv, jobject /*this*/{})",
                        export_kw, jni_ret_type, func_name,
                        pre_comma(&param_list_str)
                    ));
                } else {
                    w.wl(&format!(
                        "{} {} JNICALL {}(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef{})",
                        export_kw, jni_ret_type, func_name,
                        pre_comma(&param_list_str)
                    ));
                }
                w.braced(|w| {
                    w.w("try");
                    w.braced_end(&format!(" JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, {})", zero), |w| {
                        if spec.jni_function_prologue_file.is_some() {
                            w.wl(&format!(
                                "DJINNI_FUNCTION_PROLOGUE(\"{}.{}\");",
                                ident.name,
                                (id_java.method)(&m.ident.name)
                            ));
                        }
                        if !m.is_static {
                            w.wl(&format!(
                                "const auto& ref = ::djinni::objectFromHandleAddress<{}>(nativeRef);",
                                cpp_self
                            ));
                        }
                        // NN check for interface params
                        for p in &m.params {
                            if let Some(ref resolved) = p.ty.resolved {
                                if is_interface(resolved) && spec.cpp_nn_check_expression.is_some() {
                                    let param_name = (id_java.local)(&p.ident.name);
                                    let java_method_name = (id_java.method)(&m.ident.name);
                                    let java_params: Vec<String> = m.params.iter().map(|pp| {
                                        format!(
                                            "{} {}",
                                            java_marshal.fq_param_type_from_mexpr(pp.ty.resolved.as_ref().unwrap()),
                                            (id_java.local)(&pp.ident.name)
                                        )
                                    }).collect();
                                    let function_string = format!(
                                        "{}#{}({})",
                                        java_marshal.fq_typename_from_name(&ident.name, &TypeDef::Interface(i.clone())),
                                        java_method_name,
                                        java_params.join(", ")
                                    );
                                    w.wl(&format!(
                                        "DJINNI_ASSERT_MSG(j_{}, jniEnv, \"Got unexpected null parameter '{}' to function {}\");",
                                        param_name, param_name, function_string
                                    ));
                                }
                            }
                        }

                        let method_name_cpp = (id_cpp.method)(&m.ident.name);
                        let ret_prefix = if m.ret.is_some() { "auto r = " } else { "" };
                        let call = if m.is_static {
                            format!("{}::{}(", cpp_self, method_name_cpp)
                        } else {
                            format!("ref->{}(", method_name_cpp)
                        };

                        write_aligned_call(w, &format!("{}{}", ret_prefix, call), &m.params, ",", ")", |p| {
                            if let Some(ref resolved) = p.ty.resolved {
                                jni_marshal.to_cpp(resolved, &format!("j_{}", (id_java.local)(&p.ident.name)))
                            } else {
                                format!("j_{}", (id_java.local)(&p.ident.name))
                            }
                        });
                        w.wl(";");
                        if let Some(ref ret_ty) = m.ret {
                            if let Some(ref resolved) = ret_ty.resolved {
                                w.wl(&format!(
                                    "return ::djinni::release({});",
                                    jni_marshal.from_cpp(
                                        resolved,
                                        &cpp_marshal.maybe_move("r", ret_ty),
                                    )
                                ));
                            }
                        }
                    });
                });
            }

            // JNINativeMethod records for onLoad
            if spec.jni_use_on_load {
                let (static_methods, proxy_methods): (Vec<_>, Vec<_>) = i.methods.iter().partition(|m| m.is_static);

                write_native_method_record(w, &jni_self, false, &proxy_methods, &method_name_fn, &jni_marshal, id_java, &ident.name);
                if !static_methods.is_empty() {
                    write_native_method_record(w, &jni_self, true, &static_methods, &method_name_fn, &jni_marshal, id_java, &ident.name);
                }
            }
        }
    };

    if all_in_header {
        let all_includes: BTreeSet<String> = refs.jni_hpp.iter().chain(refs.jni_cpp.iter()).cloned().collect();
        let hpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext);
        create_file_from_parts(out_files, written_files, folder, &hpp_name, |w| {
            write_jni_file_header(w, origin, &all_includes);
            wrap_namespace(w, &jni_namespace, |w| {
                write_proto(w);
                w.wl_empty();
                write_body(w);
            });
        });
    } else {
        let hpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext);
        create_file_from_parts(out_files, written_files, folder, &hpp_name, |w| {
            write_jni_file_header(w, origin, &refs.jni_hpp);
            wrap_namespace(w, &jni_namespace, |w| {
                write_proto(w);
            });
        });

        let cpp_name = format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_ext);
        let my_header = format!(
            "\"{}{}\"",
            spec.jni_include_prefix,
            format!("{}.{}", (spec.jni_file_ident_style)(&ident.name), spec.cpp_header_ext)
        );
        let my_header_include = format!("#include {}", my_header);

        create_file_from_parts(out_files, written_files, folder, &cpp_name, |w| {
            w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
            w.wl(&format!("// This file was generated by Djinni from {}", origin));
            w.wl_empty();
            w.wl(&format!("#include {}  // my header", my_header));
            for inc in &refs.jni_cpp {
                if *inc != my_header_include {
                    w.wl(inc);
                }
            }
            w.wl_empty();
            wrap_namespace(w, &jni_namespace, |w| {
                write_body(w);
            });
        });
    }
}

fn write_native_method_record(
    w: &mut IndentWriter,
    jni_self: &str,
    is_static: bool,
    methods: &[&Method],
    method_name_fn: &dyn Fn(&str, bool) -> String,
    jni_marshal: &JniMarshal,
    id_java: &djinni_ast::ident_style::JavaIdentStyle,
    _type_name: &str,
) {
    let identifier = format!(
        "{}{}Records",
        jni_self,
        if is_static { "Static" } else { "Proxy" }
    );
    w.wl(&format!("const JNINativeMethod {} = ", identifier));
    w.braced_semi(|w| {
        if !is_static {
            w.braced_end(",", |w| {
                w.wl(&jni_native_method("nativeDestroy", "(J)V", &method_name_fn("nativeDestroy", false)));
            });
        }
        for m in methods {
            let native_addon = if m.is_static { "" } else { "native_" };
            let java_name = format!("{}{}", native_addon, (id_java.method)(&m.ident.name));
            let function_name = method_name_fn(&java_name, m.is_static);
            w.braced_end(",", |w| {
                let mut signature = jni_marshal.java_method_signature(&m.params, &m.ret);
                if !is_static {
                    signature = signature.replacen('(', "(J", 1);
                }
                w.wl(&jni_native_method(
                    &format!("{}{}", native_addon, (id_java.method)(&m.ident.name)),
                    &signature,
                    &function_name,
                ));
            });
        }
    });
}

fn jni_native_method(java_method: &str, java_sig: &str, pointer: &str) -> String {
    format!(
        "const_cast<char*>({}), const_cast<char*>({}), reinterpret_cast<void*>({}),",
        q(java_method), q(java_sig), pointer
    )
}

// --- Helpers ---

fn write_jni_type_params(w: &mut IndentWriter, params: &[TypeParam], spec: &Spec) {
    if params.is_empty() {
        return;
    }
    let inner: Vec<String> = params
        .iter()
        .map(|p| format!("typename {}", (spec.jni_class_ident_style)(&p.ident.name)))
        .collect();
    w.wl(&format!("template {}", format!("<{}>", inner.join(", "))));
}

fn type_params_signature(params: &[TypeParam], spec: &Spec) -> String {
    if params.is_empty() {
        String::new()
    } else {
        let inner: Vec<String> = params
            .iter()
            .map(|p| (spec.jni_class_ident_style)(&p.ident.name))
            .collect();
        format!("<{}>", inner.join(", "))
    }
}

fn cpp_type_args(params: &[TypeParam], spec: &Spec) -> String {
    if params.is_empty() {
        String::new()
    } else {
        let inner: Vec<String> = params
            .iter()
            .map(|p| (spec.cpp_ident_style.type_param)(&p.ident.name))
            .collect();
        format!("<{}>", inner.join(", "))
    }
}
