// vinsg
// ObjcGenerator: generates Objective-C header and implementation files,
// translated from ObjcGenerator.scala and BaseObjcGenerator.scala

use std::collections::BTreeSet;

use djinni_ast::ast::*;
use djinni_ast::ident_style::camel_upper;
use djinni_ast::meta::*;
use djinni_ast::spec::{q, Spec};

use crate::cpp_marshal::SymbolReference;
use crate::gen::*;
use crate::objc_marshal::{use_protocol, ObjcMarshal};
use crate::writer::IndentWriter;

/// Format a float like Scala's Double.toString
fn fmt_float(d: f64) -> String {
    let s = d.to_string();
    if s.contains('.') || s.contains('E') || s.contains('e') {
        s
    } else {
        format!("{}.0", s)
    }
}

// --- ObjcRefs ---

struct ObjcRefs {
    header: BTreeSet<String>,
    body: BTreeSet<String>,
}

impl ObjcRefs {
    fn new() -> Self {
        Self {
            header: BTreeSet::new(),
            body: BTreeSet::new(),
        }
    }

    fn find_type_ref(&mut self, ty: &TypeRef, marshal: &ObjcMarshal) {
        if let Some(resolved) = &ty.resolved {
            self.find_mexpr(resolved, marshal);
        }
    }

    fn find_mexpr(&mut self, tm: &MExpr, marshal: &ObjcMarshal) {
        for arg in &tm.args {
            self.find_mexpr(arg, marshal);
        }
        self.find_meta(&tm.base, marshal);
    }

    fn find_meta(&mut self, m: &Meta, marshal: &ObjcMarshal) {
        for r in marshal.references(m) {
            match r {
                SymbolReference::ImportRef(arg) => {
                    self.header.insert(format!("#import {}", arg));
                }
                SymbolReference::DeclRef { decl, .. } => {
                    self.header.insert(decl);
                }
            }
        }
    }
}

// --- write ObjC file ---

fn write_objc_file<F>(
    out_files: &mut Vec<std::path::PathBuf>,
    written_files: &mut std::collections::HashMap<String, String>,
    folder: &std::path::Path,
    file_name: &str,
    origin: &str,
    refs: &BTreeSet<String>,
    f: F,
) where
    F: FnOnce(&mut IndentWriter),
{
    create_file_from_parts(out_files, written_files, folder, file_name, |w| {
        w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!(
            "// This file was generated by Djinni from {}",
            origin
        ));
        w.wl_empty();
        if !refs.is_empty() {
            for s in refs {
                // Ignore the ! in front of each line; used to put own headers to the top
                if s.starts_with('!') {
                    w.wl(&s[1..]);
                } else {
                    w.wl(s);
                }
            }
            w.wl_empty();
        }
        f(w);
    });
}

// --- aligned ObjC call ---

fn write_aligned_objc_call<F>(
    w: &mut IndentWriter,
    call: &str,
    params: &[Field],
    end: &str,
    f: F,
) where
    F: Fn(&Field) -> (String, String),
{
    w.w(call);
    let mut first = true;
    for p in params {
        let (name, value) = f(p);
        if first {
            first = false;
        } else {
            w.wl_empty();
            let padding = if call.len() > name.len() {
                call.len() - name.len()
            } else {
                0
            };
            w.w(&" ".repeat(padding));
            w.w(&name);
        }
        w.w(&format!(":{}", value));
    }
    w.w(end);
}

// --- BaseObjcGenerator: const generation ---

fn write_objc_const_variable_decl(
    w: &mut IndentWriter,
    c: &Const,
    s: &str,
    marshal: &ObjcMarshal,
    spec: &Spec,
) {
    let tm = c.ty.resolved.as_ref().expect("TypeRef not resolved");
    let nullability = marshal
        .nullability(tm)
        .map(|n| format!(" __{}", n))
        .unwrap_or_default();
    let td = format!("{}{}", marshal.fq_field_type(tm), nullability);
    w.w(&format!(
        "{} const {}{}",
        td,
        s,
        (spec.objc_ident_style.const_)(&c.ident.name)
    ));
}

fn find_resolved_record<'a>(idl: &'a [TypeDecl], name: &str) -> Option<&'a Record> {
    idl.iter().find_map(|td| {
        if td.ident().name == name {
            if let TypeDef::Record(r) = td.body() {
                Some(r)
            } else {
                None
            }
        } else {
            None
        }
    })
}

fn write_objc_const_value(
    w: &mut IndentWriter,
    ty: &TypeRef,
    v: &ConstValue,
    self_name: &str,
    marshal: &ObjcMarshal,
    spec: &Spec,
    idl: &[TypeDecl],
) {
    let tm = ty.resolved.as_ref().expect("TypeRef not resolved");
    let (_, need_ref) = marshal.to_objc_type(tm, false);
    let boxed_prefix = if need_ref { "@" } else { "" };

    match v {
        ConstValue::Int(l) => { w.w(&format!("{}{}", boxed_prefix, l)); }
        ConstValue::Float(d) => {
            let field_type = marshal.field_type_mexpr(tm);
            if field_type == "float" {
                w.w(&format!("{}{}f", boxed_prefix, fmt_float(*d)));
            } else {
                w.w(&format!("{}{}", boxed_prefix, fmt_float(*d)));
            }
        }
        ConstValue::Bool(b) => {
            w.w(&format!("{}{}", boxed_prefix, if *b { "YES" } else { "NO" }));
        }
        ConstValue::String(s) => { w.w(&format!("@{}", s)); }
        ConstValue::EnumValue { ty: _, value } => {
            let type_name = marshal.typename_from_mexpr(tm);
            w.w(&format!(
                "{}{}",
                type_name,
                (spec.objc_ident_style.enum_)(value)
            ));
        }
        ConstValue::Composite(fields) => {
            // Record constant — use find_resolved_record for resolved field types
            if let Meta::MDef(d) = &tm.base {
                if let Some(record) = find_resolved_record(idl, &d.name) {
                    let type_name = marshal.typename_from_mexpr(tm);
                    let head = &record.fields[0];
                    w.w(&format!(
                        "[[{} alloc] initWith{}:",
                        type_name,
                        camel_upper(&head.ident.name)
                    ));
                    if let Some((_, val)) = fields.iter().find(|(k, _)| *k == head.ident.name) {
                        write_objc_const_value(w, &head.ty, val, self_name, marshal, spec, idl);
                    }
                    w.nested_n(2, |w| {
                        for f in record.fields.iter().skip(1) {
                            w.wl_empty();
                            w.w(&format!(
                                "{}:",
                                (spec.objc_ident_style.field)(&f.ident.name)
                            ));
                            if let Some((_, val)) =
                                fields.iter().find(|(k, _)| *k == f.ident.name)
                            {
                                write_objc_const_value(w, &f.ty, val, self_name, marshal, spec, idl);
                            }
                        }
                    });
                    w.w("]");
                }
            }
        }
    }
}

enum ObjcConstantType {
    ConstVariable,
    ConstMethod,
}

fn generate_objc_constants(
    w: &mut IndentWriter,
    consts: &[Const],
    self_name: &str,
    gen_type: ObjcConstantType,
    marshal: &ObjcMarshal,
    spec: &Spec,
    idl: &[TypeDecl],
) {
    match gen_type {
        ObjcConstantType::ConstVariable => {
            for c in consts.iter().filter(|c| marshal.can_be_const_variable(c)) {
                w.wl_empty();
                write_objc_const_variable_decl(w, c, self_name, marshal, spec);
                w.w(" = ");
                write_objc_const_value(w, &c.ty, &c.value, self_name, marshal, spec, idl);
                w.wl(";");
            }
        }
        ObjcConstantType::ConstMethod => {
            for c in consts.iter().filter(|c| !marshal.can_be_const_variable(c)) {
                let tm = c.ty.resolved.as_ref().expect("TypeRef not resolved");
                let nullability = marshal
                    .nullability(tm)
                    .map(|n| format!(" __{}", n))
                    .unwrap_or_default();
                let ret = format!("{}{}", marshal.fq_field_type(tm), nullability);
                let decl = format!(
                    "+ ({}){}",
                    ret,
                    (spec.objc_ident_style.method)(&c.ident.name)
                );
                write_aligned_objc_call(w, &decl, &[], "", |_| (String::new(), String::new()));
                w.wl_empty();

                w.braced(|w| {
                    let static_var = format!("s_{}", (spec.objc_ident_style.method)(&c.ident.name));
                    w.w(&format!(
                        "static {} const {} = ",
                        marshal.fq_field_type(tm),
                        static_var
                    ));
                    write_objc_const_value(w, &c.ty, &c.value, self_name, marshal, spec, idl);
                    w.wl(";");
                    w.wl(&format!("return {};", static_var));
                });
                w.wl_empty();
            }
        }
    }
}

fn write_objc_const_meth_decl(w: &mut IndentWriter, c: &Const, marshal: &ObjcMarshal, spec: &Spec) {
    let tm = c.ty.resolved.as_ref().expect("TypeRef not resolved");
    let nullability = marshal
        .nullability(tm)
        .map(|n| format!(" __{}", n))
        .unwrap_or_default();
    let ret = format!("{}{}", marshal.fq_field_type(tm), nullability);
    let decl = format!(
        "+ ({}){}",
        ret,
        (spec.objc_ident_style.method)(&c.ident.name)
    );
    write_aligned_objc_call(w, &decl, &[], ";", |_| (String::new(), String::new()));
}

// --- Main generator entry point ---

pub fn generate_objc(ctx: &mut GeneratorContext, idl: &[TypeDecl]) {
    let objc_out = match &ctx.spec.objc_out_folder {
        Some(f) => f.clone(),
        None => return,
    };

    let intern_decls: Vec<_> = idl
        .iter()
        .filter_map(|td| {
            if let TypeDecl::Intern {
                ident,
                params,
                body,
                doc,
                origin,
            } = td
            {
                Some((
                    ident.clone(),
                    params.clone(),
                    body.clone(),
                    doc.clone(),
                    origin.clone(),
                ))
            } else {
                None
            }
        })
        .collect();

    for (ident, params, body, doc, origin) in &intern_decls {
        match body {
            TypeDef::Enum(e) => {
                assert!(params.is_empty());
                generate_enum(ctx, &objc_out, origin, ident, doc, e);
            }
            TypeDef::Record(r) => {
                generate_record(ctx, &objc_out, origin, ident, doc, params, r, idl);
            }
            TypeDef::Interface(i) => {
                generate_interface(ctx, &objc_out, origin, ident, doc, params, i, idl);
            }
            TypeDef::ProtobufMessage(_) => {}
        }
    }
}

// --- Enum ---

fn generate_enum(
    ctx: &mut GeneratorContext,
    objc_out: &std::path::Path,
    origin: &str,
    ident: &Ident,
    doc: &Doc,
    e: &Enum,
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let marshal = ObjcMarshal::new(spec);
    let id_objc = &spec.objc_ident_style;

    let mut refs = BTreeSet::new();
    refs.insert("#import <Foundation/Foundation.h>".to_string());

    let self_name = marshal.typename_from_name(&ident.name, &TypeDef::Enum(e.clone()));

    let file_name = marshal.header_name(&ident.name);
    write_objc_file(out_files, written_files, objc_out, &file_name, origin, &refs, |w| {
        write_doc(w, doc);
        if e.flags {
            w.wl(&format!("typedef NS_OPTIONS(NSInteger, {})", self_name));
        } else if spec.objc_closed_enums {
            w.wl(&format!("typedef NS_CLOSED_ENUM(NSInteger, {})", self_name));
        } else {
            w.wl(&format!("typedef NS_ENUM(NSInteger, {})", self_name));
        }
        w.braced_semi(|w| {
            let ident_fn = |name: &str| -> String {
                format!("{}{}", self_name, (id_objc.enum_)(name))
            };
            write_enum_option_none(w, e, &ident_fn, "=");
            write_enum_options(w, e, &ident_fn, "=");
            write_enum_option_all(w, e, &ident_fn, "=");
        });
    });
}

// --- Interface ---

fn generate_interface(
    ctx: &mut GeneratorContext,
    objc_out: &std::path::Path,
    origin: &str,
    ident: &Ident,
    doc: &Doc,
    _params: &[TypeParam],
    i: &Interface,
    idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let marshal = ObjcMarshal::new(spec);
    let id_objc = &spec.objc_ident_style;

    let mut refs = ObjcRefs::new();
    for m in &i.methods {
        for p in &m.params {
            refs.find_type_ref(&p.ty, &marshal);
        }
        if let Some(ret) = &m.ret {
            refs.find_type_ref(ret, &marshal);
        }
    }
    for c in &i.consts {
        refs.find_type_ref(&c.ty, &marshal);
    }

    let self_name = marshal.typename_from_name(&ident.name, &TypeDef::Interface(i.clone()));

    refs.header.insert("#import <Foundation/Foundation.h>".to_string());

    let write_objc_func_decl = |w: &mut IndentWriter, method: &Method| {
        let label = if method.is_static { "+" } else { "-" };
        let ret = marshal.return_type(method.ret.as_ref());
        let decl = format!(
            "{} ({}){}", label, ret, (id_objc.method)(&method.ident.name)
        );
        write_aligned_objc_call(
            w,
            &decl,
            &method.params,
            "",
            |p| {
                (
                    (id_objc.field)(&p.ident.name),
                    format!(
                        "({}){}",
                        marshal.param_type(&p.ty),
                        (id_objc.local)(&p.ident.name)
                    ),
                )
            },
        );
    };

    // Generate protocol implementation header if needed
    if !i.ext.objc && spec.objc_gen_protocol {
        if i.methods.iter().any(|m| m.is_static) {
            let protocol_header = format!(
                "#import {}",
                q(&format!(
                    "{}{}",
                    spec.objc_include_prefix,
                    marshal.header_name(&ident.name)
                ))
            );
            let mut impl_refs = BTreeSet::new();
            impl_refs.insert(protocol_header);
            let impl_header_name = marshal.impl_header_name(&ident.name);
            write_objc_file(
                out_files,
                written_files,
                objc_out,
                &impl_header_name,
                origin,
                &impl_refs,
                |w| {
                    w.wl(&format!("@interface {} : NSObject<{}>", self_name, self_name));
                    for m in &i.methods {
                        if m.is_static && m.lang.objc {
                            w.wl_empty();
                            write_method_doc(w, &m.doc, &m.params, id_objc.local);
                            write_objc_func_decl(w, m);
                            w.wl(";");
                        }
                    }
                    w.wl_empty();
                    w.wl("@end");
                },
            );
        }
    }

    // Generate the header file
    let file_name = marshal.header_name(&ident.name);
    write_objc_file(out_files, written_files, objc_out, &file_name, origin, &refs.header, |w| {
        for c in &i.consts {
            if marshal.can_be_const_variable(c) {
                write_doc(w, &c.doc);
                w.w("extern ");
                write_objc_const_variable_decl(w, c, &self_name, &marshal, spec);
                w.wl(";");
            }
        }

        w.wl_empty();
        write_doc(w, doc);
        if use_protocol(&i.ext, spec) {
            let base_protocol = if spec.objc_strict_protocol {
                " <NSObject>"
            } else {
                ""
            };
            w.wl(&format!("@protocol {}{}", self_name, base_protocol));
        } else {
            w.wl(&format!("@interface {} : NSObject", self_name));
        }

        for m in &i.methods {
            if !m.is_static || (!spec.objc_gen_protocol && m.lang.objc) {
                w.wl_empty();
                write_method_doc(w, &m.doc, &m.params, id_objc.local);
                write_objc_func_decl(w, m);
                w.wl(";");
            }
        }
        for c in &i.consts {
            if !marshal.can_be_const_variable(c) {
                w.wl_empty();
                write_doc(w, &c.doc);
                write_objc_const_meth_decl(w, c, &marshal, spec);
            }
        }
        w.wl_empty();
        w.wl("@end");
    });

    // Generate the implementation file for constants
    if !i.consts.is_empty() {
        refs.body.insert(format!(
            "#import {}",
            q(&format!(
                "{}{}",
                spec.objc_include_prefix,
                marshal.header_name(&ident.name)
            ))
        ));
        let body_name = format!(
            "{}.{}",
            marshal.typename_from_name(&ident.name, &TypeDef::Interface(i.clone())),
            spec.objcpp_ext
        );
        write_objc_file(out_files, written_files, objc_out, &body_name, origin, &refs.body, |w| {
            generate_objc_constants(
                w,
                &i.consts,
                &self_name,
                ObjcConstantType::ConstVariable,
                &marshal,
                spec,
                idl,
            );
        });
    }
}

// --- Record ---

fn generate_record(
    ctx: &mut GeneratorContext,
    objc_out: &std::path::Path,
    origin: &str,
    ident: &Ident,
    doc: &Doc,
    _params: &[TypeParam],
    r: &Record,
    idl: &[TypeDecl],
) {
    let (spec, out_files, written_files) = ctx.split_borrow();
    let marshal = ObjcMarshal::new(spec);
    let id_objc = &spec.objc_ident_style;

    let mut refs = ObjcRefs::new();
    for c in &r.consts {
        refs.find_type_ref(&c.ty, &marshal);
    }
    for f in &r.fields {
        refs.find_type_ref(&f.ty, &marshal);
    }

    let objc_name = if r.ext.objc {
        format!("{}_base", ident.name)
    } else {
        ident.name.clone()
    };
    let no_base_self = marshal.typename_from_name(&ident.name, &TypeDef::Record(r.clone()));
    let self_name = marshal.typename_from_name(&objc_name, &TypeDef::Record(r.clone()));
    let super_record = get_super_record(idl, r);

    refs.header.insert("#import <Foundation/Foundation.h>".to_string());
    refs.body.insert(format!(
        "!#import {}",
        q(&format!(
            "{}{}",
            if r.ext.objc {
                &spec.objc_extended_record_include_prefix
            } else {
                &spec.objc_include_prefix
            },
            marshal.header_name(&ident.name)
        ))
    ));

    if r.ext.objc {
        refs.header.insert(format!("@class {};", no_base_self));
    }

    let super_fields: Vec<Field> = match &super_record {
        None => vec![],
        Some(sr) => sr.fields.clone(),
    };
    let (super_class, first_initializer_arg) = match &super_record {
        None => {
            let first_arg = if r.fields.is_empty() {
                String::new()
            } else {
                camel_upper(&format!("with_{}", r.fields[0].ident.name))
            };
            ("NSObject".to_string(), first_arg)
        }
        Some(sr) => {
            let prefix = if r.ext.objc {
                &spec.objc_extended_record_include_prefix
            } else {
                &spec.objc_include_prefix
            };
            let sc = format!(
                "{}{}",
                prefix,
                marshal.typename_from_name(&sr.ident.name, &TypeDef::Record(sr.record.clone()))
            );
            let first_arg = if sr.fields.is_empty() {
                String::new()
            } else {
                camel_upper(&format!("with_{}", sr.fields[0].ident.name))
            };
            (sc, first_arg)
        }
    };

    let is_record_inherited = is_inherited(idl, &ident.name);

    let all_fields: Vec<Field> = [super_fields.clone(), r.fields.clone()].concat();

    fn check_mutable(tm: &MExpr) -> bool {
        match &tm.base {
            Meta::MOptional => {
                if let Some(first) = tm.args.first() {
                    check_mutable(first)
                } else {
                    false
                }
            }
            Meta::MString | Meta::MList | Meta::MArray | Meta::MSet | Meta::MMap | Meta::MBinary => true,
            _ => false,
        }
    }

    // Generate header
    let header_name = marshal.header_name(&objc_name);
    write_objc_file(out_files, written_files, objc_out, &header_name, origin, &refs.header, |w| {
        // Import super record header if present
        if let Some(sr) = &super_record {
            let prefix = if r.ext.objc {
                &spec.objc_extended_record_include_prefix
            } else {
                &spec.objc_include_prefix
            };
            w.wl(&format!(
                "#import {}",
                q(&format!("{}{}", prefix, marshal.header_name(&sr.ident.name)))
            ));
        }

        write_doc(w, doc);

        if r.deriving_types.contains(&DerivingType::NSCopying) {
            w.wl(&format!("@interface {} : {}<NSCopying>", self_name, super_class));
        } else {
            w.wl(&format!("@interface {} : {}", self_name, super_class));
        }

        // Constructor
        if !r.fields.is_empty() || !super_fields.is_empty() {
            w.wl("- (nonnull instancetype)init NS_UNAVAILABLE;");
            w.wl("+ (nonnull instancetype)new NS_UNAVAILABLE;");
        }

        // Write designated initializer
        {
            let decl = format!("- (nonnull instancetype)init{}", first_initializer_arg);
            write_aligned_objc_call(w, &decl, &all_fields, "", |f| {
                (
                    (id_objc.field)(&f.ident.name),
                    format!(
                        "({}){}",
                        marshal.param_type(&f.ty),
                        (id_objc.local)(&f.ident.name)
                    ),
                )
            });

            if !is_record_inherited {
                w.wl(" NS_DESIGNATED_INITIALIZER;");
            } else {
                w.wl(";");
            }
        }

        // Write convenience initializer
        if !r.ext.objc && !spec.objc_disable_class_ctor {
            let decl = format!(
                "+ (nonnull instancetype){}{}",
                djinni_ast::ident_style::camel_lower(&objc_name),
                first_initializer_arg
            );
            write_aligned_objc_call(w, &decl, &all_fields, "", |f| {
                (
                    (id_objc.field)(&f.ident.name),
                    format!(
                        "({}){}",
                        marshal.param_type(&f.ty),
                        (id_objc.local)(&f.ident.name)
                    ),
                )
            });
            w.wl(";");
        }

        for c in &r.consts {
            if !marshal.can_be_const_variable(c) {
                w.wl_empty();
                write_doc(w, &c.doc);
                write_objc_const_meth_decl(w, c, &marshal, spec);
            }
        }

        for f in &r.fields {
            w.wl_empty();
            write_doc(w, &f.doc);
            let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
            let nullability = marshal.nullability(tm)
                .map(|n| format!(", {}", n))
                .unwrap_or_default();
            w.wl(&format!(
                "@property (nonatomic, readonly{}) {} {};",
                nullability,
                marshal.field_type_mexpr(tm),
                (id_objc.field)(&f.ident.name)
            ));
        }
        if r.deriving_types.contains(&DerivingType::Ord) {
            w.wl_empty();
            w.wl(&format!("- (NSComparisonResult)compare:(nonnull {} *)other;", self_name));
        }
        w.wl_empty();
        w.wl("@end");

        // Constants after @end
        if !r.consts.is_empty() {
            w.wl_empty();
            for c in &r.consts {
                if marshal.can_be_const_variable(c) {
                    write_doc(w, &c.doc);
                    w.w("extern ");
                    write_objc_const_variable_decl(w, c, &no_base_self, &marshal, spec);
                    w.wl(";");
                }
            }
        }
    });

    // Generate implementation file
    refs.body.insert("#import \"DjinniUtils.h\"".to_string());
    let body_name = format!("{}.{}", marshal.typename_from_name(&objc_name, &TypeDef::Record(r.clone())), spec.objcpp_ext);

    write_objc_file(out_files, written_files, objc_out, &body_name, origin, &refs.body, |w| {
        if !r.consts.is_empty() {
            generate_objc_constants(w, &r.consts, &no_base_self, ObjcConstantType::ConstVariable, &marshal, spec, idl);
        }

        w.wl_empty();
        w.wl(&format!("@implementation {}", self_name));
        w.wl_empty();

        // Designated initializer
        let init_decl = format!("- (nonnull instancetype)init{}", first_initializer_arg);
        write_aligned_objc_call(w, &init_decl, &all_fields, "", |f| {
            (
                (id_objc.field)(&f.ident.name),
                format!(
                    "({}){}",
                    marshal.param_type(&f.ty),
                    (id_objc.local)(&f.ident.name)
                ),
            )
        });
        w.wl_empty();
        w.braced(|w| {
            match &super_record {
                None => w.w("if (self = [super init])"),
                Some(sr) => {
                    let super_init_decl = format!("if (self = [super init{}", first_initializer_arg);
                    write_aligned_objc_call(w, &super_init_decl, &sr.fields, "", |f| {
                        (
                            (id_objc.field)(&f.ident.name),
                            (id_objc.local)(&f.ident.name).to_string(),
                        )
                    });
                    w.wl("])");
                    // Return early - the braced block follows differently
                    w.braced(|w| {
                        for f in &r.fields {
                            let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
                            if check_mutable(tm) {
                                w.wl(&format!(
                                    "_{} = [{} copy];",
                                    (id_objc.field)(&f.ident.name),
                                    (id_objc.local)(&f.ident.name)
                                ));
                            } else {
                                w.wl(&format!(
                                    "_{} = {};",
                                    (id_objc.field)(&f.ident.name),
                                    (id_objc.local)(&f.ident.name)
                                ));
                            }
                        }
                    });
                    w.wl("return self;");
                    return;
                }
            };
            w.braced(|w| {
                for f in &r.fields {
                    let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
                    if check_mutable(tm) {
                        w.wl(&format!(
                            "_{} = [{} copy];",
                            (id_objc.field)(&f.ident.name),
                            (id_objc.local)(&f.ident.name)
                        ));
                    } else {
                        w.wl(&format!(
                            "_{} = {};",
                            (id_objc.field)(&f.ident.name),
                            (id_objc.local)(&f.ident.name)
                        ));
                    }
                }
            });
            w.wl("return self;");
        });
        w.wl_empty();

        // Convenience initializer
        if !r.ext.objc && !spec.objc_disable_class_ctor {
            let conv_decl = format!(
                "+ (nonnull instancetype){}{}",
                djinni_ast::ident_style::camel_lower(&objc_name),
                first_initializer_arg
            );
            write_aligned_objc_call(w, &conv_decl, &all_fields, "", |f| {
                (
                    (id_objc.field)(&f.ident.name),
                    format!(
                        "({}){}",
                        marshal.param_type(&f.ty),
                        (id_objc.local)(&f.ident.name)
                    ),
                )
            });
            w.wl_empty();
            w.braced(|w| {
                let call = format!("return [[self alloc] init{}", first_initializer_arg);
                write_aligned_objc_call(w, &call, &all_fields, "", |f| {
                    (
                        (id_objc.field)(&f.ident.name),
                        (id_objc.local)(&f.ident.name).to_string(),
                    )
                });
                w.wl("];");
            });
            w.wl_empty();
        }

        if !r.consts.is_empty() {
            generate_objc_constants(w, &r.consts, &no_base_self, ObjcConstantType::ConstMethod, &marshal, spec, idl);
        }

        // isEqual:
        w.wl("- (BOOL)isEqual:(id)other");
        w.braced(|w| {
            w.w(&format!("if (![other isKindOfClass:[{} class]])", self_name));
            w.braced(|w| {
                w.wl("return NO;");
            });

            if super_fields.is_empty() && r.fields.is_empty() {
                w.wl("return YES;");
            } else {
                w.wl(&format!("{} *typedOther = ({} *)other;", self_name, self_name));
                w.w("return ");
                w.nested_n(2, |w| {
                    let mut first = true;
                    for f in all_fields.iter() {
                        if first {
                            first = false;
                        } else {
                            w.wl(" &&");
                        }
                        let field_name = (id_objc.field)(&f.ident.name);
                        let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
                        write_equality_check(w, tm, &field_name, spec);
                    }
                });
                w.wl(";");
            }
        });
        w.wl_empty();

        // hash
        w.wl("- (NSUInteger)hash");
        w.braced(|w| {
            w.wl("NSUInteger hashCode = 17;");
            for f in all_fields.iter() {
                let field_name = (id_objc.field)(&f.ident.name);
                let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
                let hash_code = write_hash_code(tm, &field_name, spec);
                w.wl(&format!("hashCode = hashCode * 31 + {};", hash_code));
            }
            w.wl("return hashCode;");
        });
        w.wl_empty();

        // compare (Ord)
        if r.deriving_types.contains(&DerivingType::Ord) {
            w.wl(&format!("- (NSComparisonResult)compare:({} *)other", self_name));
            w.braced(|w| {
                w.wl("NSComparisonResult tempResult;");
                for f in &r.fields {
                    let field_name = (id_objc.field)(&f.ident.name);
                    let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
                    write_compare(w, tm, &field_name, spec);
                    w.w("if (tempResult != NSOrderedSame)");
                    w.braced(|w| {
                        w.wl("return tempResult;");
                    });
                }
                w.wl("return NSOrderedSame;");
            });
            w.wl_empty();
        }

        // NSCopying
        if r.deriving_types.contains(&DerivingType::NSCopying) {
            w.wl("- (id)copyWithZone:(NSZone *)zone");
            w.wl("{");
            w.wl("    return self;");
            w.wl("}");
            w.wl_empty();
        }

        // description
        w.wl("#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS");
        w.wl("- (NSString *)description");
        w.braced(|w| {
            w.w("return ");
            w.nested_n(2, |w| {
                w.w("[NSString stringWithFormat:@\"<%@ %p");
                for f in all_fields.iter() {
                    w.w(&format!(" {}:%@", (id_objc.field)(&f.ident.name)));
                }
                w.w(">\", self.class, (void *)self");
                for f in all_fields.iter() {
                    w.w(", ");
                    let field_name = (id_objc.field)(&f.ident.name);
                    let tm = f.ty.resolved.as_ref().expect("TypeRef not resolved");
                    write_description_value(w, tm, &field_name);
                }
            });
            w.wl("];");
        });
        w.wl_empty();
        w.wl("#endif");

        w.wl("@end");
    });
}

// --- equality helper ---

fn write_equality_check(w: &mut IndentWriter, tm: &MExpr, field_name: &str, _spec: &Spec) {
    match &tm.base {
        Meta::MBinary => {
            w.w(&format!("[self.{} isEqualToData:typedOther.{}]", field_name, field_name));
        }
        Meta::MList | Meta::MArray => {
            w.w(&format!("[self.{} isEqualToArray:typedOther.{}]", field_name, field_name));
        }
        Meta::MSet => {
            w.w(&format!("[self.{} isEqualToSet:typedOther.{}]", field_name, field_name));
        }
        Meta::MMap => {
            w.w(&format!("[self.{} isEqualToDictionary:typedOther.{}]", field_name, field_name));
        }
        Meta::MOptional => {
            let arg = &tm.args[0];
            match &arg.base {
                Meta::MDef(d) if d.def_type == DefType::Enum => {
                    w.w(&format!("self.{} == typedOther.{}", field_name, field_name));
                }
                Meta::MExtern(e) => match e.def_type {
                    DefType::Record => {
                        if !e.objc.equal.is_empty() {
                            w.w(&format!(
                                "((self.{fn} == nil && typedOther.{fn} == nil) || (self.{fn} != nil && [self.{fn} {}typedOther.{fn}]))",
                                e.objc.equal, fn = field_name
                            ));
                        } else {
                            w.w(&format!(
                                "((self.{fn} == nil && typedOther.{fn} == nil) || (self.{fn} != nil && [self.{fn} isEqual:typedOther.{fn}]))",
                                fn = field_name
                            ));
                        }
                    }
                    _ => {}
                },
                _ => {
                    w.w(&format!(
                        "((self.{fn} == nil && typedOther.{fn} == nil) || (self.{fn} != nil && [self.{fn} isEqual:typedOther.{fn}]))",
                        fn = field_name
                    ));
                }
            }
        }
        Meta::MString => {
            w.w(&format!("[self.{} isEqualToString:typedOther.{}]", field_name, field_name));
        }
        Meta::MDate => {
            w.w(&format!("[self.{} isEqualToDate:typedOther.{}]", field_name, field_name));
        }
        Meta::MPrimitive(_) => {
            w.w(&format!("self.{} == typedOther.{}", field_name, field_name));
        }
        Meta::MDef(d) => match d.def_type {
            DefType::Record => {
                w.w(&format!("[self.{} isEqual:typedOther.{}]", field_name, field_name));
            }
            DefType::Enum => {
                w.w(&format!("self.{} == typedOther.{}", field_name, field_name));
            }
            _ => panic!("Unreachable"),
        },
        Meta::MExtern(e) => match e.def_type {
            DefType::Record => {
                if e.objc.pointer {
                    w.w(&format!("[self.{} {}typedOther.{}]", field_name, e.objc.equal, field_name));
                } else {
                    w.w(&format!("self.{} == typedOther.{}", field_name, field_name));
                }
            }
            DefType::Enum => {
                w.w(&format!("self.{} == typedOther.{}", field_name, field_name));
            }
            _ => panic!("Unreachable"),
        },
        Meta::MProtobuf(_) => {}
        _ => panic!("Unreachable"),
    }
}

// --- hash helper ---

fn write_hash_code(tm: &MExpr, field_name: &str, _spec: &Spec) -> String {
    match &tm.base {
        Meta::MList | Meta::MArray => format!("self.{}.dynamicHash", field_name),
        Meta::MOptional => {
            let arg = &tm.args[0];
            match &arg.base {
                Meta::MList | Meta::MArray => format!("self.{}.dynamicHash", field_name),
                Meta::MDef(d) if d.def_type == DefType::Enum => {
                    format!("(NSUInteger)self.{}", field_name)
                }
                Meta::MExtern(e) => match e.def_type {
                    DefType::Record => e.objc.hash.replace("{}", &format!("self.{}", field_name)),
                    _ => format!("self.{}.hash", field_name),
                },
                _ => format!("self.{}.hash", field_name),
            }
        }
        Meta::MPrimitive(p) => {
            if p.objc_name == "float" {
                format!("[NSNumber numberWithFloat:self.{}].hash", field_name)
            } else if p.objc_name == "double" {
                format!("[NSNumber numberWithDouble:self.{}].hash", field_name)
            } else {
                format!("(NSUInteger)self.{}", field_name)
            }
        }
        Meta::MDef(d) => match d.def_type {
            DefType::Enum => format!("(NSUInteger)self.{}", field_name),
            _ => format!("self.{}.hash", field_name),
        },
        Meta::MExtern(e) => match e.def_type {
            DefType::Enum => format!("(NSUInteger)self.{}", field_name),
            DefType::Record => format!(
                "({})",
                e.objc.hash.replace("{}", &format!("self.{}", field_name))
            ),
            _ => panic!("Unreachable"),
        },
        Meta::MProtobuf(_) => String::new(),
        _ => format!("self.{}.hash", field_name),
    }
}

// --- compare helper ---

fn write_compare(w: &mut IndentWriter, tm: &MExpr, field_name: &str, _spec: &Spec) {
    fn write_primitive_order(w: &mut IndentWriter, field_name: &str) {
        w.wl(&format!("if (self.{} < other.{}) {{", field_name, field_name));
        w.nested(|w| {
            w.wl("tempResult = NSOrderedAscending;");
        });
        w.wl(&format!("}} else if (self.{} > other.{}) {{", field_name, field_name));
        w.nested(|w| {
            w.wl("tempResult = NSOrderedDescending;");
        });
        w.wl("} else {");
        w.nested(|w| {
            w.wl("tempResult = NSOrderedSame;");
        });
        w.wl("}");
    }

    match &tm.base {
        Meta::MString | Meta::MDate => {
            w.wl(&format!(
                "tempResult = [self.{} compare:other.{}];",
                field_name, field_name
            ));
        }
        Meta::MPrimitive(_) => write_primitive_order(w, field_name),
        Meta::MDef(d) => match d.def_type {
            DefType::Record => {
                w.wl(&format!(
                    "tempResult = [self.{} compare:other.{}];",
                    field_name, field_name
                ));
            }
            DefType::Enum => write_primitive_order(w, field_name),
            _ => panic!("Unreachable"),
        },
        Meta::MExtern(e) => match e.def_type {
            DefType::Record => {
                if e.objc.pointer {
                    w.wl(&format!(
                        "tempResult = [self.{} compare:other.{}];",
                        field_name, field_name
                    ));
                } else {
                    write_primitive_order(w, field_name);
                }
            }
            DefType::Enum => write_primitive_order(w, field_name),
            _ => panic!("Unreachable"),
        },
        _ => panic!("Unreachable"),
    }
}

// --- description helper ---

fn write_description_value(w: &mut IndentWriter, tm: &MExpr, field_name: &str) {
    match &tm.base {
        Meta::MOptional => {
            w.w(&format!("self.{}", field_name));
        }
        Meta::MPrimitive(_) => {
            w.w(&format!("@(self.{})", field_name));
        }
        Meta::MDef(d) => {
            match d.def_type {
                DefType::Enum => { w.w(&format!("@(self.{})", field_name)); }
                _ => { w.w(&format!("self.{}", field_name)); }
            }
        }
        Meta::MExtern(e) => {
            if e.objc.pointer {
                w.w(&format!("self.{}", field_name));
            } else {
                w.w(&format!("@(self.{})", field_name));
            }
        }
        Meta::MProtobuf(p) => {
            if p.body.objc.is_some() {
                w.w(&format!("self.{}", field_name));
            } else {
                w.w("@\"[Opaque C++ Protobuf object]\"");
            }
        }
        _ => {
            w.w(&format!("self.{}", field_name));
        }
    }
}
