// vinsg
// TypeScript type definition generator, translated from TsGenerator.scala

use std::collections::BTreeSet;

use djinni_ast::ast::*;
use djinni_ast::ident_style::JsIdentStyle;
use djinni_ast::meta::*;
use djinni_ast::spec::Spec;

use crate::gen::{
    create_file_from_parts, write_doc, write_enum_option_all,
    write_enum_option_none, write_enum_options, write_method_doc, GeneratorContext,
};
use crate::writer::IndentWriter;

pub fn generate_ts(ctx: &mut GeneratorContext, idl: &[TypeDecl]) {
    let ts_out = match &ctx.spec.ts_out_folder {
        Some(f) => f.clone(),
        None => return,
    };

    let (spec, out_files, written_files) = ctx.split_borrow();
    let id_js = &spec.js_ident_style;

    // Collect intern types
    let decls: Vec<&TypeDecl> = idl
        .iter()
        .filter(|td| matches!(td, TypeDecl::Intern { .. }))
        .collect();

    // Collect external references (imports) - preserve insertion order
    let mut imports: Vec<(String, BTreeSet<String>)> = Vec::new();
    for td in &decls {
        match td.body() {
            TypeDef::Record(r) => {
                for f in &r.fields {
                    collect_refs(&mut imports, f.ty.resolved.as_ref());
                }
                for c in &r.consts {
                    collect_refs(&mut imports, c.ty.resolved.as_ref());
                }
            }
            TypeDef::Interface(i) => {
                for m in &i.methods {
                    for p in &m.params {
                        collect_refs(&mut imports, p.ty.resolved.as_ref());
                    }
                    if let Some(ref ret) = m.ret {
                        collect_refs(&mut imports, ret.resolved.as_ref());
                    }
                }
                for c in &i.consts {
                    collect_refs(&mut imports, c.ty.resolved.as_ref());
                }
            }
            _ => {}
        }
    }

    let file_name = format!("{}.ts", spec.ts_module);
    create_file_from_parts(out_files, written_files, &ts_out, &file_name, |w| {
        w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!(
            "// This file was generated by Djinni from {}.djinni",
            spec.module_name
        ));
        w.wl_empty();

        // Write imports
        for (module, syms) in &imports {
            if !module.is_empty() {
                let syms_str: Vec<&str> = syms.iter().map(|s| s.as_str()).collect();
                w.wl(&format!(
                    "import {{ {} }} from \"{}\"",
                    syms_str.join(", "),
                    module
                ));
            }
        }

        // Generate types
        let mut interfaces_with_statics = Vec::new();
        for td in &decls {
            match td.body() {
                TypeDef::Enum(e) => generate_ts_enum(w, td.ident(), &doc_for_td(td), e, id_js),
                TypeDef::Record(r) => {
                    generate_ts_record(w, td.ident(), &doc_for_td(td), r, id_js, spec)
                }
                TypeDef::Interface(i) => {
                    generate_ts_interface(w, td.ident(), &doc_for_td(td), i, id_js, spec);
                    if i.methods.iter().any(|m| m.is_static && m.lang.js) {
                        interfaces_with_statics.push((id_js.ty)(&td.ident().name));
                    }
                }
                _ => {}
            }
        }

        // Static factories / namespace bindings
        w.wl_empty();
        if !spec.wasm_omit_ns_alias {
            if let Some(ref wasm_ns) = spec.wasm_namespace {
                let ns_parts: Vec<&str> = wasm_ns.split('.').collect();

                // Nested namespace interfaces
                for i in 0..ns_parts.len() - 1 {
                    w.w(&format!("export interface ns_{}", ns_parts[i]));
                    w.braced(|w| {
                        w.wl(&format!("{}: ns_{}", ns_parts[i + 1], ns_parts[i + 1]));
                    });
                }

                // Innermost namespace with statics
                w.w(&format!("export interface ns_{}", ns_parts.last().unwrap()));
                w.braced(|w| {
                    for name in &interfaces_with_statics {
                        w.wl(&format!("{}: {}_statics;", name, name));
                    }
                });

                // Module statics
                let module_name = (id_js.ty)(&spec.ts_module);
                w.w(&format!("export interface {}_statics", module_name));
                w.braced(|w| {
                    for name in &interfaces_with_statics {
                        let prefixed = with_wasm_namespace(spec, name);
                        w.wl(&format!("{}: {}_statics;", prefixed, name));
                    }
                    w.wl_empty();
                    w.wl(&format!("{}: ns_{};", ns_parts[0], ns_parts[0]));
                });
            }
        } else {
            let module_name = (id_js.ty)(&spec.ts_module);
            w.w(&format!("export interface {}_statics", module_name));
            w.braced(|w| {
                for name in &interfaces_with_statics {
                    let prefixed = with_wasm_namespace(spec, name);
                    w.wl(&format!("{}: {}_statics;", prefixed, name));
                }
            });
        }
    });
}

fn doc_for_td(td: &TypeDecl) -> Doc {
    match td {
        TypeDecl::Intern { doc, .. } => doc.clone(),
        TypeDecl::Extern { .. } => Doc { lines: vec![] },
        TypeDecl::Protobuf { .. } => Doc { lines: vec![] },
    }
}

fn with_wasm_namespace(spec: &Spec, name: &str) -> String {
    match &spec.wasm_namespace {
        Some(ns) => format!("{}_{}", ns.replace('.', "_"), name),
        None => name.to_string(),
    }
}

// --- Reference collection ---

fn collect_refs(imports: &mut Vec<(String, BTreeSet<String>)>, resolved: Option<&MExpr>) {
    if let Some(tm) = resolved {
        collect_refs_mexpr(imports, tm);
    }
}

fn collect_refs_mexpr(imports: &mut Vec<(String, BTreeSet<String>)>, tm: &MExpr) {
    for arg in &tm.args {
        collect_refs_mexpr(imports, arg);
    }
    fn add_import(imports: &mut Vec<(String, BTreeSet<String>)>, module: String, sym: String) {
        if let Some(entry) = imports.iter_mut().find(|(m, _)| *m == module) {
            entry.1.insert(sym);
        } else {
            let mut set = BTreeSet::new();
            set.insert(sym);
            imports.push((module, set));
        }
    }
    match &tm.base {
        Meta::MExtern(e) => {
            if !e.ts.module.is_empty() {
                add_import(imports, e.ts.module.clone(), e.ts.typename.clone());
            }
        }
        Meta::MProtobuf(p) => {
            if let Some(ref ts) = p.body.ts {
                add_import(imports, ts.module.clone(), p.name.clone());
            }
        }
        _ => {}
    }
}

// --- Type mapping ---

fn to_ts_type(tm: &MExpr, id_js: &JsIdentStyle, add_nullability: bool) -> String {
    let base = to_ts_type_inner(tm, id_js);
    if add_nullability {
        match &tm.base {
            Meta::MOptional => format!("{} | undefined", base),
            _ => base,
        }
    } else {
        base
    }
}

fn to_ts_type_inner(tm: &MExpr, id_js: &JsIdentStyle) -> String {
    fn args_str(tm: &MExpr, id_js: &JsIdentStyle) -> String {
        if tm.args.is_empty() {
            String::new()
        } else {
            let inner: Vec<String> = tm
                .args
                .iter()
                .map(|a| to_ts_type(a, id_js, true))
                .collect();
            format!("<{}>", inner.join(", "))
        }
    }

    match &tm.base {
        Meta::MOptional => {
            assert_eq!(tm.args.len(), 1);
            to_ts_type_inner(&tm.args[0], id_js)
        }
        Meta::MArray => ts_array_type(&tm.args[0], id_js),
        Meta::MExtern(e) => {
            let base = e.ts.typename.clone();
            if e.ts.generic {
                format!("{}{}", base, args_str(tm, id_js))
            } else {
                base
            }
        }
        Meta::MProtobuf(p) => p.name.clone(),
        Meta::MPrimitive(p) => ts_primitive_type(p),
        Meta::MString => "string".to_string(),
        Meta::MDate => "Date".to_string(),
        Meta::MBinary => "Uint8Array".to_string(),
        Meta::MList => format!("Array{}", args_str(tm, id_js)),
        Meta::MSet => format!("Set{}", args_str(tm, id_js)),
        Meta::MMap => format!("Map{}", args_str(tm, id_js)),
        Meta::MDef(d) => {
            let base = (id_js.ty)(&d.name);
            format!("{}{}", base, args_str(tm, id_js))
        }
        Meta::MParam(p) => (id_js.type_param)(&p.name),
        Meta::MVoid => "void".to_string(),
    }
}

fn ts_primitive_type(p: &MPrimitive) -> String {
    match p.idl_name.as_str() {
        "bool" => "boolean".to_string(),
        "i64" => "bigint".to_string(),
        _ => "number".to_string(),
    }
}

fn ts_array_type(elem: &MExpr, id_js: &JsIdentStyle) -> String {
    match &elem.base {
        Meta::MPrimitive(p) => match p.idl_name.as_str() {
            "i8" => "Int8Array".to_string(),
            "i16" => "Int16Array".to_string(),
            "i32" => "Int32Array".to_string(),
            "i64" => "BigInt64Array".to_string(),
            "f32" => "Float32Array".to_string(),
            "f64" => "Float64Array".to_string(),
            _ => format!("Array<{}>", ts_primitive_type(p)),
        },
        _ => format!("Array<{}>", to_ts_type(elem, id_js, true)),
    }
}

fn ts_ret_type(m: &Method, id_js: &JsIdentStyle) -> String {
    match &m.ret {
        None => "void".to_string(),
        Some(ty) => to_ts_type(ty.resolved.as_ref().unwrap(), id_js, true),
    }
}

// --- Enum ---

fn generate_ts_enum(
    w: &mut IndentWriter,
    ident: &Ident,
    doc: &Doc,
    e: &Enum,
    id_js: &JsIdentStyle,
) {
    w.wl_empty();
    write_doc(w, doc);
    w.w(&format!("export enum {}", (id_js.ty)(&ident.name)));
    w.braced(|w| {
        write_enum_option_none(w, e, &|n| (id_js.enum_)(n), "=");
        write_enum_options(w, e, &|n| (id_js.enum_)(n), "=");
        write_enum_option_all(w, e, &|n| (id_js.enum_)(n), "=");
    });
}

// --- Record ---

fn generate_ts_record(
    w: &mut IndentWriter,
    ident: &Ident,
    doc: &Doc,
    r: &Record,
    id_js: &JsIdentStyle,
    spec: &Spec,
) {
    w.wl_empty();
    write_doc(w, doc);
    w.w(&format!("export interface /*record*/ {}", (id_js.ty)(&ident.name)));
    w.braced(|w| {
        for f in &r.fields {
            write_doc(w, &f.doc);
            let tm = f.ty.resolved.as_ref().unwrap();
            let field_name = (id_js.field)(&f.ident.name);
            match &tm.base {
                Meta::MOptional => {
                    let inner = &tm.args[0];
                    w.wl(&format!("{}?: {};", field_name, to_ts_type(inner, id_js, true)));
                }
                _ => {
                    w.wl(&format!("{}: {};", field_name, to_ts_type(tm, id_js, true)));
                }
            }
        }
    });
    if !r.consts.is_empty() {
        generate_ts_constants(w, ident, &r.consts, id_js, spec);
    }
}

// --- Interface ---

fn generate_ts_interface(
    w: &mut IndentWriter,
    ident: &Ident,
    doc: &Doc,
    i: &Interface,
    id_js: &JsIdentStyle,
    spec: &Spec,
) {
    w.wl_empty();
    write_doc(w, doc);
    let type_name = (id_js.ty)(&ident.name);
    w.w(&format!("export interface {}", type_name));
    w.braced(|w| {
        for m in i.methods.iter().filter(|m| !m.is_static) {
            write_method_doc(w, &m.doc, &m.params, id_js.local);
            let params: Vec<String> = m
                .params
                .iter()
                .map(|p| {
                    format!(
                        "{}: {}",
                        (id_js.local)(&p.ident.name),
                        to_ts_type(p.ty.resolved.as_ref().unwrap(), id_js, true)
                    )
                })
                .collect();
            w.wl(&format!(
                "{}({}): {};",
                (id_js.method)(&m.ident.name),
                params.join(", "),
                ts_ret_type(m, id_js)
            ));
        }
    });

    if !i.consts.is_empty() {
        generate_ts_constants(w, ident, &i.consts, id_js, spec);
    }

    let statics: Vec<&Method> = i
        .methods
        .iter()
        .filter(|m| m.is_static && m.lang.js)
        .collect();
    if !statics.is_empty() {
        w.w(&format!("export interface {}_statics", type_name));
        w.braced(|w| {
            for m in &statics {
                write_method_doc(w, &m.doc, &m.params, id_js.local);
                let params: Vec<String> = m
                    .params
                    .iter()
                    .map(|p| {
                        format!(
                            "{}: {}",
                            (id_js.method)(&p.ident.name),
                            to_ts_type(p.ty.resolved.as_ref().unwrap(), id_js, true)
                        )
                    })
                    .collect();
                w.wl(&format!(
                    "{}({}): {};",
                    (id_js.method)(&m.ident.name),
                    params.join(", "),
                    ts_ret_type(m, id_js)
                ));
            }
        });
    }
}

// --- Constants ---

fn generate_ts_constants(
    w: &mut IndentWriter,
    ident: &Ident,
    consts: &[Const],
    id_js: &JsIdentStyle,
    _spec: &Spec,
) {
    w.w(&format!("export namespace {}", (id_js.ty)(&ident.name)));
    w.braced(|w| {
        for c in consts {
            write_doc(w, &c.doc);
            w.w(&format!("export const {} = ", (id_js.const_)(&c.ident.name)));
            write_ts_const_value(w, &c.ty, &c.value, id_js);
            w.wl(";");
        }
    });
}

fn write_ts_const_value(
    w: &mut IndentWriter,
    ty: &TypeRef,
    value: &ConstValue,
    id_js: &JsIdentStyle,
) {
    match value {
        ConstValue::Int(l) => {
            let is_bigint = ty.resolved.as_ref()
                .map(|tm| to_ts_type(&remove_optional(tm), id_js, false) == "bigint")
                .unwrap_or(false);
            if is_bigint {
                w.w(&format!("BigInt(\"{}\")", l));
            } else {
                w.w(&l.to_string());
            }
        }
        ConstValue::Float(d) => {
            let s = d.to_string();
            if s.contains('.') {
                w.w(&s);
            } else {
                w.w(&format!("{}.0", s));
            }
        }
        ConstValue::Bool(b) => { w.w(if *b { "true" } else { "false" }); }
        ConstValue::String(s) => { w.w(&format!("\"{}\"", s)); }
        ConstValue::EnumValue { ty: _, value: val } => {
            let type_name = (id_js.ty)(&ty.expr.ident.name);
            w.w(&format!("{}.{}", type_name, (id_js.enum_)(val)));
        }
        ConstValue::ConstRef(name) => {
            w.w(&(id_js.const_)(name));
        }
        ConstValue::Composite(fields) => {
            let tm = match ty.resolved.as_ref() {
                Some(t) => t,
                None => return,
            };
            if let Meta::MDef(d) = &tm.base {
                if let TypeDef::Record(record) = &d.body {
                    w.braced(|w| {
                        let mut first = true;
                        for f in &record.fields {
                            if !first {
                                w.wl(",");
                            }
                            first = false;
                            w.w(&format!("{}: ", (id_js.field)(&f.ident.name)));
                            if let Some((_, val)) =
                                fields.iter().find(|(k, _)| *k == f.ident.name)
                            {
                                write_ts_const_value(w, &f.ty, val, id_js);
                            }
                        }
                        w.wl_empty();
                    });
                }
            }
        }
    }
}

fn remove_optional(tm: &MExpr) -> MExpr {
    match &tm.base {
        Meta::MOptional if !tm.args.is_empty() => tm.args[0].clone(),
        _ => tm.clone(),
    }
}
