// vinsg
// YAML generator: outputs type metadata for extern type round-tripping,
// translated from YamlGenerator.scala

use djinni_ast::ast::*;
use djinni_ast::meta::*;
use djinni_ast::spec::Spec;

use crate::cpp_marshal::CppMarshal;
use crate::gen::GeneratorContext;
use crate::java_marshal::JavaMarshal;
use crate::jni_marshal::JniMarshal;
use crate::objc_marshal::ObjcMarshal;
use crate::objcpp_marshal::ObjcppMarshal;
use crate::writer::IndentWriter;

use std::collections::HashMap;
use std::path::Path;

pub fn generate_yaml(ctx: &mut GeneratorContext, idl: &[TypeDecl]) {
    let yaml_out = match &ctx.spec.yaml_out_folder {
        Some(f) => f.clone(),
        None => return,
    };

    // Collect intern types only, sorted by name
    let mut intern_types: Vec<&TypeDecl> = idl
        .iter()
        .filter(|td| matches!(td, TypeDecl::Intern { .. }))
        .collect();
    intern_types.sort_by_key(|td| &td.ident().name);

    if let Some(out_file) = ctx.spec.yaml_out_file.clone() {
        // Single combined file
        let origins: Vec<&str> = {
            let mut origins: Vec<&str> = intern_types.iter().map(|td| td.origin()).collect();
            origins.sort();
            origins.dedup();
            origins
        };
        let origins_str = origins.join(", ");

        let (spec, out_files, written_files) = ctx.split_borrow();
        write_yaml_combined(
            spec,
            out_files,
            written_files,
            &yaml_out,
            &out_file,
            &origins_str,
            &intern_types,
        );
    } else {
        // One file per type
        for td in &intern_types {
            let file_name = format!("{}{}.yaml", ctx.spec.yaml_prefix, td.ident().name);
            let (spec, out_files, written_files) = ctx.split_borrow();
            write_yaml_single(
                spec,
                out_files,
                written_files,
                &yaml_out,
                &file_name,
                td.origin(),
                td,
            );
        }
    }
}

fn write_yaml_combined(
    spec: &Spec,
    out_files: &mut Vec<std::path::PathBuf>,
    written_files: &mut HashMap<String, String>,
    folder: &Path,
    file_name: &str,
    origins: &str,
    types: &[&TypeDecl],
) {
    crate::gen::create_file_from_parts(out_files, written_files, folder, file_name, |w| {
        // Use 2-space indent for YAML
        *w = IndentWriter::with_indent("  ", "");
        w.wl("# AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!(
            "# This file was generated by Djinni from {}",
            origins
        ));
        for td in types {
            w.wl("---");
            write_type_entry(w, spec, td);
        }
    });
}

fn write_yaml_single(
    spec: &Spec,
    out_files: &mut Vec<std::path::PathBuf>,
    written_files: &mut HashMap<String, String>,
    folder: &Path,
    file_name: &str,
    origin: &str,
    td: &TypeDecl,
) {
    crate::gen::create_file_from_parts(out_files, written_files, folder, file_name, |w| {
        *w = IndentWriter::with_indent("  ", "");
        w.wl("# AUTOGENERATED FILE - DO NOT MODIFY!");
        w.wl(&format!(
            "# This file was generated by Djinni from {}",
            origin
        ));
        write_type_entry(w, spec, td);
    });
}

fn write_type_entry(w: &mut IndentWriter, spec: &Spec, td: &TypeDecl) {
    // Preamble
    w.wl(&format!("name: {}{}", spec.yaml_prefix, td.ident().name));
    w.wl(&format!("typedef: '{}'", type_def_string(td.body())));
    let params: Vec<&str> = td
        .params()
        .iter()
        .map(|p| p.ident.name.as_str())
        .collect();
    w.wl(&format!("params: [{}]", params.join(",")));
    w.wl(&format!("prefix: {}", spec.yaml_prefix));

    // C++ section
    let cpp_marshal = CppMarshal::new(spec);
    w.wl("cpp:");
    w.nested(|w| {
        write_quoted(w, "typename", &cpp_marshal.fq_typename_from_name(&td.ident().name, td.body()));
        write_quoted(w, "header", &cpp_marshal.include(&td.ident().name, false));
        write_bool(w, "byValue", cpp_marshal.by_value_typedef(td.body()));
    });

    // ObjC section
    let objc_marshal = ObjcMarshal::new(spec);
    w.wl("objc:");
    w.nested(|w| {
        write_quoted(w, "typename", &objc_marshal.typename_from_name(&td.ident().name, td.body()));
        write_bool(w, "pointer", objc_marshal.is_pointer(td.body()));
        write_quoted(w, "hash", "%s.hash");
        write_quoted(w, "boxed", &objc_marshal.boxed_typename(&td.ident().name, td.body()));
        write_quoted(w, "header", &objc_marshal.include(&td.ident().name));
    });

    // ObjC++ section
    let objcpp_marshal = ObjcppMarshal::new(spec);
    let mexpr = make_mexpr(td);
    let meta = make_meta(td);
    w.wl("objcpp:");
    w.nested(|w| {
        write_quoted(w, "translator", &objcpp_marshal.helper_name_for_yaml(&mexpr));
        write_quoted(w, "header", &objcpp_marshal.include(&meta));
    });

    // Java section
    let java_marshal = JavaMarshal::new(spec, false);
    w.wl("java:");
    w.nested(|w| {
        write_bool(w, "reference", java_is_reference(td.body()));
        write_quoted(w, "typename", &java_marshal.fq_typename_from_name(&td.ident().name, td.body()));
        write_quoted(w, "writeToParcel", "%s.writeToParcel(out, flags)");
        write_bool(w, "generic", true);
        write_quoted(w, "readFromParcel", "new %s(in)");
        write_quoted(w, "hash", "%s.hashCode()");
        write_quoted(w, "boxed", &java_marshal.fq_typename_from_name(&td.ident().name, td.body()));
    });

    // JNI section
    let jni_marshal = JniMarshal::new(spec);
    w.wl("jni:");
    w.nested(|w| {
        write_quoted(w, "translator", &jni_marshal.helper_name(&mexpr));
        write_quoted(w, "header", &jni_marshal.include(&td.ident().name));
        write_plain(w, "typename", &jni_fq_param_type(&mexpr));
        write_quoted(w, "typeSignature", &jni_marshal.fq_typename_from_name(&td.ident().name, td.body()));
    });

    // WASM section
    w.wl("wasm:");
    w.nested(|w| {
        write_quoted(w, "translator", &wasm_helper_name(spec, &mexpr));
        write_quoted(w, "header", &wasm_include(spec, &td.ident().name));
        write_plain(w, "typename", &wasm_type(&mexpr));
    });

    // TS section
    w.wl("ts:");
    w.nested(|w| {
        write_plain(w, "typename", &ts_type_name(spec, &mexpr));
        write_quoted(w, "module", &format!("./{}", spec.ts_module));
    });
}

// --- YAML writing helpers ---

fn write_quoted(w: &mut IndentWriter, key: &str, value: &str) {
    if value.is_empty() {
        w.wl(&format!("{}: ''", key));
    } else {
        let escaped = value.replace('\'', "''");
        w.wl(&format!("{}: '{}'", key, escaped));
    }
}

fn write_plain(w: &mut IndentWriter, key: &str, value: &str) {
    if value.is_empty() {
        w.wl(&format!("{}: ''", key));
    } else {
        w.wl(&format!("{}: {}", key, value));
    }
}

fn write_bool(w: &mut IndentWriter, key: &str, value: bool) {
    w.wl(&format!("{}: {}", key, if value { "true" } else { "false" }));
}

// --- type_def string for YAML ---

fn type_def_string(td: &TypeDef) -> String {
    match td {
        TypeDef::Enum(e) => {
            if e.flags {
                "flags".to_string()
            } else {
                "enum".to_string()
            }
        }
        TypeDef::Record(r) => {
            let mut s = "record".to_string();
            if r.ext.cpp {
                s.push_str(" +c");
            }
            if r.ext.objc {
                s.push_str(" +o");
            }
            if r.ext.java {
                s.push_str(" +j");
            }
            if r.ext.js {
                s.push_str(" +w");
            }
            if !r.deriving_types.is_empty() {
                let derivings: Vec<&str> = r
                    .deriving_types
                    .iter()
                    .map(|d| match d {
                        DerivingType::Ord => "ord",
                        DerivingType::AndroidParcelable => "parcelable",
                        DerivingType::NSCopying => "nscopying",
                    })
                    .collect();
                s.push_str(&format!(" deriving({})", derivings.join(", ")));
            }
            s
        }
        TypeDef::Interface(i) => {
            let mut s = "interface".to_string();
            if i.ext.cpp {
                s.push_str(" +c");
            }
            if i.ext.objc {
                s.push_str(" +o");
            }
            if i.ext.java {
                s.push_str(" +j");
            }
            if i.ext.js {
                s.push_str(" +w");
            }
            s
        }
        TypeDef::ProtobufMessage(_) => "protobuf".to_string(),
    }
}

// --- Meta/MExpr construction for YAML ---

fn make_mexpr(td: &TypeDecl) -> MExpr {
    MExpr {
        base: make_meta(td),
        args: vec![],
    }
}

fn make_meta(td: &TypeDecl) -> Meta {
    let def_type = match td.body() {
        TypeDef::Interface(_) => DefType::Interface,
        TypeDef::Record(_) => DefType::Record,
        TypeDef::Enum(_) => DefType::Enum,
        TypeDef::ProtobufMessage(_) => panic!("protobuf not supported in YAML meta"),
    };
    Meta::MDef(MDef {
        name: td.ident().name.clone(),
        num_params: 0,
        def_type,
        body: td.body().clone(),
    })
}

// --- Java helpers ---

fn java_is_reference(_td: &TypeDef) -> bool {
    // In Scala, isReference returns true for non-primitive types.
    // All intern types (records, enums, interfaces) are references in Java.
    true
}

// --- JNI helpers ---

fn jni_fq_param_type(tm: &MExpr) -> String {
    // For intern types, JNI param type is always jobject
    match &tm.base {
        Meta::MDef(_) => "jobject".to_string(),
        _ => "jobject".to_string(),
    }
}

// --- WASM helpers (minimal, for YAML output only) ---

fn wasm_helper_name(spec: &Spec, tm: &MExpr) -> String {
    use crate::gen::with_ns;
    match &tm.base {
        Meta::MDef(d) => {
            let helper_class = (spec.jni_class_ident_style)(&d.name);
            with_ns(Some("djinni_generated"), &helper_class)
        }
        Meta::MExtern(e) => e.wasm.translator.clone(),
        _ => "[unspecified]".to_string(),
    }
}

fn wasm_include(spec: &Spec, ident: &str) -> String {
    use djinni_ast::spec::q;
    let file_name = (spec.jni_file_ident_style)(ident);
    q(&format!(
        "{}{}{}",
        spec.wasm_include_prefix, file_name, ".hpp"
    ))
}

fn wasm_type(tm: &MExpr) -> String {
    match &tm.base {
        Meta::MDef(d) => match d.def_type {
            DefType::Enum => "int32_t".to_string(),
            _ => "em::val".to_string(),
        },
        Meta::MExtern(e) => e.wasm.typename.clone(),
        Meta::MPrimitive(p) => p.c_name.clone(),
        Meta::MString => "std::string".to_string(),
        _ => "em::val".to_string(),
    }
}

// --- TS helpers (minimal, for YAML output only) ---

fn ts_type_name(spec: &Spec, tm: &MExpr) -> String {
    match &tm.base {
        Meta::MDef(d) => (spec.js_ident_style.ty)(&d.name),
        Meta::MExtern(e) => e.ts.typename.clone(),
        Meta::MPrimitive(p) => match p.idl_name.as_str() {
            "bool" => "boolean".to_string(),
            "i64" => "bigint".to_string(),
            _ => "number".to_string(),
        },
        Meta::MString => "string".to_string(),
        Meta::MDate => "Date".to_string(),
        Meta::MBinary => "Uint8Array".to_string(),
        _ => "any".to_string(),
    }
}
