// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

internal data class ChildItem(
    val _items: ArrayList<String>,
    val parent: String
) : ItemList(_items) {

    override fun toString(): String  {
        return "ChildItem {" +
                "items=" + items +
                "," + "parent=" + parent +
        "}"
    }

}
