// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

import java.util.ArrayList

internal open class ItemList(
    open val items: ArrayList<String>
) {

    override fun toString(): String  {
        return "ItemList {" +
                "items=" + items +
        "}"
    }

}
