// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

internal data class LevelF(
    override val fieldA: String,
    override val fieldB: String,
    override val fieldC: String,
    override val fieldD: String,
    override val fieldE: String,
    val fieldF: String
) : LevelE(fieldA, fieldB, fieldC, fieldD, fieldE) {

    override fun toString(): String  {
        return "LevelF {" +
                "fieldA=" + fieldA +
                "," + "fieldB=" + fieldB +
                "," + "fieldC=" + fieldC +
                "," + "fieldD=" + fieldD +
                "," + "fieldE=" + fieldE +
                "," + "fieldF=" + fieldF +
        "}"
    }

}
