// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

internal open class LevelC(
    override val fieldA: String,
    override val fieldB: String,
    open val fieldC: String
) : LevelB(fieldA, fieldB) {

    override fun toString(): String  {
        return "LevelC {" +
                "fieldA=" + fieldA +
                "," + "fieldB=" + fieldB +
                "," + "fieldC=" + fieldC +
        "}"
    }

}
