// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

internal open class LevelB(
    override val fieldA: String,
    open val fieldB: String
) : LevelA(fieldA) {

    override fun toString(): String  {
        return "LevelB {" +
                "fieldA=" + fieldA +
                "," + "fieldB=" + fieldB +
        "}"
    }

}
