// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

internal open class LevelD(
    override val fieldA: String,
    override val fieldB: String,
    override val fieldC: String,
    open val fieldD: String
) : LevelC(fieldA, fieldB, fieldC) {

    override fun toString(): String  {
        return "LevelD {" +
                "fieldA=" + fieldA +
                "," + "fieldB=" + fieldB +
                "," + "fieldC=" + fieldC +
                "," + "fieldD=" + fieldD +
        "}"
    }

}
