// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort

internal open class LevelA(
    open val fieldA: String
) {

    override fun toString(): String  {
        return "LevelA {" +
                "fieldA=" + fieldA +
        "}"
    }

}
