// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeLevelB.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLevelB::NativeLevelB() = default;

NativeLevelB::~NativeLevelB() = default;

auto NativeLevelB::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeLevelB>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.fieldA)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.fieldB)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeLevelB::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeLevelB>::get();
    ::textsort::LevelB model;
    model.fieldA = ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_fieldA));
    model.fieldB = ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_fieldB));
    return model;
}

} // namespace djinni_generated
