// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "sub_child_item.hpp"

namespace djinni_generated {

class NativeSubChildItem final {
public:
    using CppType = ::textsort::SubChildItem;
    using JniType = jobject;

    using Boxed = NativeSubChildItem;

    ~NativeSubChildItem();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSubChildItem();
    friend ::djinni::JniClass<NativeSubChildItem>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/textsort/SubChildItem") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;Ljava/lang/String;I)V") };
    const jfieldID field_items { ::djinni::jniGetFieldID(clazz.get(), "items", "Ljava/util/ArrayList;") };
    const jfieldID field_parent { ::djinni::jniGetFieldID(clazz.get(), "parent", "Ljava/lang/String;") };
    const jfieldID field_index { ::djinni::jniGetFieldID(clazz.get(), "index", "I") };
};

} // namespace djinni_generated
