// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "item_list.hpp"
#include <string>
#include <utility>

namespace textsort {

struct ChildItem : public ItemList {
    std::string parent;

    //NOLINTNEXTLINE(google-explicit-constructor)
    ChildItem(std::vector<std::string> items_,
              std::string parent_)
    : 
    ItemList( items_), parent(std::move(parent_)){}
};

} // namespace textsort
