// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include <string>
#include <utility>

namespace textsort {

struct LevelA {
    std::string fieldA;

    virtual ~LevelA(){};

    //NOLINTNEXTLINE(google-explicit-constructor)
    LevelA(std::string fieldA_)
    : fieldA(std::move(fieldA_))
    {}
};

} // namespace textsort
