// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "LevelC.hpp"
#include <string>
#include <utility>

namespace textsort {

struct LevelD : public LevelC {
    std::string fieldD;

    virtual ~LevelD(){};

    //NOLINTNEXTLINE(google-explicit-constructor)
    LevelD(std::string fieldA_,
           std::string fieldB_,
           std::string fieldC_,
           std::string fieldD_)
    : 
    LevelC( fieldA_,
            fieldB_,
            fieldC_), fieldD(std::move(fieldD_)){}
};

} // namespace textsort
