// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "LevelB.hpp"
#include <string>
#include <utility>

namespace textsort {

struct LevelC : public LevelB {
    std::string fieldC;

    virtual ~LevelC(){};

    //NOLINTNEXTLINE(google-explicit-constructor)
    LevelC(std::string fieldA_,
           std::string fieldB_,
           std::string fieldC_)
    : 
    LevelB( fieldA_,
            fieldB_), fieldC(std::move(fieldC_)){}
};

} // namespace textsort
