// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "LevelE.hpp"
#include <string>
#include <utility>

namespace textsort {

struct LevelF : public LevelE {
    std::string fieldF;

    //NOLINTNEXTLINE(google-explicit-constructor)
    LevelF(std::string fieldA_,
           std::string fieldB_,
           std::string fieldC_,
           std::string fieldD_,
           std::string fieldE_,
           std::string fieldF_)
    : 
    LevelE( fieldA_,
            fieldB_,
            fieldC_,
            fieldD_,
            fieldE_), fieldF(std::move(fieldF_)){}
};

} // namespace textsort
