// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// TextSort_Bridging_Header.h
// TextSort_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for TextSortBridgingHeader.
FOUNDATION_EXPORT double TextSortBridgingHeaderVersionNumber;

//! Project version string for TextSortBridgingHeader.
FOUNDATION_EXPORT const unsigned char TextSortBridgingHeaderVersionString[];

#import "TXSLevelA.h"
#import "TXSLevelB.h"
#import "TXSLevelC.h"
#import "TXSLevelD.h"
#import "TXSLevelE.h"
#import "TXSLevelF.h"
