// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSLevelE.h"
#include "LevelE.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSLevelE;

namespace djinni_generated {

struct LevelE
{
    using CppType = ::textsort::LevelE;
    using ObjcType = TXSLevelE*;

    using Boxed = LevelE;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
