// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSLevelA+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LevelA::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::textsort::LevelA model;
    model.fieldA = ::djinni::String::toCpp(obj.fieldA);
    return model;
}

auto LevelA::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSLevelA alloc] initWithFieldA:(::djinni::String::fromCpp(cpp.fieldA))];
}

} // namespace djinni_generated
