// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSLevelA.h"
#include "LevelA.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSLevelA;

namespace djinni_generated {

struct LevelA
{
    using CppType = ::textsort::LevelA;
    using ObjcType = TXSLevelA*;

    using Boxed = LevelA;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
