// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSLevelC+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LevelC::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::textsort::LevelC model;
    model.fieldA = ::djinni::String::toCpp(obj.fieldA);
    model.fieldB = ::djinni::String::toCpp(obj.fieldB);
    model.fieldC = ::djinni::String::toCpp(obj.fieldC);
    return model;
}

auto LevelC::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSLevelC alloc] initWithFieldA:(::djinni::String::fromCpp(cpp.fieldA))
                                      fieldB:(::djinni::String::fromCpp(cpp.fieldB))
                                      fieldC:(::djinni::String::fromCpp(cpp.fieldC))];
}

} // namespace djinni_generated
