// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

#import "TXSLevelE.h"
@interface TXSLevelF : TXSLevelE
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithFieldA:(nonnull NSString *)fieldA
                                fieldB:(nonnull NSString *)fieldB
                                fieldC:(nonnull NSString *)fieldC
                                fieldD:(nonnull NSString *)fieldD
                                fieldE:(nonnull NSString *)fieldE
                                fieldF:(nonnull NSString *)fieldF NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)LevelFWithFieldA:(nonnull NSString *)fieldA
                                  fieldB:(nonnull NSString *)fieldB
                                  fieldC:(nonnull NSString *)fieldC
                                  fieldD:(nonnull NSString *)fieldD
                                  fieldE:(nonnull NSString *)fieldE
                                  fieldF:(nonnull NSString *)fieldF;

@property (nonatomic, readonly, nonnull) NSString * fieldF;

@end
