// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSLevelC.h"


@implementation TXSLevelC

- (nonnull instancetype)initWithFieldA:(nonnull NSString *)fieldA
                                fieldB:(nonnull NSString *)fieldB
                                fieldC:(nonnull NSString *)fieldC
{
    if (self = [super initWithFieldA:fieldA
                              fieldB:fieldB])
    {
        _fieldC = [fieldC copy];
    }
    return self;
}

+ (nonnull instancetype)LevelCWithFieldA:(nonnull NSString *)fieldA
                                  fieldB:(nonnull NSString *)fieldB
                                  fieldC:(nonnull NSString *)fieldC
{
    return [[self alloc] initWithFieldA:fieldA
                                 fieldB:fieldB
                                 fieldC:fieldC];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p fieldA:%@ fieldB:%@ fieldC:%@>", self.class, (void *)self, self.fieldA, self.fieldB, self.fieldC];
}

#endif
@end
