// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSLevelD.h"
#include "LevelD.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSLevelD;

namespace djinni_generated {

struct LevelD
{
    using CppType = ::textsort::LevelD;
    using ObjcType = TXSLevelD*;

    using Boxed = LevelD;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
