// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

#import "TXSLevelB.h"
@interface TXSLevelC : TXSLevelB
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithFieldA:(nonnull NSString *)fieldA
                                fieldB:(nonnull NSString *)fieldB
                                fieldC:(nonnull NSString *)fieldC;
+ (nonnull instancetype)LevelCWithFieldA:(nonnull NSString *)fieldA
                                  fieldB:(nonnull NSString *)fieldB
                                  fieldC:(nonnull NSString *)fieldC;

@property (nonatomic, readonly, nonnull) NSString * fieldC;

@end
