// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSSubChildItem.h"
#include "sub_child_item.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSSubChildItem;

namespace djinni_generated {

struct SubChildItem
{
    using CppType = ::textsort::SubChildItem;
    using ObjcType = TXSSubChildItem*;

    using Boxed = SubChildItem;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
