// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSSubChildItem.h"


@implementation TXSSubChildItem

- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items
                               parent:(nonnull NSString *)parent
                                index:(int32_t)index
{
    if (self = [super initWithItems:items
                             parent:parent])
    {
        _index = index;
    }
    return self;
}

+ (nonnull instancetype)subChildItemWithItems:(nonnull NSArray<NSString *> *)items
                                       parent:(nonnull NSString *)parent
                                        index:(int32_t)index
{
    return [[self alloc] initWithItems:items
                                parent:parent
                                 index:index];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p items:%@ parent:%@ index:%@>", self.class, (void *)self, self.items, self.parent, @(self.index)];
}

#endif
@end
