// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSSubChildItem+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SubChildItem::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::textsort::SubChildItem model;
    model.items = ::djinni::List<::djinni::String>::toCpp(obj.items);
    model.parent = ::djinni::String::toCpp(obj.parent);
    model.index = ::djinni::I32::toCpp(obj.index);
    return model;
}

auto SubChildItem::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSSubChildItem alloc] initWithItems:(::djinni::List<::djinni::String>::fromCpp(cpp.items))
                                           parent:(::djinni::String::fromCpp(cpp.parent))
                                            index:(::djinni::I32::fromCpp(cpp.index))];
}

} // namespace djinni_generated
