// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from client_interface.djinni

#import "DBClientReturnedRecord.h"
#import "DjinniUtils.h"


@implementation DBClientReturnedRecord

- (nonnull instancetype)initWithRecordId:(int64_t)recordId
                                 content:(nonnull NSString *)content
                                    misc:(nullable NSString *)misc
{
    if (self = [super init]) {
        _recordId = recordId;
        _content = [content copy];
        _misc = [misc copy];
    }
    return self;
}

+ (nonnull instancetype)clientReturnedRecordWithRecordId:(int64_t)recordId
                                                 content:(nonnull NSString *)content
                                                    misc:(nullable NSString *)misc
{
    return [[self alloc] initWithRecordId:recordId
                                  content:content
                                     misc:misc];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBClientReturnedRecord class]]) {
        return NO;
    }
    DBClientReturnedRecord *typedOther = (DBClientReturnedRecord *)other;
    return self.recordId == typedOther.recordId &&
            [self.content isEqualToString:typedOther.content] &&
            ((self.misc == nil && typedOther.misc == nil) || (self.misc != nil && [self.misc isEqual:typedOther.misc]));
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.recordId;
    hashCode = hashCode * 31 + self.content.hash;
    hashCode = hashCode * 31 + self.misc.hash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p recordId:%@ content:%@ misc:%@>", self.class, (void *)self, @(self.recordId), self.content, self.misc];
}

#endif
@end
