// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from date.djinni

#import "DBDateRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto DateRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::DateRecord model;
    model.mCreatedAt = ::djinni::Date::toCpp(obj.createdAt);
    return model;
}

auto DateRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBDateRecord alloc] initWithCreatedAt:(::djinni::Date::fromCpp(cpp.created_at))];
}

} // namespace djinni_generated
