// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

#import "DBExtendedRecord.h"
#import "DjinniUtils.h"


@implementation DBExtendedRecord

- (nonnull instancetype)initWithFoo:(BOOL)foo
{
    if (self = [super init]) {
        _foo = foo;
    }
    return self;
}

+ (nonnull instancetype)extendedRecordWithFoo:(BOOL)foo
{
    return [[self alloc] initWithFoo:foo];
}

+ (DBExtendedRecord * __nonnull)extendedRecordConst
{
    static DBExtendedRecord * const s_extendedRecordConst = [[DBExtendedRecord alloc] initWithFoo:YES];
    return s_extendedRecordConst;
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBExtendedRecord class]]) {
        return NO;
    }
    DBExtendedRecord *typedOther = (DBExtendedRecord *)other;
    return self.foo == typedOther.foo;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.foo;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p foo:%@>", self.class, (void *)self, @(self.foo)];
}

#endif
@end
