// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map.djinni

#import "DBMapRecord.h"
#import "DjinniUtils.h"


@implementation DBMapRecord

- (nonnull instancetype)initWithMap:(nonnull NSDictionary<NSString *, NSNumber *> *)map
                               imap:(nonnull NSDictionary<NSNumber *, NSNumber *> *)imap
{
    if (self = [super init]) {
        _map = [map copy];
        _imap = [imap copy];
    }
    return self;
}

+ (nonnull instancetype)mapRecordWithMap:(nonnull NSDictionary<NSString *, NSNumber *> *)map
                                    imap:(nonnull NSDictionary<NSNumber *, NSNumber *> *)imap
{
    return [[self alloc] initWithMap:map
                                imap:imap];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBMapRecord class]]) {
        return NO;
    }
    DBMapRecord *typedOther = (DBMapRecord *)other;
    return [self.map isEqualToDictionary:typedOther.map] &&
            [self.imap isEqualToDictionary:typedOther.imap];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.map.hash;
    hashCode = hashCode * 31 + self.imap.hash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p map:%@ imap:%@>", self.class, (void *)self, self.map, self.imap];
}

#endif
@end
