// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from outcome.djinni

#import "DBNestedOutcome.h"
#import "DjinniUtils.h"


@implementation DBNestedOutcome

- (nonnull instancetype)initWithO:(nonnull DJOutcome<NSNumber *, NSString *> *)o
{
    if (self = [super init]) {
        _o = o;
    }
    return self;
}

+ (nonnull instancetype)nestedOutcomeWithO:(nonnull DJOutcome<NSNumber *, NSString *> *)o
{
    return [[self alloc] initWithO:o];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBNestedOutcome class]]) {
        return NO;
    }
    DBNestedOutcome *typedOther = (DBNestedOutcome *)other;
    return [self.o isEqual:typedOther.o];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (self.o.hash);
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p o:%@>", self.class, (void *)self, self.o];
}

#endif
@end
