// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from nested_collection.djinni

#import "DBNestedCollection.h"
#import "DjinniUtils.h"


@implementation DBNestedCollection

- (nonnull instancetype)initWithSetList:(nonnull NSArray<NSSet<NSString *> *> *)setList
{
    if (self = [super init]) {
        _setList = [setList copy];
    }
    return self;
}

+ (nonnull instancetype)nestedCollectionWithSetList:(nonnull NSArray<NSSet<NSString *> *> *)setList
{
    return [[self alloc] initWithSetList:setList];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBNestedCollection class]]) {
        return NO;
    }
    DBNestedCollection *typedOther = (DBNestedCollection *)other;
    return [self.setList isEqualToArray:typedOther.setList];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.setList.dynamicHash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p setList:%@>", self.class, (void *)self, self.setList];
}

#endif
@end
