// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proto.djinni

#import "DBRecordWithEmbeddedProto.h"
#import "DjinniUtils.h"


@implementation DBRecordWithEmbeddedProto

- (nonnull instancetype)initWithPerson:(nonnull DJTestPerson *)person
{
    if (self = [super init]) {
        _person = person;
    }
    return self;
}

+ (nonnull instancetype)RecordWithEmbeddedProtoWithPerson:(nonnull DJTestPerson *)person
{
    return [[self alloc] initWithPerson:person];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBRecordWithEmbeddedProto class]]) {
        return NO;
    }
    DBRecordWithEmbeddedProto *typedOther = (DBRecordWithEmbeddedProto *)other;
    return ;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + ();
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p person:%@>", self.class, (void *)self, self.person];
}

#endif
@end
