// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extended_record.djinni

#import "DBRecordUsingExtendedRecord+Private.h"
#import "DBExtendedRecord+Private.h"
#include <cassert>

namespace djinni_generated {

auto RecordUsingExtendedRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::RecordUsingExtendedRecord model;
    model.mEr = ::djinni_generated::ExtendedRecord::toCpp(obj.er);
    return model;
}

auto RecordUsingExtendedRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBRecordUsingExtendedRecord alloc] initWithEr:(::djinni_generated::ExtendedRecord::fromCpp(cpp.er))];
}

} // namespace djinni_generated
