// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from derivings.djinni

#import "DBRecordWithDerivings+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RecordWithDerivings::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::RecordWithDerivings model;
    model.mEight = ::djinni::I8::toCpp(obj.eight);
    model.mSixteen = ::djinni::I16::toCpp(obj.sixteen);
    model.mThirtytwo = ::djinni::I32::toCpp(obj.thirtytwo);
    model.mSixtyfour = ::djinni::I64::toCpp(obj.sixtyfour);
    model.mFthirtytwo = ::djinni::F32::toCpp(obj.fthirtytwo);
    model.mFsixtyfour = ::djinni::F64::toCpp(obj.fsixtyfour);
    model.mD = ::djinni::Date::toCpp(obj.d);
    model.mS = ::djinni::String::toCpp(obj.s);
    return model;
}

auto RecordWithDerivings::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBRecordWithDerivings alloc] initWithEight:(::djinni::I8::fromCpp(cpp.eight))
                                                sixteen:(::djinni::I16::fromCpp(cpp.sixteen))
                                              thirtytwo:(::djinni::I32::fromCpp(cpp.thirtytwo))
                                              sixtyfour:(::djinni::I64::fromCpp(cpp.sixtyfour))
                                             fthirtytwo:(::djinni::F32::fromCpp(cpp.fthirtytwo))
                                             fsixtyfour:(::djinni::F64::fromCpp(cpp.fsixtyfour))
                                                      d:(::djinni::Date::fromCpp(cpp.d))
                                                      s:(::djinni::String::fromCpp(cpp.s))];
}

} // namespace djinni_generated
