// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni

#import "DBRecordWithFlags.h"
#import "DjinniUtils.h"


@implementation DBRecordWithFlags

- (nonnull instancetype)initWithAccess:(DBAccessFlags)access
{
    if (self = [super init]) {
        _access = access;
    }
    return self;
}

+ (nonnull instancetype)recordWithFlagsWithAccess:(DBAccessFlags)access
{
    return [[self alloc] initWithAccess:access];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBRecordWithFlags class]]) {
        return NO;
    }
    DBRecordWithFlags *typedOther = (DBRecordWithFlags *)other;
    return self.access == typedOther.access;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.access;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p access:%@>", self.class, (void *)self, @(self.access)];
}

#endif
@end
