// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestSingleField.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestSingleField

- (nonnull instancetype)initWithValue:(nonnull NSString *)value
{
    if (self = [super init]) {
        _value = [value copy];
    }
    return self;
}

+ (nonnull instancetype)swiftTestSingleFieldWithValue:(nonnull NSString *)value
{
    return [[self alloc] initWithValue:value];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestSingleField class]]) {
        return NO;
    }
    DBSwiftTestSingleField *typedOther = (DBSwiftTestSingleField *)other;
    return [self.value isEqualToString:typedOther.value];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.value.hash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p value:%@>", self.class, (void *)self, self.value];
}

#endif
@end
