// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestExternRecord.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestExternRecord

- (nonnull instancetype)initWithBackgroundColor:(nonnull UIColor *)backgroundColor
                                      labelText:(nonnull SmartString *)labelText
                                           icon:(nonnull ImageViewModel *)icon
                                         action:(nonnull UserAction *)action
{
    if (self = [super init]) {
        _backgroundColor = backgroundColor;
        _labelText = labelText;
        _icon = icon;
        _action = action;
    }
    return self;
}

+ (nonnull instancetype)swiftTestExternRecordWithBackgroundColor:(nonnull UIColor *)backgroundColor
                                                       labelText:(nonnull SmartString *)labelText
                                                            icon:(nonnull ImageViewModel *)icon
                                                          action:(nonnull UserAction *)action
{
    return [[self alloc] initWithBackgroundColor:backgroundColor
                                       labelText:labelText
                                            icon:icon
                                          action:action];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestExternRecord class]]) {
        return NO;
    }
    DBSwiftTestExternRecord *typedOther = (DBSwiftTestExternRecord *)other;
    return [self.backgroundColor isEqual:typedOther.backgroundColor] &&
            [self.labelText isEqual:typedOther.labelText] &&
            [self.icon isEqual:typedOther.icon] &&
            [self.action isEqual:typedOther.action];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (self.backgroundColor.hash);
    hashCode = hashCode * 31 + (self.labelText.hash);
    hashCode = hashCode * 31 + (self.icon.hash);
    hashCode = hashCode * 31 + (self.action.hash);
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p backgroundColor:%@ labelText:%@ icon:%@ action:%@>", self.class, (void *)self, self.backgroundColor, self.labelText, self.icon, self.action];
}

#endif
@end
