// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestSingleField+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestSingleField::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestSingleField model;
    model.mValue = ::djinni::String::toCpp(obj.value);
    return model;
}

auto SwiftTestSingleField::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestSingleField alloc] initWithValue:(::djinni::String::fromCpp(cpp.value))];
}

} // namespace djinni_generated
