// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestDocumented+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestDocumented::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestDocumented model;
    model.mText = ::djinni::String::toCpp(obj.text);
    model.mVisible = ::djinni::Bool::toCpp(obj.visible);
    return model;
}

auto SwiftTestDocumented::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestDocumented alloc] initWithText:(::djinni::String::fromCpp(cpp.text))
                                               visible:(::djinni::Bool::fromCpp(cpp.visible))];
}

} // namespace djinni_generated
