// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestAllPrimitives+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestAllPrimitives::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestAllPrimitives model;
    model.mMyBool = ::djinni::Bool::toCpp(obj.myBool);
    model.mMyI8 = ::djinni::I8::toCpp(obj.myI8);
    model.mMyI16 = ::djinni::I16::toCpp(obj.myI16);
    model.mMyI32 = ::djinni::I32::toCpp(obj.myI32);
    model.mMyI64 = ::djinni::I64::toCpp(obj.myI64);
    model.mMyF32 = ::djinni::F32::toCpp(obj.myF32);
    model.mMyF64 = ::djinni::F64::toCpp(obj.myF64);
    model.mMyString = ::djinni::String::toCpp(obj.myString);
    model.mMyBinary = ::djinni::Binary::toCpp(obj.myBinary);
    model.mMyDate = ::djinni::Date::toCpp(obj.myDate);
    return model;
}

auto SwiftTestAllPrimitives::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestAllPrimitives alloc] initWithMyBool:(::djinni::Bool::fromCpp(cpp.my_bool))
                                                       myI8:(::djinni::I8::fromCpp(cpp.my_i8))
                                                      myI16:(::djinni::I16::fromCpp(cpp.my_i16))
                                                      myI32:(::djinni::I32::fromCpp(cpp.my_i32))
                                                      myI64:(::djinni::I64::fromCpp(cpp.my_i64))
                                                      myF32:(::djinni::F32::fromCpp(cpp.my_f32))
                                                      myF64:(::djinni::F64::fromCpp(cpp.my_f64))
                                                   myString:(::djinni::String::fromCpp(cpp.my_string))
                                                   myBinary:(::djinni::Binary::fromCpp(cpp.my_binary))
                                                     myDate:(::djinni::Date::fromCpp(cpp.my_date))];
}

} // namespace djinni_generated
