// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestColor.h"
#import "DBSwiftTestLabel.h"
#import "DBSwiftTestTextStyle.h"
#import <Foundation/Foundation.h>

/**
 * ============================================================
 * Test: Nested records
 * Verifies: correct type references between generated types
 * ============================================================
 */
@interface DBSwiftTestNested : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithLabel:(nonnull DBSwiftTestLabel *)label
                                color:(DBSwiftTestColor)color
                                style:(nonnull DBSwiftTestTextStyle *)style NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)swiftTestNestedWithLabel:(nonnull DBSwiftTestLabel *)label
                                           color:(DBSwiftTestColor)color
                                           style:(nonnull DBSwiftTestTextStyle *)style;

@property (nonatomic, readonly, nonnull) DBSwiftTestLabel * label;

@property (nonatomic, readonly) DBSwiftTestColor color;

@property (nonatomic, readonly, nonnull) DBSwiftTestTextStyle * style;

@end
