// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestLabel.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestLabel

- (nonnull instancetype)initWithTextColor:(int32_t)textColor
                                 fontSize:(float)fontSize
                                     text:(nonnull NSString *)text
                                   isBold:(BOOL)isBold
{
    if (self = [super initWithTextColor:textColor
                               fontSize:fontSize])
    {
        _text = [text copy];
        _isBold = isBold;
    }
    return self;
}

+ (nonnull instancetype)swiftTestLabelWithTextColor:(int32_t)textColor
                                           fontSize:(float)fontSize
                                               text:(nonnull NSString *)text
                                             isBold:(BOOL)isBold
{
    return [[self alloc] initWithTextColor:textColor
                                  fontSize:fontSize
                                      text:text
                                    isBold:isBold];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestLabel class]]) {
        return NO;
    }
    DBSwiftTestLabel *typedOther = (DBSwiftTestLabel *)other;
    return self.textColor == typedOther.textColor &&
            self.fontSize == typedOther.fontSize &&
            [self.text isEqualToString:typedOther.text] &&
            self.isBold == typedOther.isBold;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.textColor;
    hashCode = hashCode * 31 + [NSNumber numberWithFloat:self.fontSize].hash;
    hashCode = hashCode * 31 + self.text.hash;
    hashCode = hashCode * 31 + (NSUInteger)self.isBold;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p textColor:%@ fontSize:%@ text:%@ isBold:%@>", self.class, (void *)self, @(self.textColor), @(self.fontSize), self.text, @(self.isBold)];
}

#endif
@end
