// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestTextStyle+Private.h"
#import "DBSwiftTestLetterCase+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestTextStyle::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestTextStyle model;
    model.mColor = ::djinni::I32::toCpp(obj.color);
    model.mLetterCase = ::djinni::Enum<::testsuite::SwiftTestLetterCase, DBSwiftTestLetterCase>::toCpp(obj.letterCase);
    return model;
}

auto SwiftTestTextStyle::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestTextStyle alloc] initWithColor:(::djinni::I32::fromCpp(cpp.color))
                                            letterCase:(::djinni::Enum<::testsuite::SwiftTestLetterCase, DBSwiftTestLetterCase>::fromCpp(cpp.letter_case))];
}

} // namespace djinni_generated
