// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestExternOptional+Private.h"
#import "DJIMarshal+Private.h"
#import "TestColorTranslator.h"
#import "UserActionTranslator.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestExternOptional::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestExternOptional model;
    model.mName = ::djinni::String::toCpp(obj.name);
    model.mOptColor = ::djinni::Optional<std::optional, ::djinni::TestColorTranslator>::toCpp(obj.optColor);
    model.mOptAction = ::djinni::Optional<std::optional, ::djinni::UserActionTranslator>::toCpp(obj.optAction);
    return model;
}

auto SwiftTestExternOptional::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestExternOptional alloc] initWithName:(::djinni::String::fromCpp(cpp.name))
                                                  optColor:(::djinni::Optional<std::optional, ::djinni::TestColorTranslator>::fromCpp(cpp.opt_color))
                                                 optAction:(::djinni::Optional<std::optional, ::djinni::UserActionTranslator>::fromCpp(cpp.opt_action))];
}

} // namespace djinni_generated
