// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestExternOptional.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestExternOptional

- (nonnull instancetype)initWithName:(nonnull NSString *)name
                            optColor:(nullable UIColor *)optColor
                           optAction:(nullable UserAction *)optAction
{
    if (self = [super init]) {
        _name = [name copy];
        _optColor = optColor;
        _optAction = optAction;
    }
    return self;
}

+ (nonnull instancetype)swiftTestExternOptionalWithName:(nonnull NSString *)name
                                               optColor:(nullable UIColor *)optColor
                                              optAction:(nullable UserAction *)optAction
{
    return [[self alloc] initWithName:name
                             optColor:optColor
                            optAction:optAction];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestExternOptional class]]) {
        return NO;
    }
    DBSwiftTestExternOptional *typedOther = (DBSwiftTestExternOptional *)other;
    return [self.name isEqualToString:typedOther.name] &&
            ((self.optColor == nil && typedOther.optColor == nil) || (self.optColor != nil && [self.optColor isEqual:typedOther.optColor])) &&
            ((self.optAction == nil && typedOther.optAction == nil) || (self.optAction != nil && [self.optAction isEqual:typedOther.optAction]));
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.name.hash;
    hashCode = hashCode * 31 + self.optColor.hash;
    hashCode = hashCode * 31 + self.optAction.hash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p name:%@ optColor:%@ optAction:%@>", self.class, (void *)self, self.name, self.optColor, self.optAction];
}

#endif
@end
