// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestLetterCase.h"
#import <Foundation/Foundation.h>

@interface DBSwiftTestTextStyle : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithColor:(int32_t)color
                           letterCase:(DBSwiftTestLetterCase)letterCase NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)swiftTestTextStyleWithColor:(int32_t)color
                                         letterCase:(DBSwiftTestLetterCase)letterCase;

@property (nonatomic, readonly) int32_t color;

@property (nonatomic, readonly) DBSwiftTestLetterCase letterCase;

@end
