// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestDocumented.h"
#include "swift_test_documented.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestDocumented;

namespace djinni_generated {

struct SwiftTestDocumented
{
    using CppType = ::testsuite::SwiftTestDocumented;
    using ObjcType = DBSwiftTestDocumented*;

    using Boxed = SwiftTestDocumented;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
