// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestColor.h"
#import <Foundation/Foundation.h>

/**
 * ============================================================
 * Test: Collection types
 * Verifies: list -> [T], set -> Set<T>, map -> [K: V]
 * ============================================================
 */
@interface DBSwiftTestCollections : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithStringList:(nonnull NSArray<NSString *> *)stringList
                                    intSet:(nonnull NSSet<NSNumber *> *)intSet
                            stringToIntMap:(nonnull NSDictionary<NSString *, NSNumber *> *)stringToIntMap
                                nestedList:(nonnull NSArray<NSArray<NSString *> *> *)nestedList
                                  enumList:(nonnull NSArray<NSNumber *> *)enumList
                                   enumMap:(nonnull NSDictionary<NSNumber *, NSString *> *)enumMap NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)swiftTestCollectionsWithStringList:(nonnull NSArray<NSString *> *)stringList
                                                    intSet:(nonnull NSSet<NSNumber *> *)intSet
                                            stringToIntMap:(nonnull NSDictionary<NSString *, NSNumber *> *)stringToIntMap
                                                nestedList:(nonnull NSArray<NSArray<NSString *> *> *)nestedList
                                                  enumList:(nonnull NSArray<NSNumber *> *)enumList
                                                   enumMap:(nonnull NSDictionary<NSNumber *, NSString *> *)enumMap;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * stringList;

@property (nonatomic, readonly, nonnull) NSSet<NSNumber *> * intSet;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSNumber *> * stringToIntMap;

@property (nonatomic, readonly, nonnull) NSArray<NSArray<NSString *> *> * nestedList;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * enumList;

@property (nonatomic, readonly, nonnull) NSDictionary<NSNumber *, NSString *> * enumMap;

@end
