// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestNested+Private.h"
#import "DBSwiftTestColor+Private.h"
#import "DBSwiftTestLabel+Private.h"
#import "DBSwiftTestTextStyle+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestNested::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestNested model;
    model.mLabel = ::djinni_generated::SwiftTestLabel::toCpp(obj.label);
    model.mColor = ::djinni::Enum<::testsuite::SwiftTestColor, DBSwiftTestColor>::toCpp(obj.color);
    model.mStyle = ::djinni_generated::SwiftTestTextStyle::toCpp(obj.style);
    return model;
}

auto SwiftTestNested::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestNested alloc] initWithLabel:(::djinni_generated::SwiftTestLabel::fromCpp(cpp.label))
                                              color:(::djinni::Enum<::testsuite::SwiftTestColor, DBSwiftTestColor>::fromCpp(cpp.color))
                                              style:(::djinni_generated::SwiftTestTextStyle::fromCpp(cpp.style))];
}

} // namespace djinni_generated
