// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestExternRecord.h"
#include "swift_test_extern_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestExternRecord;

namespace djinni_generated {

struct SwiftTestExternRecord
{
    using CppType = ::testsuite::SwiftTestExternRecord;
    using ObjcType = DBSwiftTestExternRecord*;

    using Boxed = SwiftTestExternRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
