// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestLabel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestLabel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestLabel model;
    model.mTextColor = ::djinni::I32::toCpp(obj.textColor);
    model.mFontSize = ::djinni::F32::toCpp(obj.fontSize);
    model.mText = ::djinni::String::toCpp(obj.text);
    model.mIsBold = ::djinni::Bool::toCpp(obj.isBold);
    return model;
}

auto SwiftTestLabel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestLabel alloc] initWithTextColor:(::djinni::I32::fromCpp(cpp.text_color))
                                              fontSize:(::djinni::F32::fromCpp(cpp.font_size))
                                                  text:(::djinni::String::fromCpp(cpp.text))
                                                isBold:(::djinni::Bool::fromCpp(cpp.is_bold))];
}

} // namespace djinni_generated
