// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestCollections.h"
#include "swift_test_collections.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestCollections;

namespace djinni_generated {

struct SwiftTestCollections
{
    using CppType = ::testsuite::SwiftTestCollections;
    using ObjcType = DBSwiftTestCollections*;

    using Boxed = SwiftTestCollections;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
