// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestEmpty.h"
#import "DjinniUtils.h"


int32_t const DBSwiftTestEmptySomeConst = 42;

@implementation DBSwiftTestEmpty

- (nonnull instancetype)init
{
    if (self = [super init]) {
    }
    return self;
}

+ (nonnull instancetype)swiftTestEmpty
{
    return [[self alloc] init];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestEmpty class]]) {
        return NO;
    }
    return YES;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p>", self.class, (void *)self];
}

#endif
@end
