// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestAllPrimitives.h"
#include "swift_test_all_primitives.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestAllPrimitives;

namespace djinni_generated {

struct SwiftTestAllPrimitives
{
    using CppType = ::testsuite::SwiftTestAllPrimitives;
    using ObjcType = DBSwiftTestAllPrimitives*;

    using Boxed = SwiftTestAllPrimitives;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
