// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestInterface+Private.h"
#import "DBSwiftTestInterface.h"
#import "DBSwiftTestColor+Private.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DBSwiftTestInterface ()

- (id)initWithCpp:(const std::shared_ptr<::testsuite::SwiftTestInterface>&)cppRef;

@end

@implementation DBSwiftTestInterface {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::testsuite::SwiftTestInterface>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::testsuite::SwiftTestInterface>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull NSString *)doSomething:(nonnull NSString *)input {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->do_something(::djinni::String::toCpp(input));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (DBSwiftTestColor)getColor {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get_color();
        return ::djinni::Enum<::testsuite::SwiftTestColor, DBSwiftTestColor>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SwiftTestInterface::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SwiftTestInterface::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DBSwiftTestInterface>(cpp);
}

} // namespace djinni_generated

@end
