// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestBaseLabel.h"
#include "swift_test_base_label.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestBaseLabel;

namespace djinni_generated {

struct SwiftTestBaseLabel
{
    using CppType = ::testsuite::SwiftTestBaseLabel;
    using ObjcType = DBSwiftTestBaseLabel*;

    using Boxed = SwiftTestBaseLabel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
