// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestSingleField.h"
#include "swift_test_single_field.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestSingleField;

namespace djinni_generated {

struct SwiftTestSingleField
{
    using CppType = ::testsuite::SwiftTestSingleField;
    using ObjcType = DBSwiftTestSingleField*;

    using Boxed = SwiftTestSingleField;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
