// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import <Foundation/Foundation.h>

/**
 * ============================================================
 * Test: All primitive types in a single record
 * Verifies: type mapping for every primitive
 * ============================================================
 */
@interface DBSwiftTestAllPrimitives : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithMyBool:(BOOL)myBool
                                  myI8:(int8_t)myI8
                                 myI16:(int16_t)myI16
                                 myI32:(int32_t)myI32
                                 myI64:(int64_t)myI64
                                 myF32:(float)myF32
                                 myF64:(double)myF64
                              myString:(nonnull NSString *)myString
                              myBinary:(nonnull NSData *)myBinary
                                myDate:(nonnull NSDate *)myDate NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)swiftTestAllPrimitivesWithMyBool:(BOOL)myBool
                                                    myI8:(int8_t)myI8
                                                   myI16:(int16_t)myI16
                                                   myI32:(int32_t)myI32
                                                   myI64:(int64_t)myI64
                                                   myF32:(float)myF32
                                                   myF64:(double)myF64
                                                myString:(nonnull NSString *)myString
                                                myBinary:(nonnull NSData *)myBinary
                                                  myDate:(nonnull NSDate *)myDate;

@property (nonatomic, readonly) BOOL myBool;

@property (nonatomic, readonly) int8_t myI8;

@property (nonatomic, readonly) int16_t myI16;

@property (nonatomic, readonly) int32_t myI32;

@property (nonatomic, readonly) int64_t myI64;

@property (nonatomic, readonly) float myF32;

@property (nonatomic, readonly) double myF64;

@property (nonatomic, readonly, nonnull) NSString * myString;

@property (nonatomic, readonly, nonnull) NSData * myBinary;

@property (nonatomic, readonly, nonnull) NSDate * myDate;

@end
