// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestExternRecord+Private.h"
#import "ImageViewModelTranslator.h"
#import "SmartStringTranslator.h"
#import "TestColorTranslator.h"
#import "UserActionTranslator.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestExternRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestExternRecord model;
    model.mBackgroundColor = ::djinni::TestColorTranslator::toCpp(obj.backgroundColor);
    model.mLabelText = ::djinni::SmartStringTranslator::toCpp(obj.labelText);
    model.mIcon = ::djinni::ImageViewModelTranslator::toCpp(obj.icon);
    model.mAction = ::djinni::UserActionTranslator::toCpp(obj.action);
    return model;
}

auto SwiftTestExternRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestExternRecord alloc] initWithBackgroundColor:(::djinni::TestColorTranslator::fromCpp(cpp.background_color))
                                                          labelText:(::djinni::SmartStringTranslator::fromCpp(cpp.label_text))
                                                               icon:(::djinni::ImageViewModelTranslator::fromCpp(cpp.icon))
                                                             action:(::djinni::UserActionTranslator::fromCpp(cpp.action))];
}

} // namespace djinni_generated
