// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestTextStyle.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestTextStyle

- (nonnull instancetype)initWithColor:(int32_t)color
                           letterCase:(DBSwiftTestLetterCase)letterCase
{
    if (self = [super init]) {
        _color = color;
        _letterCase = letterCase;
    }
    return self;
}

+ (nonnull instancetype)swiftTestTextStyleWithColor:(int32_t)color
                                         letterCase:(DBSwiftTestLetterCase)letterCase
{
    return [[self alloc] initWithColor:color
                            letterCase:letterCase];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestTextStyle class]]) {
        return NO;
    }
    DBSwiftTestTextStyle *typedOther = (DBSwiftTestTextStyle *)other;
    return self.color == typedOther.color &&
            self.letterCase == typedOther.letterCase;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.color;
    hashCode = hashCode * 31 + (NSUInteger)self.letterCase;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p color:%@ letterCase:%@>", self.class, (void *)self, @(self.color), @(self.letterCase)];
}

#endif
@end
