// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestTextStyle.h"
#include "swift_test_text_style.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestTextStyle;

namespace djinni_generated {

struct SwiftTestTextStyle
{
    using CppType = ::testsuite::SwiftTestTextStyle;
    using ObjcType = DBSwiftTestTextStyle*;

    using Boxed = SwiftTestTextStyle;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
