// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestOptionals+Private.h"
#import "DBSwiftTestAllPrimitives+Private.h"
#import "DBSwiftTestColor+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestOptionals::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestOptionals model;
    model.mRequiredField = ::djinni::String::toCpp(obj.requiredField);
    model.mOptionalString = ::djinni::Optional<std::optional, ::djinni::String>::toCpp(obj.optionalString);
    model.mOptionalInt = ::djinni::Optional<std::optional, ::djinni::I32>::toCpp(obj.optionalInt);
    model.mOptionalEnum = ::djinni::Optional<std::optional, ::djinni::Enum<::testsuite::SwiftTestColor, DBSwiftTestColor>>::toCpp(obj.optionalEnum);
    model.mOptionalRecord = ::djinni::Optional<std::optional, ::djinni_generated::SwiftTestAllPrimitives>::toCpp(obj.optionalRecord);
    model.mOptionalList = ::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::toCpp(obj.optionalList);
    return model;
}

auto SwiftTestOptionals::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestOptionals alloc] initWithRequiredField:(::djinni::String::fromCpp(cpp.required_field))
                                                optionalString:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(cpp.optional_string))
                                                   optionalInt:(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(cpp.optional_int))
                                                  optionalEnum:(::djinni::Optional<std::optional, ::djinni::Enum<::testsuite::SwiftTestColor, DBSwiftTestColor>>::fromCpp(cpp.optional_enum))
                                                optionalRecord:(::djinni::Optional<std::optional, ::djinni_generated::SwiftTestAllPrimitives>::fromCpp(cpp.optional_record))
                                                  optionalList:(::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::fromCpp(cpp.optional_list))];
}

} // namespace djinni_generated
