// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestNested.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestNested

- (nonnull instancetype)initWithLabel:(nonnull DBSwiftTestLabel *)label
                                color:(DBSwiftTestColor)color
                                style:(nonnull DBSwiftTestTextStyle *)style
{
    if (self = [super init]) {
        _label = label;
        _color = color;
        _style = style;
    }
    return self;
}

+ (nonnull instancetype)swiftTestNestedWithLabel:(nonnull DBSwiftTestLabel *)label
                                           color:(DBSwiftTestColor)color
                                           style:(nonnull DBSwiftTestTextStyle *)style
{
    return [[self alloc] initWithLabel:label
                                 color:color
                                 style:style];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestNested class]]) {
        return NO;
    }
    DBSwiftTestNested *typedOther = (DBSwiftTestNested *)other;
    return [self.label isEqual:typedOther.label] &&
            self.color == typedOther.color &&
            [self.style isEqual:typedOther.style];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.label.hash;
    hashCode = hashCode * 31 + (NSUInteger)self.color;
    hashCode = hashCode * 31 + self.style.hash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p label:%@ color:%@ style:%@>", self.class, (void *)self, self.label, @(self.color), self.style];
}

#endif
@end
