// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestExternOptional.h"
#include "swift_test_extern_optional.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestExternOptional;

namespace djinni_generated {

struct SwiftTestExternOptional
{
    using CppType = ::testsuite::SwiftTestExternOptional;
    using ObjcType = DBSwiftTestExternOptional*;

    using Boxed = SwiftTestExternOptional;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
