// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestOptionals.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestOptionals

- (nonnull instancetype)initWithRequiredField:(nonnull NSString *)requiredField
                               optionalString:(nullable NSString *)optionalString
                                  optionalInt:(nullable NSNumber *)optionalInt
                                 optionalEnum:(nullable NSNumber *)optionalEnum
                               optionalRecord:(nullable DBSwiftTestAllPrimitives *)optionalRecord
                                 optionalList:(nullable NSArray<NSString *> *)optionalList
{
    if (self = [super init]) {
        _requiredField = [requiredField copy];
        _optionalString = [optionalString copy];
        _optionalInt = optionalInt;
        _optionalEnum = optionalEnum;
        _optionalRecord = optionalRecord;
        _optionalList = [optionalList copy];
    }
    return self;
}

+ (nonnull instancetype)swiftTestOptionalsWithRequiredField:(nonnull NSString *)requiredField
                                             optionalString:(nullable NSString *)optionalString
                                                optionalInt:(nullable NSNumber *)optionalInt
                                               optionalEnum:(nullable NSNumber *)optionalEnum
                                             optionalRecord:(nullable DBSwiftTestAllPrimitives *)optionalRecord
                                               optionalList:(nullable NSArray<NSString *> *)optionalList
{
    return [[self alloc] initWithRequiredField:requiredField
                                optionalString:optionalString
                                   optionalInt:optionalInt
                                  optionalEnum:optionalEnum
                                optionalRecord:optionalRecord
                                  optionalList:optionalList];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestOptionals class]]) {
        return NO;
    }
    DBSwiftTestOptionals *typedOther = (DBSwiftTestOptionals *)other;
    return [self.requiredField isEqualToString:typedOther.requiredField] &&
            ((self.optionalString == nil && typedOther.optionalString == nil) || (self.optionalString != nil && [self.optionalString isEqual:typedOther.optionalString])) &&
            ((self.optionalInt == nil && typedOther.optionalInt == nil) || (self.optionalInt != nil && [self.optionalInt isEqual:typedOther.optionalInt])) &&
            self.optionalEnum == typedOther.optionalEnum &&
            ((self.optionalRecord == nil && typedOther.optionalRecord == nil) || (self.optionalRecord != nil && [self.optionalRecord isEqual:typedOther.optionalRecord])) &&
            ((self.optionalList == nil && typedOther.optionalList == nil) || (self.optionalList != nil && [self.optionalList isEqual:typedOther.optionalList]));
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.requiredField.hash;
    hashCode = hashCode * 31 + self.optionalString.hash;
    hashCode = hashCode * 31 + self.optionalInt.hash;
    hashCode = hashCode * 31 + (NSUInteger)self.optionalEnum;
    hashCode = hashCode * 31 + self.optionalRecord.hash;
    hashCode = hashCode * 31 + self.optionalList.dynamicHash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p requiredField:%@ optionalString:%@ optionalInt:%@ optionalEnum:%@ optionalRecord:%@ optionalList:%@>", self.class, (void *)self, self.requiredField, self.optionalString, self.optionalInt, self.optionalEnum, self.optionalRecord, self.optionalList];
}

#endif
@end
