// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestEmpty.h"
#include "swift_test_empty.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestEmpty;

namespace djinni_generated {

struct SwiftTestEmpty
{
    using CppType = ::testsuite::SwiftTestEmpty;
    using ObjcType = DBSwiftTestEmpty*;

    using Boxed = SwiftTestEmpty;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
