// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestBaseLabel+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SwiftTestBaseLabel::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    ::testsuite::SwiftTestBaseLabel model;
    model.mTextColor = ::djinni::I32::toCpp(obj.textColor);
    model.mFontSize = ::djinni::F32::toCpp(obj.fontSize);
    return model;
}

auto SwiftTestBaseLabel::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSwiftTestBaseLabel alloc] initWithTextColor:(::djinni::I32::fromCpp(cpp.text_color))
                                                  fontSize:(::djinni::F32::fromCpp(cpp.font_size))];
}

} // namespace djinni_generated
