// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestLabel.h"
#include "swift_test_label.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBSwiftTestLabel;

namespace djinni_generated {

struct SwiftTestLabel
{
    using CppType = ::testsuite::SwiftTestLabel;
    using ObjcType = DBSwiftTestLabel*;

    using Boxed = SwiftTestLabel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
