// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import <Foundation/Foundation.h>

/** Enum with multi-word cases (underscore-separated in Djinni) */
typedef NS_ENUM(NSInteger, DBSwiftTestShadowElevation)
{
    DBSwiftTestShadowElevationNone = 0,
    DBSwiftTestShadowElevationLowShadow = 1,
    DBSwiftTestShadowElevationMediumShadow = 2,
    DBSwiftTestShadowElevationHighShadow = 3,
};
