// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import <Foundation/Foundation.h>

/**
 * ============================================================
 * Test: Enum default values in records
 * Verifies: default value conversion (EnumType::Value -> .value)
 * ============================================================
 */
typedef NS_ENUM(NSInteger, DBSwiftTestLetterCase)
{
    DBSwiftTestLetterCaseDefault = 0,
    DBSwiftTestLetterCaseUpper = 1,
    DBSwiftTestLetterCaseLower = 2,
};
