// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import <Foundation/Foundation.h>

/**
 * ============================================================
 * Test: Empty record (only constants, no fields)
 * Verifies: struct with no fields, no init
 * ============================================================
 */
@interface DBSwiftTestEmpty : NSObject
- (nonnull instancetype)init NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)swiftTestEmpty;

@end

extern int32_t const DBSwiftTestEmptySomeConst;
