// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import "DBSwiftTestDocumented.h"
#import "DjinniUtils.h"


@implementation DBSwiftTestDocumented

- (nonnull instancetype)initWithText:(nonnull NSString *)text
                             visible:(BOOL)visible
{
    if (self = [super init]) {
        _text = [text copy];
        _visible = visible;
    }
    return self;
}

+ (nonnull instancetype)swiftTestDocumentedWithText:(nonnull NSString *)text
                                            visible:(BOOL)visible
{
    return [[self alloc] initWithText:text
                              visible:visible];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBSwiftTestDocumented class]]) {
        return NO;
    }
    DBSwiftTestDocumented *typedOther = (DBSwiftTestDocumented *)other;
    return [self.text isEqualToString:typedOther.text] &&
            self.visible == typedOther.visible;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + self.text.hash;
    hashCode = hashCode * 31 + (NSUInteger)self.visible;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p text:%@ visible:%@>", self.class, (void *)self, self.text, @(self.visible)];
}

#endif
@end
