// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from swift_test.djinni

#import <Foundation/Foundation.h>

#import "DBSwiftTestBaseLabel.h"
@interface DBSwiftTestLabel : DBSwiftTestBaseLabel
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithTextColor:(int32_t)textColor
                                 fontSize:(float)fontSize
                                     text:(nonnull NSString *)text
                                   isBold:(BOOL)isBold NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)swiftTestLabelWithTextColor:(int32_t)textColor
                                           fontSize:(float)fontSize
                                               text:(nonnull NSString *)text
                                             isBold:(BOOL)isBold;

@property (nonatomic, readonly, nonnull) NSString * text;

@property (nonatomic, readonly) BOOL isBold;

@end
