// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from ident_explicit.djinni

#import "DBTestIdentRecord.h"
#import "DjinniUtils.h"


NSString * __nonnull const DBTestIdentRecordRecordConstValueNative = @"test";

int32_t const DBTestIdentRecordXXXWeirdCaseNative = 1;

@implementation DBTestIdentRecord

- (nonnull instancetype)initWithFirstValue:(int32_t)FirstValue
                               secondValue:(nonnull NSString *)secondValue
{
    if (self = [super init]) {
        _FirstValue = FirstValue;
        _secondValue = [secondValue copy];
    }
    return self;
}

+ (nonnull instancetype)testIdentRecordWithFirstValue:(int32_t)FirstValue
                                          secondValue:(nonnull NSString *)secondValue
{
    return [[self alloc] initWithFirstValue:FirstValue
                                secondValue:secondValue];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBTestIdentRecord class]]) {
        return NO;
    }
    DBTestIdentRecord *typedOther = (DBTestIdentRecord *)other;
    return self.FirstValue == typedOther.FirstValue &&
            [self.secondValue isEqualToString:typedOther.secondValue];
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.FirstValue;
    hashCode = hashCode * 31 + self.secondValue.hash;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p FirstValue:%@ secondValue:%@>", self.class, (void *)self, @(self.FirstValue), self.secondValue];
}

#endif
@end
