// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from varnames.djinni

#import "DBVarnameRecord.h"
#import "DjinniUtils.h"


@implementation DBVarnameRecord

- (nonnull instancetype)initWithField:(int8_t)Field
{
    if (self = [super init]) {
        _Field = Field;
    }
    return self;
}

+ (nonnull instancetype)VarnameRecordWithField:(int8_t)Field
{
    return [[self alloc] initWithField:Field];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[DBVarnameRecord class]]) {
        return NO;
    }
    DBVarnameRecord *typedOther = (DBVarnameRecord *)other;
    return self.Field == typedOther.Field;
}

- (NSUInteger)hash
{
    NSUInteger hashCode = 17;
    hashCode = hashCode * 31 + (NSUInteger)self.Field;
    return hashCode;
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p Field:%@>", self.class, (void *)self, @(self.Field)];
}

#endif
@end
