/**
  * Copyright 2014 Dropbox, Inc.
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *    http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */

package djinni

import djinni.ast._
import djinni.generatorTools._
import djinni.meta._
import djinni.writer.IndentWriter

import scala.collection.mutable

class SwiftGenerator(spec: Spec) extends Generator(spec) {

  val marshal = new SwiftMarshal(spec)

  // Swift reserved keywords that need backtick escaping when used as identifiers
  private val swiftKeywords = Set(
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "continue", "default", "defer", "do",
    "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
    "switch", "where", "while", "as", "Any", "catch", "false", "is", "nil",
    "super", "self", "Self", "throw", "throws", "true", "try", "none"
  )

  private def escapeSwiftKeyword(name: String): String =
    if (swiftKeywords.contains(name)) s"`$name`" else name

  // Lowercase the first character, preserve rest (for enum cases), escape keywords
  private val swiftEnumCase: IdentConverter = (s: String) => {
    val converted = if (s.isEmpty) s else s.charAt(0).toLower + s.substring(1)
    escapeSwiftKeyword(converted)
  }

  // camelLower for field names
  private val swiftField: IdentConverter = IdentStyle.camelLower

  class SwiftRefs() {
    var imports = mutable.TreeSet[String]()
    imports.add("Foundation")

    def find(ty: TypeRef) { find(ty.resolved) }
    def find(tm: MExpr) {
      tm.args.foreach(find)
      findBase(tm.base)
    }
    private def findBase(m: Meta) {
      if (marshal.needsUIKit(m)) {
        imports.add("UIKit")
      }
      val module = marshal.importForMeta(m)
      if (module.nonEmpty) {
        imports.add(module)
      }
    }
  }

  private def writeSwiftFile(fileName: String, origin: String, refs: SwiftRefs, f: IndentWriter => Unit) {
    createFile(spec.swiftOutFolder.get, fileName + ".swift", (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      // If UIKit is in imports, it implies Foundation, so we can just import UIKit
      if (refs.imports.contains("UIKit")) {
        refs.imports.remove("Foundation")
      }
      for (imp <- refs.imports) {
        w.wl(s"import $imp")
      }
      w.wl
      f(w)
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: Enum) {
    val refs = new SwiftRefs()
    val swiftName = marshal.typename(ident, e)

    writeSwiftFile(swiftName, origin, refs, w => {
      writeDoc(w, doc)
      val options = normalEnumOptions(e)
      val rawType = if (options.nonEmpty) ": Int, Sendable" else ": Sendable"
      w.w(s"public enum $swiftName$rawType").braced {
        var shift = 0
        for (o <- options) {
          writeDoc(w, o.doc)
          w.wl(s"case ${swiftEnumCase(o.ident.name)} = $shift")
          shift += 1
        }
      }
    })
  }

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record, idl: Seq[TypeDecl]) {
    val refs = new SwiftRefs()

    // Collect all fields including inherited ones (flattened)
    val superRecord = getSuperRecord(idl, r)
    val superFields: Seq[Field] = superRecord match {
      case None => Seq.empty
      case Some(value) => value.fields
    }
    val allFields = superFields ++ r.fields

    // Filter out fields whose types should be skipped in Swift
    val fields = allFields.filter(f => !marshal.shouldSkipField(f.ty.resolved))

    // Collect imports from all non-skipped fields
    fields.foreach(f => refs.find(f.ty))

    val swiftName = marshal.typename(ident, r)

    writeSwiftFile(swiftName, origin, refs, w => {
      writeDoc(w, doc)
      w.w(s"public struct $swiftName: Sendable").braced {
        // Field declarations
        for (f <- fields) {
          writeDoc(w, f.doc)
          w.wl(s"public let ${swiftField(f.ident)}: ${marshal.fieldType(f.ty)}")
        }

        if (fields.nonEmpty) {
          w.wl

          // Public memberwise init
          val initParams = fields.map(f => {
            val fieldName = swiftField(f.ident)
            val fieldType = marshal.fieldType(f.ty)
            swiftDefaultValue(f) match {
              case Some(dv) => s"$fieldName: $fieldType = $dv"
              case None => s"$fieldName: $fieldType"
            }
          })
          if (initParams.size == 1) {
            w.w(s"public init(${initParams.head})")
          } else {
            w.wl("public init(")
            w.increase()
            for ((p, i) <- initParams.zipWithIndex) {
              val sep = if (i < initParams.size - 1) "," else ""
              w.wl(s"$p$sep")
            }
            w.decrease()
            w.w(")")
          }
          w.braced {
            for (f <- fields) {
              val fieldName = swiftField(f.ident)
              w.wl(s"self.$fieldName = $fieldName")
            }
          }
        }
      }
    })
  }

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {
    // No-op: interfaces are not generated for Swift
  }

  // Convert a Djinni default value to a Swift expression, or return None
  private def swiftDefaultValue(f: Field): Option[String] = {
    // Check if the field is optional — default to nil
    val isOptional = f.ty.resolved.base == MOptional

    if (f.defaultValue.nonEmpty) {
      // Default value specified in IDL, e.g. "LetterCase::Default"
      Some(convertDefaultValue(f.defaultValue, f.ty.resolved))
    } else if (isOptional) {
      Some("nil")
    } else {
      None
    }
  }

  // Convert a Djinni default value expression to Swift syntax
  private def convertDefaultValue(value: String, tm: MExpr): String = {
    // Handle enum default values like "LetterCase::Default" → ".default"
    if (value.contains("::")) {
      val parts = value.split("::")
      if (parts.length == 2) {
        "." + swiftEnumCase(parts(1).trim)
      } else {
        value
      }
    } else {
      // Literal values (numbers, booleans, strings)
      value
    }
  }
}
