// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "child_item.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeChildItem
{
    using CppType = ::textsort::ChildItem;
    using JsType = em::val;
    using Boxed = NativeChildItem;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
