// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeLevelE.hpp"  // my header

namespace djinni_generated {

auto NativeLevelE::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["fieldE"])};
}
auto NativeLevelE::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("fieldE", ::djinni::String::Boxed::fromCpp(c.fieldE));
    return js;
}

} // namespace djinni_generated
