// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "LevelD.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeLevelD
{
    using CppType = ::textsort::LevelD;
    using JsType = em::val;
    using Boxed = NativeLevelD;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
