// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeSubChildItem.hpp"  // my header

namespace djinni_generated {

auto NativeSubChildItem::toCpp(const JsType& j) -> CppType {
    return {::djinni::I32::Boxed::toCpp(j["index"])};
}
auto NativeSubChildItem::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("index", ::djinni::I32::Boxed::fromCpp(c.index));
    return js;
}

} // namespace djinni_generated
