// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeLevelF.hpp"  // my header

namespace djinni_generated {

auto NativeLevelF::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["fieldF"])};
}
auto NativeLevelF::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("fieldF", ::djinni::String::Boxed::fromCpp(c.fieldF));
    return js;
}

} // namespace djinni_generated
