// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeLevelC.hpp"  // my header

namespace djinni_generated {

auto NativeLevelC::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["fieldC"])};
}
auto NativeLevelC::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("fieldC", ::djinni::String::Boxed::fromCpp(c.fieldC));
    return js;
}

} // namespace djinni_generated
