// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "LevelB.hpp"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeLevelB
{
    using CppType = ::textsort::LevelB;
    using JsType = em::val;
    using Boxed = NativeLevelB;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
